// ============================================================
//  ARSENAL IA — BIBLIOTECA DE PROMPTS (parte 9)
//  Subir a 30: Marketing · Ventas · Redes · Copywriting
//  Negocios · Diseño · Productividad
// ============================================================

const PROMPTS_9 = [

// ---------- MARKETING (+10) ----------
{ cat:"marketing", t:{es:"Estrategia de marca en redes", en:"Brand strategy on social media"},
  p:{es:"Actúa como estratega de marca. Diseña una estrategia para construir y fortalecer la marca de [NEGOCIO] en redes sociales. Define: la personalidad de la marca, el tono de comunicación, los valores a transmitir, el tipo de contenido que refuerza la marca y cómo lograr que la gente la reconozca y la recuerde. Práctica y aplicable para [PÚBLICO].",
     en:"Act as a brand strategist. Design a strategy to build and strengthen the brand of [BUSINESS] on social media. Define: the brand personality, the communication tone, the values to convey, the type of content that reinforces the brand and how to make people recognize and remember it. Practical and applicable for [AUDIENCE]."}},

{ cat:"marketing", t:{es:"Plan de marketing con poco presupuesto", en:"Low-budget marketing plan"},
  p:{es:"Eres experto en marketing de bajo costo. Tengo un presupuesto muy limitado para promocionar [NEGOCIO/PRODUCTO]. Dame un plan de marketing con estrategias gratuitas o muy económicas: marketing orgánico, alianzas, contenido, boca a boca, y cómo aprovechar lo que ya tengo. Prioriza las acciones por impacto vs costo. Realista para alguien que empieza.",
     en:"You're a low-cost marketing expert. I have a very limited budget to promote [BUSINESS/PRODUCT]. Give me a marketing plan with free or very cheap strategies: organic marketing, partnerships, content, word of mouth, and how to leverage what I already have. Prioritize the actions by impact vs cost. Realistic for someone starting out."}},

{ cat:"marketing", t:{es:"Ángulos de venta para un producto", en:"Selling angles for a product"},
  p:{es:"Actúa como estratega creativo. Para [PRODUCTO], dame 8 ángulos de venta distintos para promocionarlo (diferentes formas de presentar el mismo producto según lo que le importa a cada tipo de cliente). Por ejemplo: por ahorro de tiempo, por estatus, por resultados, por facilidad, etc. Para cada ángulo, el mensaje principal y a quién le hablaría.",
     en:"Act as a creative strategist. For [PRODUCT], give me 8 different selling angles to promote it (different ways to present the same product based on what matters to each type of customer). For example: time savings, status, results, ease, etc. For each angle, the main message and who it would speak to."}},

{ cat:"marketing", t:{es:"Idea de campaña viral", en:"Viral campaign idea"},
  p:{es:"Eres experto en marketing viral. Dame 5 ideas de campañas con potencial de volverse virales para promocionar [NEGOCIO/PRODUCTO]. Para cada una: el concepto, por qué la gente la compartiría, cómo ejecutarla con pocos recursos y qué resultado buscaría. Enfócate en ideas creativas que generen conversación y alcance orgánico. Marca la más prometedora.",
     en:"You're a viral marketing expert. Give me 5 campaign ideas with potential to go viral to promote [BUSINESS/PRODUCT]. For each: the concept, why people would share it, how to execute it with few resources and what result it would seek. Focus on creative ideas that generate conversation and organic reach. Mark the most promising one."}},

{ cat:"marketing", t:{es:"Mensaje para atraer a tu cliente ideal", en:"Message to attract your ideal customer"},
  p:{es:"Actúa como copywriter de marketing. Para [PRODUCTO/SERVICIO] dirigido a [CLIENTE IDEAL], escribe un mensaje que hable directamente a esa persona, que sienta que es para ella. Que mencione su situación, su deseo o problema, y cómo mi producto encaja perfecto con lo que busca. Que genere ese 'esto es justo lo que necesitaba'. Cercano y específico.",
     en:"Act as a marketing copywriter. For [PRODUCT/SERVICE] aimed at [IDEAL CUSTOMER], write a message that speaks directly to that person, so they feel it's for them. It should mention their situation, their desire or problem, and how my product fits perfectly with what they're looking for. It should generate that 'this is exactly what I needed'. Warm and specific."}},

{ cat:"marketing", t:{es:"Aprovecha una tendencia para vender", en:"Leverage a trend to sell"},
  p:{es:"Eres experto en marketing de tendencias. Está de moda [TENDENCIA/TEMA ACTUAL] y quiero aprovecharlo para promocionar [PRODUCTO]. Dame ideas de cómo conectar mi producto con esa tendencia de forma natural y oportuna: qué contenido crear, qué mensaje usar, y cómo subirme a la conversación sin que se vea forzado. Que aproveche el momento para ganar visibilidad.",
     en:"You're a trend marketing expert. [CURRENT TREND/TOPIC] is trending and I want to leverage it to promote [PRODUCT]. Give me ideas on how to connect my product with that trend naturally and timely: what content to create, what message to use, and how to join the conversation without it looking forced. It should seize the moment to gain visibility."}},

{ cat:"marketing", t:{es:"Programa de fidelización de clientes", en:"Customer loyalty program"},
  p:{es:"Actúa como experto en retención. Diseña un programa de fidelización para que los clientes de [NEGOCIO] vuelvan a comprar y me recomienden. Dame: qué recompensas o beneficios ofrecer, cómo estructurarlo de forma simple, cómo comunicarlo, y cómo hacer que los clientes se sientan especiales. Práctico y aplicable para un negocio pequeño. Que aumente las compras repetidas.",
     en:"Act as a retention expert. Design a loyalty program so customers of [BUSINESS] buy again and recommend me. Give me: what rewards or benefits to offer, how to structure it simply, how to communicate it, and how to make customers feel special. Practical and applicable for a small business. It should increase repeat purchases."}},

{ cat:"marketing", t:{es:"Compara tu producto con la competencia", en:"Compare your product with competitors"},
  p:{es:"Eres estratega de marketing. Ayúdame a crear una comparación honesta y persuasiva entre mi producto [PRODUCTO] y las alternativas de la competencia. Destaca mis ventajas reales sin atacar directamente a otros, enfócate en lo que me hace mejor opción para el cliente, y preséntalo de forma que ayude a decidir a mi favor. Para usar en mi página o ventas. Convincente pero ético.",
     en:"You're a marketing strategist. Help me create an honest, persuasive comparison between my product [PRODUCT] and the competition's alternatives. Highlight my real advantages without directly attacking others, focus on what makes me the better option for the customer, and present it in a way that helps them decide in my favor. To use on my page or sales. Convincing but ethical."}},

{ cat:"marketing", t:{es:"Webinar o clase gratis para vender", en:"Free webinar or class to sell"},
  p:{es:"Actúa como experto en marketing educativo. Quiero hacer un webinar o clase gratuita para atraer clientes y luego venderles [PRODUCTO]. Ayúdame a planearlo: qué tema enseñar que atraiga a mi público, cómo estructurar la clase para aportar valor y generar confianza, y cómo presentar mi oferta al final sin que se sienta solo como una venta. Que convierta asistentes en clientes.",
     en:"Act as an educational marketing expert. I want to do a free webinar or class to attract customers and then sell them [PRODUCT]. Help me plan it: what topic to teach that attracts my audience, how to structure the class to provide value and build trust, and how to present my offer at the end without it feeling just like a sale. It should convert attendees into customers."}},

{ cat:"marketing", t:{es:"Mide los resultados de tu marketing", en:"Measure your marketing results"},
  p:{es:"Eres analista de marketing. Ayúdame a entender qué debo medir para saber si mi marketing está funcionando en [NEGOCIO]. Explícame de forma simple: qué indicadores importan según mi objetivo (más ventas, más seguidores, más visitas), cómo interpretarlos, y cómo usar esa información para mejorar. Sin tecnicismos complicados, práctico para alguien que no es experto en datos.",
     en:"You're a marketing analyst. Help me understand what I should measure to know if my marketing is working in [BUSINESS]. Explain simply: what indicators matter based on my goal (more sales, more followers, more visits), how to interpret them, and how to use that information to improve. Without complicated jargon, practical for someone who isn't a data expert."}},

// ---------- VENTAS (+10) ----------
{ cat:"sales", t:{es:"Script de llamada de ventas", en:"Sales call script"},
  p:{es:"Actúa como experto en ventas telefónicas. Escríbeme un guion para una llamada de ventas de [PRODUCTO]. Incluye: cómo abrir la llamada para captar interés, preguntas para entender la necesidad, cómo presentar el producto según lo que necesita, cómo manejar las objeciones comunes, y cómo cerrar o agendar el siguiente paso. Natural y conversacional, no robótico.",
     en:"Act as a phone sales expert. Write me a script for a sales call for [PRODUCT]. Include: how to open the call to capture interest, questions to understand the need, how to present the product based on what they need, how to handle common objections, and how to close or schedule the next step. Natural and conversational, not robotic."}},

{ cat:"sales", t:{es:"Vende a un cliente que compara precios", en:"Sell to a price-comparing customer"},
  p:{es:"Eres cerrador experto. Un cliente está comparando mi producto [PRODUCTO] con otros más baratos. Dame argumentos y respuestas para mostrarle por qué vale la pena elegirme aunque no sea el más barato: cómo destacar el valor, la calidad, el respaldo, los resultados, y cómo hacer que entienda que lo barato puede salir caro. Sin hablar mal de la competencia. Persuasivo y honesto.",
     en:"You're an expert closer. A customer is comparing my product [PRODUCT] with cheaper ones. Give me arguments and responses to show them why it's worth choosing me even if I'm not the cheapest: how to highlight value, quality, support, results, and how to make them understand that cheap can end up expensive. Without badmouthing the competition. Persuasive and honest."}},

{ cat:"sales", t:{es:"Aumenta la confianza antes de vender", en:"Build trust before selling"},
  p:{es:"Actúa como experto en ventas relacionales. Antes de venderle a alguien que apenas me conoce, quiero generar confianza. Dame estrategias y mensajes para construir esa confianza primero: cómo demostrar que soy real y confiable, cómo aportar valor antes de vender, qué compartir para reducir su desconfianza, y cómo lograr que se sienta seguro de comprarme. Aplicable por WhatsApp o redes.",
     en:"Act as a relational sales expert. Before selling to someone who barely knows me, I want to build trust. Give me strategies and messages to build that trust first: how to show I'm real and trustworthy, how to provide value before selling, what to share to reduce their distrust, and how to make them feel safe buying from me. Applicable via WhatsApp or social media."}},

{ cat:"sales", t:{es:"Cierra una venta por WhatsApp", en:"Close a sale on WhatsApp"},
  p:{es:"Eres experto en ventas por WhatsApp. Tengo un cliente interesado en [PRODUCTO] que ya hizo varias preguntas. Dame los mensajes exactos para llevarlo al cierre: cómo resumir el valor, cómo presentar el precio y la forma de pago, cómo crear un motivo para decidir ya, y cómo guiarlo paso a paso hasta que pague. Mensajes naturales y cercanos, listos para enviar.",
     en:"You're a WhatsApp sales expert. I have a customer interested in [PRODUCT] who already asked several questions. Give me the exact messages to take them to the close: how to summarize the value, how to present the price and payment method, how to create a reason to decide now, and how to guide them step by step until they pay. Natural, warm messages, ready to send."}},

{ cat:"sales", t:{es:"Ofrece un descuento sin desvalorizar", en:"Offer a discount without devaluing"},
  p:{es:"Actúa como estratega de ventas. Quiero ofrecer un descuento en [PRODUCTO] para cerrar una venta, pero sin que parezca que mi producto vale menos o que siempre voy a rebajar. Dame formas inteligentes de ofrecer el descuento: con una justificación (por tiempo, por ser nuevo cliente, etc.), condiciones, y cómo presentarlo para que el cliente lo valore. Que cierre la venta sin dañar mi imagen.",
     en:"Act as a sales strategist. I want to offer a discount on [PRODUCT] to close a sale, but without making it seem my product is worth less or that I'll always lower the price. Give me smart ways to offer the discount: with a justification (time-limited, new customer, etc.), conditions, and how to present it so the customer values it. It should close the sale without damaging my image."}},

{ cat:"sales", t:{es:"Detecta si un cliente está listo para comprar", en:"Detect if a customer is ready to buy"},
  p:{es:"Eres experto en ventas. Enséñame a identificar las señales de que un cliente está listo para comprar [PRODUCTO] durante una conversación. Dame: qué frases o preguntas indican interés real, cómo distinguir al que solo curiosea del que va a comprar, y qué hacer en cada caso para avanzar hacia el cierre en el momento justo, sin presionar antes de tiempo ni dejar pasar la oportunidad.",
     en:"You're a sales expert. Teach me to identify the signs that a customer is ready to buy [PRODUCT] during a conversation. Give me: what phrases or questions indicate real interest, how to tell the one just browsing from the one who'll buy, and what to do in each case to move toward the close at the right moment, without pressuring too early or letting the opportunity pass."}},

{ cat:"sales", t:{es:"Convierte 'no' en una futura venta", en:"Turn a 'no' into a future sale"},
  p:{es:"Actúa como experto en ventas a largo plazo. Un cliente me dijo que no por ahora a [PRODUCTO]. Dame estrategias para mantener la relación y convertir ese 'no' en una venta futura: cómo responder con elegancia, cómo quedar bien posicionado para cuando esté listo, cómo seguir en contacto sin presionar, y cuándo y cómo retomar. Que no cierre la puerta, sino que la deje entreabierta.",
     en:"Act as a long-term sales expert. A customer told me no for now to [PRODUCT]. Give me strategies to maintain the relationship and turn that 'no' into a future sale: how to respond gracefully, how to stay well positioned for when they're ready, how to keep in touch without pressuring, and when and how to follow up. Don't close the door, leave it ajar."}},

{ cat:"sales", t:{es:"Presenta el precio con seguridad", en:"Present the price with confidence"},
  p:{es:"Eres coach de ventas. Me da inseguridad decir el precio de [PRODUCTO] y a veces hasta lo bajo solo. Enséñame a presentar el precio con seguridad y sin titubear: cómo decirlo con confianza, cómo justificar el valor antes del precio, cómo no disculparme por cobrar, y cómo mantenerme firme si el cliente regatea. Dame frases y un enfoque mental para hacerlo bien. Que transmita que mi producto vale lo que cuesta.",
     en:"You're a sales coach. I feel insecure saying the price of [PRODUCT] and sometimes even lower it on my own. Teach me to present the price with confidence and without hesitating: how to say it confidently, how to justify the value before the price, how not to apologize for charging, and how to stay firm if the customer haggles. Give me phrases and a mindset to do it well. It should convey that my product is worth what it costs."}},

{ cat:"sales", t:{es:"Guion para vender en vivo o presencial", en:"Script to sell live or in person"},
  p:{es:"Actúa como vendedor experto. Voy a vender [PRODUCTO] en persona o en un live. Dame un guion: cómo captar la atención al inicio, cómo presentar el producto mostrando sus beneficios, cómo generar deseo y urgencia, cómo manejar las dudas en vivo, y cómo cerrar invitando a comprar ahí mismo. Dinámico y persuasivo, adaptado a una interacción en tiempo real. Que genere ventas en el momento.",
     en:"Act as an expert salesperson. I'm going to sell [PRODUCT] in person or on a live. Give me a script: how to grab attention at the start, how to present the product showing its benefits, how to generate desire and urgency, how to handle doubts live, and how to close by inviting them to buy right there. Dynamic and persuasive, adapted to a real-time interaction. It should generate sales on the spot."}},

{ cat:"sales", t:{es:"Vende un servicio de alto valor", en:"Sell a high-value service"},
  p:{es:"Eres experto en venta de servicios premium. Ofrezco [SERVICIO DE ALTO VALOR] y necesito venderlo a un precio alto. Dame una estrategia: cómo comunicar el valor para justificar el precio, cómo posicionarme como la mejor opción, cómo manejar la objeción del precio en servicios caros, y cómo generar la confianza necesaria para que inviertan en mí. Para clientes que buscan calidad, no lo más barato.",
     en:"You're a premium service sales expert. I offer [HIGH-VALUE SERVICE] and need to sell it at a high price. Give me a strategy: how to communicate the value to justify the price, how to position myself as the best option, how to handle the price objection in expensive services, and how to build the trust needed for them to invest in me. For customers who seek quality, not the cheapest."}},

// ---------- REDES SOCIALES (+10) ----------
{ cat:"social", t:{es:"Gancho para los primeros segundos de un Reel", en:"Hook for the first seconds of a Reel"},
  p:{es:"Actúa como experto en contenido viral. Para un Reel sobre [TEMA] en el nicho de [NICHO], dame 10 ganchos para los primeros 3 segundos que eviten que la gente siga deslizando. Varía los tipos: pregunta, promesa, error común, dato sorprendente, intriga. Que en una frase capturen la atención y obliguen a quedarse a ver. Marca los 3 más potentes.",
     en:"Act as a viral content expert. For a Reel about [TOPIC] in the [NICHE] niche, give me 10 hooks for the first 3 seconds that prevent people from scrolling. Vary the types: question, promise, common mistake, surprising fact, intrigue. In one phrase they should capture attention and force people to stay and watch. Mark the 3 most powerful."}},

{ cat:"social", t:{es:"Publicación que genera guardados", en:"Post that gets saves"},
  p:{es:"Eres experto en contenido de valor. Crea una publicación para [RED SOCIAL] sobre [TEMA] que la gente quiera guardar para volver a verla después (tips, lista, guía, recursos). Dame el contenido completo: el gancho de portada, el valor organizado de forma útil, y un cierre que invite a guardar y compartir. Que sea tan útil que la gente no quiera perderla. Para [PÚBLICO].",
     en:"You're a value content expert. Create a post for [SOCIAL NETWORK] about [TOPIC] that people want to save to revisit later (tips, list, guide, resources). Give me the complete content: the cover hook, the value organized usefully, and a closing that invites saving and sharing. It should be so useful people don't want to lose it. For [AUDIENCE]."}},

{ cat:"social", t:{es:"Responde comentarios para generar comunidad", en:"Reply to comments to build community"},
  p:{es:"Actúa como community manager experto. Dame estrategias y ejemplos para responder los comentarios en mis publicaciones de [NICHO] de forma que genere comunidad y más interacción. Cómo responder a elogios, a preguntas, a críticas, y cómo provocar más conversación con mis respuestas. Que la gente sienta cercanía y quiera seguir interactuando. Con ejemplos de respuestas para distintos casos.",
     en:"Act as an expert community manager. Give me strategies and examples to reply to comments on my [NICHE] posts in a way that builds community and more interaction. How to respond to praise, questions, criticism, and how to spark more conversation with my replies. People should feel warmth and want to keep interacting. With example responses for different cases."}},

{ cat:"social", t:{es:"Idea de contenido para cada día de la semana", en:"Content idea for each day of the week"},
  p:{es:"Eres estratega de contenido. Dame un concepto de contenido temático para cada día de la semana para una cuenta de [NICHO] (como #LunesDeTips, #ViernesDePreguntas, etc.). Para cada día: el nombre del tema, qué publicar y por qué funcionaría con mi audiencia. Que le den estructura a mi semana y la gente sepa qué esperar cada día. Creativo y aplicable.",
     en:"You're a content strategist. Give me a thematic content concept for each day of the week for a [NICHE] account (like #TipTuesday, #QuestionFriday, etc.). For each day: the theme name, what to post and why it would work with my audience. They should give structure to my week and people know what to expect each day. Creative and applicable."}},

{ cat:"social", t:{es:"Texto para promocionar tu producto en redes", en:"Copy to promote your product on social"},
  p:{es:"Actúa como copywriter de redes sociales. Escribe 3 publicaciones distintas para promocionar [PRODUCTO] en [RED SOCIAL] sin sonar solo a venta. Una enfocada en el problema que resuelve, una mostrando un beneficio o resultado, y una con prueba o testimonio. Que aporten valor o conecten, e inviten sutilmente a comprar o saber más. Cercanas y persuasivas para [PÚBLICO].",
     en:"Act as a social media copywriter. Write 3 different posts to promote [PRODUCT] on [SOCIAL NETWORK] without sounding just salesy. One focused on the problem it solves, one showing a benefit or result, and one with proof or testimonial. They should provide value or connect, and subtly invite buying or learning more. Warm and persuasive for [AUDIENCE]."}},

{ cat:"social", t:{es:"Crea expectativa antes de un lanzamiento", en:"Build hype before a launch"},
  p:{es:"Eres experto en lanzamientos en redes. Voy a lanzar [PRODUCTO] pronto y quiero generar expectativa antes. Dame una secuencia de publicaciones e historias para los días previos que despierten curiosidad e interés, sin revelar todo. Qué ir mostrando, cómo intrigar, y cómo hacer que la gente espere el lanzamiento con ganas. Que llegue al día del lanzamiento con una audiencia caliente lista para comprar.",
     en:"You're a social launch expert. I'm going to launch [PRODUCT] soon and want to build anticipation beforehand. Give me a sequence of posts and stories for the days before that spark curiosity and interest, without revealing everything. What to show, how to intrigue, and how to make people eagerly await the launch. So I arrive at launch day with a warm audience ready to buy."}},

{ cat:"social", t:{es:"Publicación de antes y después", en:"Before and after post"},
  p:{es:"Actúa como creador de contenido. Ayúdame a crear una publicación de 'antes y después' relacionada con [PRODUCTO/SERVICIO/TEMA] para [RED SOCIAL]. Que muestre la transformación o el resultado de forma atractiva, cuente la historia detrás, y conecte con quien quiere lograr ese mismo cambio. Que genere deseo e interés en lograr ese 'después'. Con el texto y la estructura sugerida.",
     en:"Act as a content creator. Help me create a 'before and after' post related to [PRODUCT/SERVICE/TOPIC] for [SOCIAL NETWORK]. It should show the transformation or result attractively, tell the story behind it, and connect with whoever wants to achieve that same change. It should generate desire and interest in achieving that 'after'. With the suggested text and structure."}},

{ cat:"social", t:{es:"Aumenta tus seguidores orgánicamente", en:"Grow your followers organically"},
  p:{es:"Eres experto en crecimiento orgánico. Tengo una cuenta de [NICHO] y quiero crecer sin pagar publicidad. Dame una estrategia concreta: qué tipo de contenido atrae más seguidores, cómo aprovechar tendencias y formatos virales, cómo aumentar el alcance, cómo colaborar con otros, y qué hábitos de publicación seguir. Realista y aplicable para crecer paso a paso. Que aumente mi audiencia con el tiempo.",
     en:"You're an organic growth expert. I have a [NICHE] account and want to grow without paying for ads. Give me a concrete strategy: what type of content attracts more followers, how to leverage trends and viral formats, how to increase reach, how to collaborate with others, and what posting habits to follow. Realistic and applicable to grow step by step. It should increase my audience over time."}},

{ cat:"social", t:{es:"Pie de foto corto y con gancho", en:"Short caption with a hook"},
  p:{es:"Actúa como copywriter de redes. Dame 10 pies de foto (captions) cortos y con gancho para publicaciones de [NICHO]. Que sean breves pero impactantes, que generen curiosidad, identificación o ganas de comentar. Ideales para fotos o Reels donde el texto debe ser corto pero efectivo. Adaptados a un tono [TONO: cercano, divertido, profesional] para [PÚBLICO]. Marca los 3 mejores.",
     en:"Act as a social copywriter. Give me 10 short captions with a hook for [NICHE] posts. They should be brief but impactful, generating curiosity, relatability or the urge to comment. Ideal for photos or Reels where the text must be short but effective. Adapted to a [TONE: warm, fun, professional] tone for [AUDIENCE]. Mark the 3 best."}},

{ cat:"social", t:{es:"Convierte un cliente feliz en contenido", en:"Turn a happy customer into content"},
  p:{es:"Eres experto en prueba social en redes. Un cliente quedó feliz con [PRODUCTO/SERVICIO]. Ayúdame a convertir esa experiencia en contenido que genere confianza y atraiga más clientes. Dame: cómo pedirle permiso y material, cómo presentar su testimonio o caso de forma atractiva en redes, y qué formato usar (historia, publicación, video). Que muestre resultados reales y motive a otros a comprar.",
     en:"You're a social proof expert. A customer was happy with [PRODUCT/SERVICE]. Help me turn that experience into content that builds trust and attracts more customers. Give me: how to ask for permission and material, how to present their testimonial or case attractively on social media, and what format to use (story, post, video). It should show real results and motivate others to buy."}},

// ---------- COPYWRITING (+10) ----------
{ cat:"copywriting", t:{es:"Fórmula PAS para tu texto", en:"PAS formula for your copy"},
  p:{es:"Actúa como copywriter experto. Escribe un texto de venta para [PRODUCTO] usando la fórmula PAS: Problema (identifica el dolor del cliente), Agitación (haz que sienta ese problema y sus consecuencias) y Solución (presenta mi producto como el alivio). Que conecte emocionalmente y lleve naturalmente a querer comprar. Explica brevemente cada parte mientras lo escribes. Persuasivo y empático.",
     en:"Act as an expert copywriter. Write a sales copy for [PRODUCT] using the PAS formula: Problem (identify the customer's pain), Agitation (make them feel that problem and its consequences) and Solution (present my product as the relief). It should connect emotionally and naturally lead to wanting to buy. Briefly explain each part as you write it. Persuasive and empathetic."}},

{ cat:"copywriting", t:{es:"Oferta irresistible en texto", en:"Irresistible offer in copy"},
  p:{es:"Eres copywriter de respuesta directa. Ayúdame a redactar una oferta irresistible para [PRODUCTO]. Combina y presenta de forma persuasiva: el producto principal y su valor, los bonos o extras, el precio con su descuento, la garantía, y la razón para comprar ya. Estructúralo de forma que el valor percibido sea mucho mayor que el precio. Que el cliente sienta que es una oportunidad que no puede dejar pasar.",
     en:"You're a direct-response copywriter. Help me write an irresistible offer for [PRODUCT]. Combine and present persuasively: the main product and its value, the bonuses or extras, the price with its discount, the guarantee, and the reason to buy now. Structure it so the perceived value is much greater than the price. The customer should feel it's an opportunity they can't pass up."}},

{ cat:"copywriting", t:{es:"Texto para historia de Instagram", en:"Copy for Instagram story"},
  p:{es:"Actúa como copywriter de redes. Escribe el texto para una serie de historias de Instagram que promocionen [PRODUCTO] de forma persuasiva. Divídelo en varias historias cortas que vayan llevando al espectador desde captar su atención hasta invitarlo a comprar, aprovechando el formato (con preguntas, encuestas, cuenta regresiva). Que mantenga el interés historia tras historia. Cercano y persuasivo.",
     en:"Act as a social copywriter. Write the copy for a series of Instagram stories that promote [PRODUCT] persuasively. Break it into several short stories that lead the viewer from grabbing attention to inviting them to buy, leveraging the format (with questions, polls, countdown). It should keep interest story after story. Warm and persuasive."}},

{ cat:"copywriting", t:{es:"Frases de cierre que impulsan la compra", en:"Closing phrases that drive purchase"},
  p:{es:"Eres copywriter experto en cierres. Para [PRODUCTO], dame 12 frases de cierre persuasivas para usar al final de un texto, anuncio o conversación, que impulsen al cliente a comprar ahora. Que combinen urgencia, beneficio y facilidad. Varía los enfoques. Que generen ese empujón final para pasar de la duda a la acción. Marca las 3 más efectivas y dime en qué contexto usar cada una.",
     en:"You're a closing-copy expert. For [PRODUCT], give me 12 persuasive closing phrases to use at the end of a copy, ad or conversation, that drive the customer to buy now. They should combine urgency, benefit and ease. Vary the approaches. They should create that final push to go from doubt to action. Mark the 3 most effective and tell me what context to use each in."}},

{ cat:"copywriting", t:{es:"Reescribe tu texto en distintos tonos", en:"Rewrite your copy in different tones"},
  p:{es:"Actúa como copywriter versátil. Toma este texto: \"[PEGA TU TEXTO]\" y reescríbelo en 3 tonos diferentes: uno profesional y serio, uno cercano y amigable, y uno divertido y desenfadado. Así puedo elegir el que mejor conecte con mi público. Mantén el mensaje principal en todas las versiones, adaptando solo el estilo. Muéstrame las 3 versiones claramente separadas.",
     en:"Act as a versatile copywriter. Take this text: \"[PASTE YOUR TEXT]\" and rewrite it in 3 different tones: one professional and serious, one warm and friendly, and one fun and casual. That way I can choose the one that best connects with my audience. Keep the main message in all versions, adapting only the style. Show me the 3 versions clearly separated."}},

{ cat:"copywriting", t:{es:"Texto para email de venta", en:"Copy for a sales email"},
  p:{es:"Eres copywriter de email. Escribe el texto de un email de venta para [PRODUCTO] dirigido a [PÚBLICO]. Que tenga un asunto que invite a abrir, una apertura que enganche, el desarrollo enfocado en el beneficio y en resolver una duda, y un cierre con llamada a la acción clara. Persuasivo, directo y cercano. Que logre que el lector haga clic y compre. Con el asunto incluido.",
     en:"You're an email copywriter. Write the copy of a sales email for [PRODUCT] aimed at [AUDIENCE]. It should have a subject that invites opening, an engaging opening, the body focused on the benefit and resolving a doubt, and a closing with a clear call to action. Persuasive, direct and warm. It should get the reader to click and buy. With the subject included."}},

{ cat:"copywriting", t:{es:"Describe el resultado que obtendrá el cliente", en:"Describe the result the customer gets"},
  p:{es:"Actúa como copywriter enfocado en beneficios. Para [PRODUCTO], escribe un texto que pinte vívidamente el resultado o la transformación que obtendrá el cliente después de usarlo. Que se imagine su vida o situación mejorada, que sienta el deseo de llegar a ese punto. Enfócate en cómo se sentirá y qué logrará, no en las características. Que despierte el deseo de comprar para conseguir ese resultado.",
     en:"Act as a benefit-focused copywriter. For [PRODUCT], write copy that vividly paints the result or transformation the customer will get after using it. They should imagine their life or situation improved, feel the desire to reach that point. Focus on how they'll feel and what they'll achieve, not on the features. It should spark the desire to buy to get that result."}},

{ cat:"copywriting", t:{es:"Texto corto para un anuncio", en:"Short copy for an ad"},
  p:{es:"Eres copywriter de publicidad. Escribe 5 textos cortos y potentes para un anuncio de [PRODUCTO] dirigido a [PÚBLICO]. Que en pocas palabras capten la atención, comuniquen el beneficio principal e inviten a la acción. Ideales para anuncios donde el espacio es limitado y cada palabra cuenta. Varía los enfoques y marca el más persuasivo. Directos y sin relleno.",
     en:"You're an advertising copywriter. Write 5 short, powerful copies for an ad of [PRODUCT] aimed at [AUDIENCE]. In few words they should capture attention, communicate the main benefit and invite action. Ideal for ads where space is limited and every word counts. Vary the approaches and mark the most persuasive one. Direct and no fluff."}},

{ cat:"copywriting", t:{es:"Crea curiosidad para que sigan leyendo", en:"Create curiosity so they keep reading"},
  p:{es:"Actúa como copywriter experto en retención. Para un texto sobre [TEMA/PRODUCTO], dame técnicas y ejemplos de cómo crear curiosidad para que el lector siga leyendo hasta el final. Cómo abrir bucles abiertos, hacer promesas, insinuar sin revelar, y mantener el interés párrafo a párrafo. Dame ejemplos de frases que generen ese 'necesito saber qué sigue'. Para que mi texto enganche de principio a fin.",
     en:"Act as a retention-copy expert. For a text about [TOPIC/PRODUCT], give me techniques and examples of how to create curiosity so the reader keeps reading to the end. How to open loops, make promises, hint without revealing, and keep interest paragraph by paragraph. Give me examples of phrases that generate that 'I need to know what's next'. So my copy hooks from start to finish."}},

{ cat:"copywriting", t:{es:"Texto para presentar una oferta limitada", en:"Copy to present a limited offer"},
  p:{es:"Eres copywriter experto en urgencia. Escribe un texto para promocionar una oferta limitada de [PRODUCTO] (por tiempo o cantidad). Que genere urgencia real y honesta, comunique claramente el beneficio y la condición de la oferta, y motive a actuar ya para no perderla. Que el lector sienta que esperar significa perder la oportunidad. Persuasivo sin caer en falsedades. Con llamada a la acción potente.",
     en:"You're an urgency-copy expert. Write copy to promote a limited offer of [PRODUCT] (by time or quantity). It should create real, honest urgency, clearly communicate the benefit and the offer condition, and motivate acting now to not miss it. The reader should feel that waiting means losing the opportunity. Persuasive without falsehoods. With a powerful call to action."}},

// ---------- NEGOCIOS (+10) ----------
{ cat:"business", t:{es:"Valida tu idea antes de invertir", en:"Validate your idea before investing"},
  p:{es:"Actúa como consultor de emprendimiento. Antes de invertir tiempo y dinero en [IDEA DE NEGOCIO], quiero validar si la gente realmente lo quiere. Dame un plan para validarla de forma rápida y barata: cómo probar el interés real, qué preguntar a posibles clientes, cómo conseguir las primeras señales de demanda, y cómo interpretar los resultados para decidir si seguir o ajustar. Práctico y de bajo riesgo.",
     en:"Act as an entrepreneurship consultant. Before investing time and money in [BUSINESS IDEA], I want to validate if people really want it. Give me a plan to validate it quickly and cheaply: how to test real interest, what to ask potential customers, how to get the first signs of demand, and how to interpret the results to decide whether to continue or adjust. Practical and low-risk."}},

{ cat:"business", t:{es:"Mejora la rentabilidad de tu negocio", en:"Improve your business profitability"},
  p:{es:"Eres consultor financiero de negocios. Mi negocio [NEGOCIO] vende pero siento que gano poco. Ayúdame a mejorar la rentabilidad: cómo identificar qué productos o servicios dejan más ganancia, dónde estoy perdiendo dinero, cómo subir precios o reducir costos sin perder clientes, y cómo enfocarme en lo más rentable. Dame un análisis práctico y acciones concretas para ganar más con lo que ya tengo.",
     en:"You're a business finance consultant. My business [BUSINESS] sells but I feel I earn little. Help me improve profitability: how to identify which products or services bring the most profit, where I'm losing money, how to raise prices or cut costs without losing customers, and how to focus on the most profitable. Give me a practical analysis and concrete actions to earn more with what I already have."}},

{ cat:"business", t:{es:"Crea un plan de crecimiento", en:"Create a growth plan"},
  p:{es:"Actúa como consultor de crecimiento. Mi negocio [NEGOCIO] está estable y quiero hacerlo crecer. Dame un plan de crecimiento realista: las distintas formas de crecer (más clientes, más productos, más mercados, vender más a los actuales), cuál tiene más sentido para mí, los pasos concretos para cada una, y por dónde empezar. Que me ayude a pasar al siguiente nivel sin arriesgar lo que ya tengo.",
     en:"Act as a growth consultant. My business [BUSINESS] is stable and I want to grow it. Give me a realistic growth plan: the different ways to grow (more customers, more products, more markets, selling more to current ones), which makes most sense for me, the concrete steps for each, and where to start. It should help me reach the next level without risking what I already have."}},

{ cat:"business", t:{es:"Analiza tus números clave", en:"Analyze your key numbers"},
  p:{es:"Eres consultor de negocios. Ayúdame a entender qué números debo vigilar en mi negocio [NEGOCIO] para saber si va bien y tomar buenas decisiones. Explícame de forma simple: qué indicadores importan (ventas, ganancia, costo por cliente, etc.), cómo calcularlos, qué me dice cada uno, y cómo usarlos para mejorar. Sin contabilidad complicada, práctico para alguien que maneja su propio negocio.",
     en:"You're a business consultant. Help me understand what numbers I should watch in my business [BUSINESS] to know if it's doing well and make good decisions. Explain simply: what indicators matter (sales, profit, cost per customer, etc.), how to calculate them, what each tells me, and how to use them to improve. Without complicated accounting, practical for someone running their own business."}},

{ cat:"business", t:{es:"Planea la apertura de tu negocio", en:"Plan your business opening"},
  p:{es:"Actúa como consultor de emprendimiento. Voy a abrir [TIPO DE NEGOCIO] y quiero hacerlo bien desde el inicio. Dame una guía de lo que debo preparar antes de abrir: lo esencial para empezar, qué necesito tener listo, los errores comunes de los que empiezan, cómo conseguir mis primeros clientes desde el día uno, y un plan de los primeros pasos. Realista y ordenado para arrancar con buen pie.",
     en:"Act as an entrepreneurship consultant. I'm going to open [TYPE OF BUSINESS] and want to do it right from the start. Give me a guide of what to prepare before opening: the essentials to start, what I need ready, the common mistakes of beginners, how to get my first customers from day one, and a plan of the first steps. Realistic and organized to start on the right foot."}},

{ cat:"business", t:{es:"Diversifica tus ingresos", en:"Diversify your income"},
  p:{es:"Eres consultor de negocios. Actualmente mi negocio [NEGOCIO] depende de una sola fuente de ingresos y quiero diversificar para tener más estabilidad. Dame ideas concretas de cómo crear nuevas fuentes de ingreso relacionadas con lo que ya hago: productos o servicios adicionales, ingresos pasivos, nuevos mercados. Para cada idea, por qué funcionaría y qué tan fácil es empezar. Que reduzca mi riesgo y aumente mis ingresos.",
     en:"You're a business consultant. Currently my business [BUSINESS] depends on a single income source and I want to diversify for more stability. Give me concrete ideas on how to create new income streams related to what I already do: additional products or services, passive income, new markets. For each idea, why it would work and how easy it is to start. It should reduce my risk and increase my income."}},

{ cat:"business", t:{es:"Negocia mejor con proveedores o clientes", en:"Negotiate better with suppliers or clients"},
  p:{es:"Actúa como experto en negociación. Tengo que negociar [SITUACIÓN: precio con un proveedor, condiciones con un cliente, etc.]. Dame estrategias y tácticas para negociar mejor: cómo prepararme, cómo plantear mi posición, cómo manejar las objeciones, cuándo ceder y cuándo mantenerme firme, y cómo lograr un acuerdo que me beneficie sin dañar la relación. Práctico, con frases y un enfoque claro. Que consiga mejores condiciones.",
     en:"Act as a negotiation expert. I have to negotiate [SITUATION: price with a supplier, terms with a client, etc.]. Give me strategies and tactics to negotiate better: how to prepare, how to present my position, how to handle objections, when to give in and when to stand firm, and how to reach an agreement that benefits me without harming the relationship. Practical, with phrases and a clear approach. To get better terms."}},

{ cat:"business", t:{es:"Organiza las finanzas de tu negocio", en:"Organize your business finances"},
  p:{es:"Eres asesor financiero. Mis finanzas del negocio [NEGOCIO] están desordenadas y mezclo lo personal con lo del negocio. Ayúdame a organizarlas de forma simple: cómo separar el dinero personal del negocio, cómo llevar un control básico de ingresos y gastos, cómo saber cuánto gano realmente, y qué hábitos financieros adoptar. Sin contabilidad complicada, práctico para ordenar el dinero de mi negocio y tomar mejores decisiones.",
     en:"You're a financial advisor. My business finances [BUSINESS] are disorganized and I mix personal with business money. Help me organize them simply: how to separate personal from business money, how to keep basic control of income and expenses, how to know how much I really earn, and what financial habits to adopt. Without complicated accounting, practical to organize my business money and make better decisions."}},

{ cat:"business", t:{es:"Resuelve un problema con un cliente", en:"Resolve a problem with a client"},
  p:{es:"Actúa como experto en servicio al cliente. Tengo un problema o conflicto con un cliente: [DESCRIBE LA SITUACIÓN]. Ayúdame a resolverlo de la mejor manera: cómo responder con profesionalismo y empatía, cómo buscar una solución que deje satisfecho al cliente sin perjudicarme demasiado, y cómo convertir esta situación en una oportunidad de fortalecer la relación. Dame un enfoque y mensajes para manejarlo bien.",
     en:"Act as a customer service expert. I have a problem or conflict with a client: [DESCRIBE THE SITUATION]. Help me resolve it in the best way: how to respond professionally and empathetically, how to find a solution that satisfies the client without hurting me too much, and how to turn this situation into an opportunity to strengthen the relationship. Give me an approach and messages to handle it well."}},

{ cat:"business", t:{es:"Define la misión y visión de tu negocio", en:"Define your business mission and vision"},
  p:{es:"Eres consultor de estrategia. Ayúdame a definir la misión y visión de mi negocio [NEGOCIO]. La misión: para qué existe mi negocio, a quién sirve y cómo. La visión: a dónde quiero llegar en el futuro. Que sean claras, inspiradoras y auténticas, que guíen mis decisiones y conecten con mis clientes y conmigo mismo. Dame varias versiones para elegir. Que reflejen el propósito real de mi negocio.",
     en:"You're a strategy consultant. Help me define the mission and vision of my business [BUSINESS]. The mission: why my business exists, who it serves and how. The vision: where I want to go in the future. They should be clear, inspiring and authentic, guiding my decisions and connecting with my customers and myself. Give me several versions to choose from. They should reflect the real purpose of my business."}},

// ---------- DISEÑO (+5) ----------
{ cat:"design", t:{es:"Infografía para explicar un tema", en:"Infographic to explain a topic"},
  p:{es:"Actúa como diseñador de infografías. Ayúdame a diseñar el contenido y la estructura de una infografía sobre [TEMA] para [PÚBLICO]. Dame: qué información incluir y cómo organizarla visualmente, el título atractivo, cómo dividir los datos en secciones claras, qué elementos visuales usar y la paleta de colores. Que comunique la información de forma clara, atractiva y fácil de entender de un vistazo.",
     en:"Act as an infographic designer. Help me design the content and structure of an infographic about [TOPIC] for [AUDIENCE]. Give me: what information to include and how to organize it visually, the attractive title, how to divide the data into clear sections, what visual elements to use and the color palette. It should communicate the information clearly, attractively and easy to understand at a glance."}},

{ cat:"design", t:{es:"Portada para ebook o guía", en:"Cover for an ebook or guide"},
  p:{es:"Crea un prompt en inglés para generar con IA la portada de un ebook o guía titulado [TÍTULO] sobre [TEMA]. Describe: el estilo visual acorde al tema, los elementos gráficos, la paleta de colores, el espacio para el título, y la sensación que debe transmitir (profesional, atractiva, confiable). Que se vea como una portada de calidad que invite a descargar o comprar. Con parámetros recomendados.",
     en:"Create an English prompt to generate the cover of an ebook or guide titled [TITLE] about [TOPIC] with AI. Describe: the visual style fitting the topic, the graphic elements, the color palette, the space for the title, and the feeling it should convey (professional, attractive, trustworthy). It should look like a quality cover that invites downloading or buying. With recommended parameters."}},

{ cat:"design", t:{es:"Diseño de flyer o volante", en:"Flyer design"},
  p:{es:"Actúa como diseñador gráfico. Ayúdame a diseñar un flyer o volante para promocionar [NEGOCIO/PRODUCTO/EVENTO]. Indica: qué información incluir y cómo jerarquizarla, el título o gancho principal, la distribución de los elementos, la paleta de colores, el estilo, y la llamada a la acción. Que sea atractivo, comunique claro y motive a contactar o comprar. Con una descripción detallada para crearlo o mandarlo a diseñar.",
     en:"Act as a graphic designer. Help me design a flyer to promote [BUSINESS/PRODUCT/EVENT]. Indicate: what information to include and how to prioritize it, the main title or hook, the element layout, the color palette, the style, and the call to action. It should be attractive, communicate clearly and motivate contact or purchase. With a detailed description to create it or send for design."}},

{ cat:"design", t:{es:"Conceptos visuales con IA para tu marca", en:"Visual concepts with AI for your brand"},
  p:{es:"Crea 3 prompts distintos en inglés para generar con IA imágenes que representen la identidad visual de [MARCA/NEGOCIO] del sector [SECTOR]. Cada prompt para un estilo o enfoque diferente, describiendo los colores de mi marca, el ambiente, los elementos y la sensación a transmitir. Que me den opciones visuales para mi marca y pueda elegir la dirección que más me guste. Con parámetros recomendados.",
     en:"Create 3 different English prompts to generate images with AI that represent the visual identity of [BRAND/BUSINESS] in the [SECTOR] sector. Each prompt for a different style or approach, describing my brand colors, the ambiance, the elements and the feeling to convey. They should give me visual options for my brand so I can choose the direction I like most. With recommended parameters."}},

{ cat:"design", t:{es:"Mejora la presentación visual de tu oferta", en:"Improve the visual presentation of your offer"},
  p:{es:"Actúa como diseñador experto en conversión. Ayúdame a presentar visualmente mi oferta de [PRODUCTO] de forma más atractiva y profesional. Dame recomendaciones de: cómo organizar la información visualmente, qué destacar, qué colores y elementos usan las ofertas que convierten, cómo mostrar el precio y los beneficios, y cómo lograr que se vea valiosa y confiable. Práctico para mejorar cómo se ve mi oferta.",
     en:"Act as a conversion-focused designer. Help me visually present my offer for [PRODUCT] in a more attractive and professional way. Give me recommendations on: how to organize the information visually, what to highlight, what colors and elements converting offers use, how to show the price and benefits, and how to make it look valuable and trustworthy. Practical to improve how my offer looks."}},

// ---------- PRODUCTIVIDAD (+5) ----------
{ cat:"productivity", t:{es:"Sistema para no olvidar tareas", en:"System to not forget tasks"},
  p:{es:"Actúa como experto en productividad. Se me olvidan cosas y tareas importantes y vivo apagando incendios. Ayúdame a crear un sistema simple para capturar y no olvidar nada: cómo anotar todo en un solo lugar, cómo organizar las tareas por prioridad, cómo revisar para no dejar pasar nada, y qué hábito seguir cada día. Que sea fácil de mantener y me dé tranquilidad de tener todo bajo control.",
     en:"Act as a productivity expert. I forget important things and tasks and I'm always putting out fires. Help me create a simple system to capture and not forget anything: how to write everything in one place, how to organize tasks by priority, how to review so nothing slips through, and what habit to follow each day. It should be easy to maintain and give me peace of mind of having everything under control."}},

{ cat:"productivity", t:{es:"Delega tareas eficazmente", en:"Delegate tasks effectively"},
  p:{es:"Eres experto en gestión. Quiero empezar a delegar tareas de [TRABAJO/NEGOCIO] porque no puedo con todo, pero me cuesta soltar. Ayúdame: cómo decidir qué tareas delegar primero, cómo explicar bien lo que necesito para que lo hagan bien, cómo supervisar sin controlar de más, y cómo confiar en que otros lo hagan. Práctico, para liberar mi tiempo y enfocarme en lo importante sin que todo dependa de mí.",
     en:"You're a management expert. I want to start delegating tasks from [WORK/BUSINESS] because I can't do everything, but I struggle to let go. Help me: how to decide which tasks to delegate first, how to clearly explain what I need so they do it well, how to supervise without over-controlling, and how to trust others to do it. Practical, to free my time and focus on what's important without everything depending on me."}},

{ cat:"productivity", t:{es:"Trabaja mejor desde casa", en:"Work better from home"},
  p:{es:"Actúa como experto en trabajo remoto. Trabajo desde casa y me cuesta concentrarme y separar el trabajo de la vida personal. Dame estrategias para ser más productivo en casa: cómo organizar mi espacio, cómo crear una rutina, cómo evitar las distracciones del hogar, cómo poner límites de horario, y cómo mantener el enfoque. Práctico y realista para rendir mejor trabajando desde casa sin quemarme.",
     en:"Act as a remote work expert. I work from home and struggle to concentrate and separate work from personal life. Give me strategies to be more productive at home: how to organize my space, how to create a routine, how to avoid home distractions, how to set time limits, and how to stay focused. Practical and realistic to perform better working from home without burning out."}},

{ cat:"productivity", t:{es:"Evita el agotamiento (burnout)", en:"Avoid burnout"},
  p:{es:"Eres coach de bienestar y productividad. Siento que estoy al borde del agotamiento por exceso de trabajo. Ayúdame a manejarlo de forma sana: cómo identificar las señales de agotamiento, cómo organizar mi carga de forma más sostenible, cómo poner límites, cómo descansar de verdad, y cómo recuperar energía y motivación. Consejos prácticos y realistas para cuidar mi bienestar sin descuidar mis responsabilidades.",
     en:"You're a wellness and productivity coach. I feel I'm on the verge of burnout from overwork. Help me manage it healthily: how to identify the signs of burnout, how to organize my load more sustainably, how to set limits, how to truly rest, and how to recover energy and motivation. Practical, realistic advice to care for my wellbeing without neglecting my responsibilities."}},

{ cat:"productivity", t:{es:"Crea hábitos que se mantengan", en:"Build habits that stick"},
  p:{es:"Actúa como experto en hábitos. Quiero crear el hábito de [HÁBITO QUE QUIERES] pero siempre lo dejo a los pocos días. Ayúdame a lograr que se mantenga: cómo empezar pequeño, cómo encadenarlo a algo que ya hago, cómo no romper la cadena, cómo superar la falta de motivación, y cuánto tiempo toma que se vuelva automático. Práctico y basado en lo que de verdad funciona para crear hábitos duraderos.",
     en:"Act as a habits expert. I want to build the habit of [HABIT YOU WANT] but I always quit after a few days. Help me make it stick: how to start small, how to chain it to something I already do, how to not break the chain, how to overcome lack of motivation, and how long it takes to become automatic. Practical and based on what really works to build lasting habits."}},

];
