// ============================================================
//  ARSENAL IA — BIBLIOTECA DE PROMPTS (parte 11)
//  Cierre a 30: Diseño · Productividad · Marca personal · IA y Agentes
// ============================================================

const PROMPTS_11 = [

// ---------- DISEÑO (+5) ----------
{ cat:"design", t:{es:"Identidad visual completa de marca", en:"Complete brand visual identity"},
  p:{es:"Actúa como diseñador de identidad de marca. Ayúdame a definir la identidad visual completa de [MARCA/NEGOCIO] del sector [SECTOR] dirigida a [PÚBLICO]. Dame recomendaciones de: estilo del logo, paleta de colores con códigos, tipografías principales y secundarias, estilo de imágenes y gráficos, y la sensación general que debe transmitir. Que todo sea coherente y profesional. Una guía clara para construir mi marca visualmente.",
     en:"Act as a brand identity designer. Help me define the complete visual identity of [BRAND/BUSINESS] in the [SECTOR] sector aimed at [AUDIENCE]. Give me recommendations on: logo style, color palette with codes, primary and secondary typography, image and graphic style, and the overall feeling it should convey. Everything should be coherent and professional. A clear guide to build my brand visually."}},

{ cat:"design", t:{es:"Diseño de presentación o pitch deck", en:"Presentation or pitch deck design"},
  p:{es:"Actúa como diseñador de presentaciones. Ayúdame a diseñar una presentación profesional sobre [TEMA] para [PROPÓSITO: vender, exponer, convencer]. Dame: la estructura de diapositivas, qué incluir en cada una, cómo distribuir texto e imágenes, qué estilo visual y colores usar, y cómo mantenerla limpia y atractiva. Que se vea profesional, comunique claro y mantenga la atención. Práctica y orientada a lograr su objetivo.",
     en:"Act as a presentation designer. Help me design a professional presentation about [TOPIC] for [PURPOSE: sell, present, convince]. Give me: the slide structure, what to include in each, how to distribute text and images, what visual style and colors to use, and how to keep it clean and attractive. It should look professional, communicate clearly and keep attention. Practical and oriented to achieving its goal."}},

{ cat:"design", t:{es:"Imagen promocional con IA para tu oferta", en:"Promotional image with AI for your offer"},
  p:{es:"Crea un prompt en inglés para generar con IA una imagen promocional atractiva para anunciar [PRODUCTO/OFERTA]. Describe: el estilo visual, el ambiente, los colores acordes a mi marca, los elementos a incluir, el espacio para texto, y la sensación que debe transmitir (deseable, profesional, llamativa). Que sirva para promocionar mi oferta en redes y capte la atención. Con parámetros recomendados para alta calidad.",
     en:"Create an English prompt to generate an attractive promotional image with AI to announce [PRODUCT/OFFER]. Describe: the visual style, the ambiance, brand-appropriate colors, the elements to include, space for text, and the feeling it should convey (desirable, professional, eye-catching). It should serve to promote my offer on social media and grab attention. With recommended parameters for high quality."}},

{ cat:"design", t:{es:"Plantilla visual reutilizable", en:"Reusable visual template"},
  p:{es:"Actúa como diseñador gráfico. Ayúdame a definir una plantilla visual reutilizable para mis publicaciones de [NICHO/NEGOCIO] en redes, para no diseñar desde cero cada vez. Dame: la estructura base, dónde va el logo y el texto, los colores y tipografías fijos, el estilo de los elementos, y cómo variarla manteniendo la coherencia. Que me ahorre tiempo y haga que mi contenido se vea profesional y consistente. Práctica y aplicable.",
     en:"Act as a graphic designer. Help me define a reusable visual template for my [NICHE/BUSINESS] social media posts, so I don't design from scratch every time. Give me: the base structure, where the logo and text go, the fixed colors and typography, the element style, and how to vary it keeping coherence. It should save me time and make my content look professional and consistent. Practical and applicable."}},

{ cat:"design", t:{es:"Mejora visual de tu perfil o página", en:"Visual improvement of your profile or page"},
  p:{es:"Actúa como consultor de diseño. Mi perfil o página de [RED SOCIAL/SITIO] se ve [DESCRIBE: simple, desordenado, poco profesional]. Dame recomendaciones concretas para mejorar su aspecto visual: qué cambiar, cómo organizar los elementos, qué colores y estilo usar, cómo destacar lo importante, y cómo lograr que se vea más profesional y atractivo. Práctico y aplicable sin necesidad de ser diseñador experto. Que cause mejor impresión.",
     en:"Act as a design consultant. My [SOCIAL NETWORK/SITE] profile or page looks [DESCRIBE: simple, messy, unprofessional]. Give me concrete recommendations to improve its visual appearance: what to change, how to organize the elements, what colors and style to use, how to highlight what's important, and how to make it look more professional and attractive. Practical and applicable without needing to be an expert designer. To make a better impression."}},

// ---------- PRODUCTIVIDAD (+5) ----------
{ cat:"productivity", t:{es:"Organiza tu negocio para tener más tiempo", en:"Organize your business for more time"},
  p:{es:"Actúa como consultor de productividad. Mi negocio [NEGOCIO] me consume todo el tiempo y siento que trabajo demasiado. Ayúdame a organizarlo para liberar tiempo: cómo identificar qué tareas me quitan más tiempo, qué puedo simplificar, automatizar o delegar, cómo crear sistemas para que no todo dependa de mí, y cómo recuperar horas para lo importante. Práctico y aplicable para trabajar menos y mejor. Que me dé más libertad.",
     en:"Act as a productivity consultant. My business [BUSINESS] consumes all my time and I feel I work too much. Help me organize it to free up time: how to identify which tasks take the most time, what I can simplify, automate or delegate, how to create systems so not everything depends on me, and how to recover hours for what matters. Practical and applicable to work less and better. To give me more freedom."}},

{ cat:"productivity", t:{es:"Planifica tus metas del mes", en:"Plan your monthly goals"},
  p:{es:"Actúa como coach de productividad. Ayúdame a planificar mis metas para este mes. Quiero lograr: [DESCRIBE LO QUE QUIERES LOGRAR]. Ayúdame a convertirlo en metas claras y alcanzables, dividirlas en acciones semanales, priorizar lo más importante, y crear un sistema simple para hacerles seguimiento. Realista, que no me sature, y que me ayude a avanzar de verdad hacia lo que quiero este mes. Claro y aplicable.",
     en:"Act as a productivity coach. Help me plan my goals for this month. I want to achieve: [DESCRIBE WHAT YOU WANT TO ACHIEVE]. Help me turn it into clear, achievable goals, break them into weekly actions, prioritize what's most important, and create a simple system to track them. Realistic, not overwhelming, and that helps me really progress toward what I want this month. Clear and applicable."}},

{ cat:"productivity", t:{es:"Toma notas y organiza ideas", en:"Take notes and organize ideas"},
  p:{es:"Actúa como experto en organización personal. Tengo muchas ideas y notas dispersas y se me pierden. Ayúdame a crear un sistema simple para capturar y organizar mis ideas y notas: dónde guardarlas, cómo clasificarlas para encontrarlas fácil, cómo convertir las ideas en acciones, y cómo revisarlas. Que sea fácil de mantener y me ayude a no perder ideas valiosas ni información importante. Práctico y sostenible.",
     en:"Act as a personal organization expert. I have many scattered ideas and notes and I lose them. Help me create a simple system to capture and organize my ideas and notes: where to store them, how to classify them to find them easily, how to turn ideas into actions, and how to review them. It should be easy to maintain and help me not lose valuable ideas or important information. Practical and sustainable."}},

{ cat:"productivity", t:{es:"Empieza el día con claridad", en:"Start the day with clarity"},
  p:{es:"Actúa como coach de productividad. Quiero empezar cada día con claridad sobre qué hacer en vez de sentirme abrumado o disperso. Dame un método simple para planear mi día cada mañana: cómo elegir mis prioridades, cuántas tareas clave enfocarme, cómo organizar mi tiempo, y cómo terminar el día sintiendo que avancé. Práctico y rápido de hacer, que me dé enfoque y dirección desde temprano. Aplicable a mi día a día.",
     en:"Act as a productivity coach. I want to start each day with clarity about what to do instead of feeling overwhelmed or scattered. Give me a simple method to plan my day each morning: how to choose my priorities, how many key tasks to focus on, how to organize my time, and how to end the day feeling I made progress. Practical and quick to do, giving me focus and direction from early on. Applicable to my daily life."}},

{ cat:"productivity", t:{es:"Recupera el control cuando todo es caos", en:"Regain control when everything is chaos"},
  p:{es:"Actúa como coach de productividad. Siento que tengo demasiadas cosas pendientes y todo es un caos, no sé por dónde empezar. Ayúdame a recuperar el control: cómo sacar todo lo que tengo en la cabeza, cómo organizarlo, cómo decidir qué es urgente e importante, qué hacer primero, y cómo volver a sentir que tengo las cosas bajo control. Práctico y tranquilizador, para pasar del caos a la claridad paso a paso. Que me dé calma y dirección.",
     en:"Act as a productivity coach. I feel I have too many pending things and everything is chaos, I don't know where to start. Help me regain control: how to get everything out of my head, how to organize it, how to decide what's urgent and important, what to do first, and how to feel I have things under control again. Practical and reassuring, to go from chaos to clarity step by step. To give me calm and direction."}},

// ---------- MARCA PERSONAL (+5) ----------
{ cat:"personal", t:{es:"Crea tu marca personal desde cero", en:"Build your personal brand from scratch"},
  p:{es:"Actúa como estratega de marca personal. Quiero empezar a construir mi marca personal en [ÁREA/TEMA] pero no sé por dónde empezar. Dame una guía paso a paso: cómo definir por qué quiero ser conocido, cómo encontrar mi enfoque y voz, en qué plataforma empezar, qué tipo de contenido crear, y los primeros pasos concretos. Práctica y motivadora, que me dé un camino claro para arrancar mi marca personal sin abrumarme.",
     en:"Act as a personal brand strategist. I want to start building my personal brand in [AREA/TOPIC] but don't know where to start. Give me a step-by-step guide: how to define what I want to be known for, how to find my focus and voice, what platform to start on, what type of content to create, and the first concrete steps. Practical and motivating, giving me a clear path to start my personal brand without overwhelming me."}},

{ cat:"personal", t:{es:"Conecta con tu audiencia a nivel humano", en:"Connect with your audience on a human level"},
  p:{es:"Actúa como experto en marca personal. Quiero que mi audiencia de [NICHO/ÁREA] sienta una conexión real conmigo, no solo que me vean como alguien que vende. Dame estrategias e ideas de contenido para conectar a nivel humano: qué compartir de mí, cómo mostrar mi lado auténtico, cómo generar cercanía y confianza, y cómo equilibrar lo personal con lo profesional. Que la gente sienta que me conoce y confíe en mí. Práctico y genuino.",
     en:"Act as a personal branding expert. I want my [NICHE/AREA] audience to feel a real connection with me, not just see me as someone who sells. Give me strategies and content ideas to connect on a human level: what to share about myself, how to show my authentic side, how to create warmth and trust, and how to balance the personal with the professional. People should feel they know me and trust me. Practical and genuine."}},

{ cat:"personal", t:{es:"Cuenta tu propósito o tu 'por qué'", en:"Tell your purpose or your 'why'"},
  p:{es:"Actúa como experto en storytelling personal. Ayúdame a comunicar mi propósito o mi 'por qué' detrás de lo que hago en [ÁREA/ACTIVIDAD]. Mi motivación es: [DESCRIBE POR QUÉ HACES LO QUE HACES]. Conviértelo en un mensaje auténtico y conmovedor que conecte con mi audiencia, transmita mi pasión, y haga que la gente se identifique y quiera seguirme o apoyarme. Que inspire y genere conexión. Genuino y memorable.",
     en:"Act as a personal storytelling expert. Help me communicate my purpose or my 'why' behind what I do in [AREA/ACTIVITY]. My motivation is: [DESCRIBE WHY YOU DO WHAT YOU DO]. Turn it into an authentic, moving message that connects with my audience, conveys my passion, and makes people identify and want to follow or support me. It should inspire and create connection. Genuine and memorable."}},

{ cat:"personal", t:{es:"Plan de contenido personal para un mes", en:"Personal content plan for a month"},
  p:{es:"Actúa como estratega de marca personal. Crea un plan de contenido de un mes para construir mi marca personal en [RED SOCIAL] sobre [TEMA/ÁREA]. Dame ideas de publicaciones variadas que combinen: mostrar mi experiencia, aportar valor, conectar a nivel humano, contar mi historia, y opcionalmente promocionar lo que ofrezco. Organízalas para mantener un buen equilibrio. Realista y sostenible, que me dé contenido listo para un mes.",
     en:"Act as a personal brand strategist. Create a one-month content plan to build my personal brand on [SOCIAL NETWORK] about [TOPIC/AREA]. Give me varied post ideas that combine: showing my experience, providing value, connecting on a human level, telling my story, and optionally promoting what I offer. Organize them to maintain a good balance. Realistic and sustainable, giving me ready content for a month."}},

{ cat:"personal", t:{es:"Comunica tu experiencia sin presumir", en:"Communicate your experience without bragging"},
  p:{es:"Actúa como experto en marca personal. Tengo experiencia y conocimiento en [ÁREA] y quiero comunicarlo para posicionarme, pero sin sonar arrogante o presumido. Dame estrategias e ideas: cómo demostrar mi experiencia a través de aportar valor, cómo compartir logros con humildad, cómo enseñar lo que sé de forma generosa, y cómo posicionarme como experto sin caer en la soberbia. Que genere respeto y confianza, no rechazo. Auténtico y equilibrado.",
     en:"Act as a personal branding expert. I have experience and knowledge in [AREA] and want to communicate it to position myself, but without sounding arrogant or boastful. Give me strategies and ideas: how to demonstrate my experience through providing value, how to share achievements with humility, how to teach what I know generously, and how to position myself as an expert without falling into arrogance. It should generate respect and trust, not rejection. Authentic and balanced."}},

// ---------- IA Y AGENTES (+5) ----------
{ cat:"agents", t:{es:"Diseña tu propio asistente de IA", en:"Design your own AI assistant"},
  p:{es:"Actúa como experto en configuración de IA. Ayúdame a diseñar un asistente de IA personalizado para [PROPÓSITO/TAREA]. Dame las instrucciones completas que debo darle: qué rol y personalidad debe tener, qué debe saber, cómo debe responder, qué pasos seguir, qué formato usar, y qué no debe hacer. Que quede como un asistente especializado y útil para lo que necesito. Listo para copiar y configurar. Completo y bien estructurado.",
     en:"Act as an AI configuration expert. Help me design a custom AI assistant for [PURPOSE/TASK]. Give me the complete instructions I should give it: what role and personality it should have, what it should know, how it should respond, what steps to follow, what format to use, and what it shouldn't do. So it becomes a specialized, useful assistant for what I need. Ready to copy and configure. Complete and well structured."}},

{ cat:"agents", t:{es:"Usa la IA para tu negocio día a día", en:"Use AI for your business day to day"},
  p:{es:"Actúa como consultor de IA para negocios. Tengo un negocio de [NEGOCIO] y quiero aprovechar la IA en mi día a día para ahorrar tiempo y mejorar. Dame ideas concretas y prácticas de cómo usar la IA en distintas áreas (marketing, atención, contenido, organización, ventas), con ejemplos de para qué usarla en cada una y cómo empezar. Enfócate en usos simples y útiles que pueda aplicar ya sin ser experto en tecnología.",
     en:"Act as an AI-for-business consultant. I have a [BUSINESS] business and want to leverage AI in my day to day to save time and improve. Give me concrete, practical ideas on how to use AI in different areas (marketing, support, content, organization, sales), with examples of what to use it for in each and how to start. Focus on simple, useful uses I can apply now without being a tech expert."}},

{ cat:"agents", t:{es:"Resuelve dudas y aprende con la IA", en:"Resolve doubts and learn with AI"},
  p:{es:"Actúa como experto y tutor en cualquier tema. Quiero usar la IA para resolver mis dudas y aprender sobre [TEMA] de forma efectiva. Enséñame cómo aprovecharla al máximo: cómo preguntarle para obtener explicaciones claras, cómo pedirle que profundice o simplifique, cómo usarla para resolver dudas específicas, y cómo aprender de forma estructurada con su ayuda. Dame ejemplos de buenas preguntas para aprender sobre este tema. Práctico y aplicable.",
     en:"Act as an expert and tutor in any topic. I want to use AI to resolve my doubts and learn about [TOPIC] effectively. Teach me how to make the most of it: how to ask it for clear explanations, how to ask it to go deeper or simplify, how to use it to resolve specific doubts, and how to learn in a structured way with its help. Give me examples of good questions to learn about this topic. Practical and applicable."}},

{ cat:"agents", t:{es:"Crea contenido más rápido con IA", en:"Create content faster with AI"},
  p:{es:"Actúa como experto en IA para creadores de contenido. Quiero usar la IA para crear contenido más rápido para [NICHO/NEGOCIO] sin que pierda calidad ni suene robótico. Dame un sistema práctico: cómo generar ideas, cómo crear borradores y mejorarlos, cómo darle mi estilo personal, qué prompts usar para distintos formatos (publicaciones, guiones, textos), y cómo revisarlo para que quede bien. Que me ayude a producir más en menos tiempo manteniendo mi voz.",
     en:"Act as an AI-for-content-creators expert. I want to use AI to create content faster for [NICHE/BUSINESS] without losing quality or sounding robotic. Give me a practical system: how to generate ideas, how to create drafts and improve them, how to give it my personal style, what prompts to use for different formats (posts, scripts, copy), and how to review it so it turns out well. To help me produce more in less time keeping my voice."}},

{ cat:"agents", t:{es:"Saca más provecho a la IA en tu trabajo", en:"Get more out of AI in your work"},
  p:{es:"Actúa como experto en productividad con IA. Trabajo en [ÁREA/PROFESIÓN] y quiero usar la IA para ser más eficiente y mejorar mis resultados. Dame ideas concretas de cómo aplicarla a mis tareas: en qué me puede ayudar específicamente, con ejemplos de para qué usarla, qué prompts probar, y cómo integrarla en mi rutina de trabajo. Enfócate en usos prácticos y reales que me ahorren tiempo y me ayuden a trabajar mejor. Aplicable a lo que hago.",
     en:"Act as an AI productivity expert. I work in [AREA/PROFESSION] and want to use AI to be more efficient and improve my results. Give me concrete ideas on how to apply it to my tasks: what it can specifically help me with, with examples of what to use it for, what prompts to try, and how to integrate it into my work routine. Focus on practical, real uses that save me time and help me work better. Applicable to what I do."}},

];
