// ============================================================
//  ARSENAL IA — BIBLIOTECA DE PROMPTS (parte 10)
//  Subir a 30: E-commerce · Email · SEO · Video
//  Marca personal · Agentes · Educación · Salud
// ============================================================

const PROMPTS_10 = [

// ---------- E-COMMERCE (+10) ----------
{ cat:"ecommerce", t:{es:"Catálogo de productos atractivo", en:"Attractive product catalog"},
  p:{es:"Actúa como experto en e-commerce. Ayúdame a organizar y presentar el catálogo de mi tienda de [PRODUCTOS] de forma atractiva. Dame: cómo agrupar y ordenar los productos, cómo escribir descripciones que vendan, qué información mostrar de cada uno, y cómo destacar los más rentables o populares. Que facilite la compra y haga que el cliente encuentre y desee los productos. Práctico y aplicable.",
     en:"Act as an e-commerce expert. Help me organize and present my [PRODUCTS] store catalog attractively. Give me: how to group and order the products, how to write descriptions that sell, what information to show for each, and how to highlight the most profitable or popular ones. It should make buying easier and make the customer find and desire the products. Practical and applicable."}},

{ cat:"ecommerce", t:{es:"Estrategia de envío gratis", en:"Free shipping strategy"},
  p:{es:"Eres consultor de e-commerce. Quiero usar el envío gratis para vender más en mi tienda de [PRODUCTOS] sin perder dinero. Ayúdame: cómo ofrecer envío gratis de forma rentable (a partir de cierto monto, en ciertos productos, etc.), cómo usarlo para aumentar el valor de cada compra, cómo comunicarlo, y cómo calcular para que me siga conviniendo. Que aumente las ventas sin afectar mi ganancia.",
     en:"You're an e-commerce consultant. I want to use free shipping to sell more in my [PRODUCTS] store without losing money. Help me: how to offer free shipping profitably (above a certain amount, on certain products, etc.), how to use it to increase the value of each purchase, how to communicate it, and how to calculate so it still benefits me. It should increase sales without affecting my profit."}},

{ cat:"ecommerce", t:{es:"Página de inicio de tu tienda online", en:"Homepage of your online store"},
  p:{es:"Actúa como experto en tiendas online. Ayúdame a definir qué debe tener la página de inicio de mi tienda de [PRODUCTOS] para vender más. Dame: qué mostrar primero, cómo captar la atención, qué productos o ofertas destacar, cómo generar confianza, y cómo guiar al visitante hacia la compra. Que cause buena primera impresión y convierta visitantes en compradores. Práctico y orientado a ventas.",
     en:"Act as an online store expert. Help me define what my [PRODUCTS] store homepage should have to sell more. Give me: what to show first, how to grab attention, what products or offers to highlight, how to build trust, and how to guide the visitor toward purchase. It should make a good first impression and convert visitors into buyers. Practical and sales-oriented."}},

{ cat:"ecommerce", t:{es:"Vende por catálogo de WhatsApp", en:"Sell via WhatsApp catalog"},
  p:{es:"Eres experto en ventas por WhatsApp. Quiero vender mis productos de [PRODUCTOS] usando WhatsApp Business y su catálogo. Ayúdame: cómo organizar mi catálogo para que sea fácil de comprar, cómo presentar los productos, cómo responder a los interesados y guiarlos a la compra, y cómo cerrar ventas por chat. Que convierta las conversaciones de WhatsApp en ventas reales. Práctico y aplicable.",
     en:"You're a WhatsApp sales expert. I want to sell my [PRODUCTS] using WhatsApp Business and its catalog. Help me: how to organize my catalog so it's easy to buy from, how to present the products, how to respond to interested people and guide them to purchase, and how to close sales via chat. It should turn WhatsApp conversations into real sales. Practical and applicable."}},

{ cat:"ecommerce", t:{es:"Promoción para liquidar inventario", en:"Promotion to clear inventory"},
  p:{es:"Actúa como experto en e-commerce. Tengo productos de [PRODUCTOS] que necesito vender rápido para liquidar inventario. Dame una estrategia de promoción: qué tipo de oferta usar, cómo crear urgencia, cómo comunicarla para que la gente compre ya, y cómo combinar productos para venderlos más rápido. Que me ayude a mover el inventario estancado recuperando la mayor cantidad de dinero posible. Práctica y efectiva.",
     en:"Act as an e-commerce expert. I have [PRODUCTS] I need to sell fast to clear inventory. Give me a promotion strategy: what type of offer to use, how to create urgency, how to communicate it so people buy now, and how to combine products to sell them faster. It should help me move stuck inventory recovering as much money as possible. Practical and effective."}},

{ cat:"ecommerce", t:{es:"Fideliza a los compradores de tu tienda", en:"Build loyalty with your store buyers"},
  p:{es:"Eres experto en retención de clientes. Quiero que los clientes de mi tienda de [PRODUCTOS] vuelvan a comprar. Dame estrategias: cómo darles una buena experiencia que los haga volver, qué hacer después de la primera compra, cómo crear incentivos para que recompren, cómo mantenerme presente sin saturar, y cómo convertir compradores ocasionales en clientes frecuentes. Práctico para aumentar las compras repetidas.",
     en:"You're a customer retention expert. I want customers of my [PRODUCTS] store to buy again. Give me strategies: how to give them a good experience that makes them return, what to do after the first purchase, how to create incentives to rebuy, how to stay present without saturating, and how to turn occasional buyers into frequent customers. Practical to increase repeat purchases."}},

{ cat:"ecommerce", t:{es:"Maneja las opiniones negativas", en:"Handle negative reviews"},
  p:{es:"Actúa como experto en reputación de tiendas online. Recibí una opinión o reseña negativa sobre [PRODUCTO/EXPERIENCIA] en mi tienda. Ayúdame a manejarla bien: cómo responder de forma profesional y que juegue a mi favor, cómo resolver el problema del cliente, cómo convertir una mala experiencia en una oportunidad, y cómo evitar que dañe mi reputación. Dame un enfoque y una respuesta de ejemplo. Que muestre buen servicio.",
     en:"Act as an online store reputation expert. I received a negative review about [PRODUCT/EXPERIENCE] in my store. Help me handle it well: how to respond professionally and in my favor, how to resolve the customer's problem, how to turn a bad experience into an opportunity, and how to prevent it from damaging my reputation. Give me an approach and an example response. It should show good service."}},

{ cat:"ecommerce", t:{es:"Crea urgencia en tu tienda online", en:"Create urgency in your online store"},
  p:{es:"Eres experto en conversión. Quiero crear urgencia honesta en mi tienda de [PRODUCTOS] para que la gente compre y no lo deje para después. Dame técnicas que pueda aplicar: ofertas con fecha límite, stock limitado real, bonos por comprar pronto, y cómo comunicarlas de forma que motiven la compra inmediata sin engañar. Que reduzcan la indecisión y aumenten las ventas. Prácticas y éticas.",
     en:"You're a conversion expert. I want to create honest urgency in my [PRODUCTS] store so people buy and don't leave it for later. Give me techniques I can apply: offers with a deadline, real limited stock, bonuses for buying soon, and how to communicate them in a way that motivates immediate purchase without deceiving. They should reduce indecision and increase sales. Practical and ethical."}},

{ cat:"ecommerce", t:{es:"Mensajes de venta para tu tienda", en:"Sales messages for your store"},
  p:{es:"Actúa como copywriter de e-commerce. Escríbeme mensajes listos para promocionar y vender los productos de mi tienda de [PRODUCTOS] por distintos canales (WhatsApp, redes, email). Dame: un mensaje para anunciar un producto, uno para una oferta, uno para recordar a clientes, y uno para responder a interesados. Cercanos, persuasivos y orientados a generar la venta. Listos para copiar y adaptar.",
     en:"Act as an e-commerce copywriter. Write me ready messages to promote and sell my [PRODUCTS] store products via different channels (WhatsApp, social media, email). Give me: a message to announce a product, one for an offer, one to remind customers, and one to respond to interested people. Warm, persuasive and oriented to generating the sale. Ready to copy and adapt."}},

{ cat:"ecommerce", t:{es:"Aumenta la confianza en tu tienda", en:"Increase trust in your store"},
  p:{es:"Eres consultor de e-commerce. Como mi tienda de [PRODUCTOS] es nueva, la gente desconfía de comprar. Ayúdame a generar confianza: qué elementos mostrar para que se vea confiable y segura, cómo manejar las dudas sobre pagos y envíos, cómo usar reseñas y garantías, y cómo transmitir que soy un negocio real y serio. Práctico, para que los clientes se sientan seguros de comprarme aunque no me conozcan.",
     en:"You're an e-commerce consultant. Since my [PRODUCTS] store is new, people are wary of buying. Help me build trust: what elements to show so it looks reliable and safe, how to handle doubts about payments and shipping, how to use reviews and guarantees, and how to convey that I'm a real, serious business. Practical, so customers feel safe buying from me even if they don't know me."}},

// ---------- EMAIL MARKETING (+10) ----------
{ cat:"email", t:{es:"Asuntos que aumentan la apertura", en:"Subjects that increase opens"},
  p:{es:"Actúa como experto en email marketing. Dame 15 líneas de asunto para correos de [NICHO/TEMA] que logren que la gente los abra. Varía las técnicas: curiosidad, beneficio directo, pregunta, urgencia, personalización, número. Cortas y atractivas, adaptadas a [PÚBLICO]. Que destaquen en una bandeja llena de correos. Marca las 3 con mayor probabilidad de apertura y explica por qué funcionan.",
     en:"Act as an email marketing expert. Give me 15 subject lines for [NICHE/TOPIC] emails that get people to open them. Vary the techniques: curiosity, direct benefit, question, urgency, personalization, number. Short and attractive, adapted to [AUDIENCE]. They should stand out in a full inbox. Mark the 3 with the highest open probability and explain why they work."}},

{ cat:"email", t:{es:"Campaña de email de varios correos", en:"Multi-email campaign"},
  p:{es:"Eres estratega de email marketing. Diseña una campaña de email de 5 correos para [OBJETIVO: lanzar un producto, una oferta, nutrir clientes]. Dame el plan completo: el objetivo de cada correo, qué decir en cada uno, cómo conectarlos entre sí, y cómo llevar al lector progresivamente hacia la acción final. Para cada correo, el asunto y los puntos clave. Que funcione como una secuencia que convierte.",
     en:"You're an email marketing strategist. Design a 5-email campaign for [GOAL: launch a product, an offer, nurture customers]. Give me the complete plan: the goal of each email, what to say in each, how to connect them, and how to progressively lead the reader toward the final action. For each email, the subject and key points. It should work as a converting sequence."}},

{ cat:"email", t:{es:"Correo personal que conecta", en:"Personal email that connects"},
  p:{es:"Actúa como copywriter de email. Escribe un correo de tono personal y cercano para mi lista de [NICHO], como si le escribiera a un amigo. Que comparta algo genuino (una reflexión, una experiencia, una lección), conecte a nivel humano, y de forma natural se relacione con lo que ofrezco. Que fortalezca la relación con mis suscriptores y genere confianza. Cálido y auténtico. Con asunto incluido.",
     en:"Act as an email copywriter. Write a personal, warm-toned email for my [NICHE] list, as if writing to a friend. It should share something genuine (a reflection, an experience, a lesson), connect on a human level, and naturally relate to what I offer. It should strengthen the relationship with my subscribers and build trust. Warm and authentic. With subject included."}},

{ cat:"email", t:{es:"Correo para anunciar contenido nuevo", en:"Email to announce new content"},
  p:{es:"Eres experto en email marketing. Escribe un correo para anunciar a mi lista [CONTENIDO NUEVO: artículo, video, recurso, etc.]. Que despierte interés por el contenido, explique qué valor obtendrán, los invite a verlo con un enlace claro, y mantenga la relación con mi audiencia. Que genere clics y mantenga a mis suscriptores enganchados con lo que comparto. Con asunto incluido. Cercano y atractivo.",
     en:"You're an email marketing expert. Write an email to announce [NEW CONTENT: article, video, resource, etc.] to my list. It should spark interest in the content, explain what value they'll get, invite them to see it with a clear link, and maintain the relationship with my audience. It should generate clicks and keep my subscribers engaged with what I share. With subject included. Warm and attractive."}},

{ cat:"email", t:{es:"Correo con oferta por tiempo limitado", en:"Email with a time-limited offer"},
  p:{es:"Actúa como experto en email de ventas. Escribe un correo para una oferta por tiempo limitado de [PRODUCTO]. Que comunique la oferta de forma clara y atractiva, genere urgencia real con la fecha límite, recuerde el beneficio principal, y motive a comprar antes de que termine. Que el lector sienta que debe actuar ya. Con asunto que invite a abrir de inmediato. Persuasivo y directo.",
     en:"Act as a sales email expert. Write an email for a time-limited offer of [PRODUCT]. It should communicate the offer clearly and attractively, create real urgency with the deadline, remind of the main benefit, and motivate buying before it ends. The reader should feel they must act now. With a subject that invites opening immediately. Persuasive and direct."}},

{ cat:"email", t:{es:"Correo para recuperar suscriptores inactivos", en:"Email to recover inactive subscribers"},
  p:{es:"Eres experto en email marketing. Escribe un correo para reactivar a los suscriptores de [NICHO] que llevan tiempo sin abrir mis correos. Que reconozca la ausencia de forma cercana, les recuerde el valor que ofrezco, les dé una razón para volver a interesarse, y los invite a seguir conmigo o a actualizar sus preferencias. Honesto y cálido. Que recupere a los que aún pueden estar interesados. Con asunto.",
     en:"You're an email marketing expert. Write an email to re-engage [NICHE] subscribers who haven't opened my emails in a while. It should acknowledge the absence warmly, remind them of the value I offer, give them a reason to get interested again, and invite them to stay with me or update their preferences. Honest and warm. To recover those who may still be interested. With subject."}},

{ cat:"email", t:{es:"Correo que genera respuestas", en:"Email that generates replies"},
  p:{es:"Actúa como experto en email marketing. Escribe un correo para mi lista de [NICHO] diseñado para generar respuestas e interacción (no solo aperturas). Que haga una pregunta interesante, invite a responder, genere conversación, y me ayude a conocer mejor a mi audiencia. Que la gente sienta ganas de contestarme. Cercano y genuino. Con asunto incluido. Que aumente la interacción con mis suscriptores.",
     en:"Act as an email marketing expert. Write an email for my [NICHE] list designed to generate replies and interaction (not just opens). It should ask an interesting question, invite replying, generate conversation, and help me get to know my audience better. People should feel like answering me. Warm and genuine. With subject included. To increase interaction with my subscribers."}},

{ cat:"email", t:{es:"Correo de seguimiento tras una consulta", en:"Follow-up email after an inquiry"},
  p:{es:"Eres copywriter de email. Alguien consultó por [PRODUCTO/SERVICIO] pero no concretó. Escribe un correo de seguimiento que retome el contacto de forma natural, resuelva posibles dudas que lo frenaron, refuerce el valor, y lo invite amablemente a dar el siguiente paso. Que no presione pero que reactive el interés. Cercano y profesional. Con asunto incluido. Que ayude a cerrar la venta que quedó pendiente.",
     en:"You're an email copywriter. Someone inquired about [PRODUCT/SERVICE] but didn't follow through. Write a follow-up email that resumes contact naturally, resolves possible doubts that stopped them, reinforces the value, and kindly invites them to take the next step. It shouldn't pressure but reactivate interest. Warm and professional. With subject included. To help close the pending sale."}},

{ cat:"email", t:{es:"Correo para pedir testimonios", en:"Email to ask for testimonials"},
  p:{es:"Actúa como experto en fidelización. Escribe un correo para pedirles a mis clientes que compraron [PRODUCTO] que me dejen un testimonio o reseña. Que agradezca su compra, les pida su opinión de forma amable y fácil de dar, les explique por qué es importante para mí, y opcionalmente ofrezca un incentivo. Que motive a responder sin sonar insistente. Cálido y genuino. Con asunto incluido.",
     en:"Act as a loyalty expert. Write an email to ask my customers who bought [PRODUCT] to leave me a testimonial or review. It should thank them for their purchase, ask for their opinion kindly and easy to give, explain why it's important to me, and optionally offer an incentive. It should motivate replying without sounding pushy. Warm and genuine. With subject included."}},

{ cat:"email", t:{es:"Correo de valor que prepara la venta", en:"Value email that sets up the sale"},
  p:{es:"Eres estratega de email marketing. Escribe un correo que aporte mucho valor sobre [TEMA] a mi lista de [NICHO] y, sin vender directamente, prepare el terreno para una oferta futura de [PRODUCTO]. Que enseñe algo útil, demuestre mi experiencia, genere confianza, y deje al lector con ganas de más. Que cuando llegue la oferta, ya esté predispuesto a comprar. Con asunto incluido. Valioso y estratégico.",
     en:"You're an email marketing strategist. Write an email that provides great value about [TOPIC] to my [NICHE] list and, without selling directly, sets the stage for a future offer of [PRODUCT]. It should teach something useful, demonstrate my expertise, build trust, and leave the reader wanting more. So when the offer arrives, they're already inclined to buy. With subject included. Valuable and strategic."}},

// ---------- SEO Y BLOGS (+10) ----------
{ cat:"seo", t:{es:"Cluster de contenido sobre un tema", en:"Content cluster on a topic"},
  p:{es:"Actúa como estratega de SEO. Quiero posicionarme como autoridad en [TEMA] creando varios artículos conectados. Diséñame un cluster de contenido: un artículo principal sobre el tema general, y 8 artículos relacionados que lo complementen, cada uno con su palabra clave. Explícame cómo enlazarlos entre sí para fortalecer el posicionamiento. Que construya autoridad temática y atraiga tráfico sostenido.",
     en:"Act as an SEO strategist. I want to position myself as an authority in [TOPIC] by creating several connected articles. Design me a content cluster: a main article about the general topic, and 8 related articles that complement it, each with its keyword. Explain how to link them to strengthen ranking. It should build topical authority and attract sustained traffic."}},

{ cat:"seo", t:{es:"Optimiza imágenes para SEO", en:"Optimize images for SEO"},
  p:{es:"Eres experto en SEO técnico. Explícame de forma simple cómo optimizar las imágenes de mi sitio o blog de [TEMA] para que ayuden al posicionamiento. Dame: cómo nombrar los archivos de imagen, qué textos alternativos (alt) usar, cómo aprovechar las imágenes para palabras clave, y buenas prácticas para que no ralenticen mi sitio. Práctico y fácil de aplicar para alguien que no es experto en tecnología.",
     en:"You're a technical SEO expert. Explain simply how to optimize my site or blog images about [TOPIC] so they help ranking. Give me: how to name the image files, what alt texts to use, how to leverage images for keywords, and best practices so they don't slow my site. Practical and easy to apply for someone who isn't a tech expert."}},

{ cat:"seo", t:{es:"Guía completa para posicionar una palabra", en:"Complete guide to rank a keyword"},
  p:{es:"Actúa como consultor SEO. Quiero posicionar mi sitio para la palabra clave [KEYWORD]. Dame una guía paso a paso: cómo analizar qué busca la gente con esa palabra, cómo crear contenido que responda mejor que la competencia, cómo estructurarlo, dónde colocar la keyword, y qué más necesito para llegar a los primeros resultados. Completa y aplicable para alguien que quiere posicionar sin ser experto.",
     en:"Act as an SEO consultant. I want to rank my site for the keyword [KEYWORD]. Give me a step-by-step guide: how to analyze what people search with that word, how to create content that answers better than the competition, how to structure it, where to place the keyword, and what else I need to reach the top results. Complete and applicable for someone who wants to rank without being an expert."}},

{ cat:"seo", t:{es:"Calendario editorial SEO", en:"SEO editorial calendar"},
  p:{es:"Eres estratega de contenido SEO. Crea un calendario editorial de 3 meses para un blog de [TEMA/NICHO] orientado a posicionar en Google. Dame los artículos a publicar cada semana, con su título optimizado, palabra clave objetivo e intención. Que combine temas para atraer tráfico, temas para generar confianza y temas para vender, organizados de forma estratégica. En formato de tabla por semanas. Realista de mantener.",
     en:"You're an SEO content strategist. Create a 3-month editorial calendar for a blog about [TOPIC/NICHE] aimed at ranking on Google. Give me the articles to publish each week, with their optimized title, target keyword and intent. It should combine topics to attract traffic, topics to build trust and topics to sell, organized strategically. In a table by weeks. Realistic to maintain."}},

{ cat:"seo", t:{es:"Mejora un artículo para que posicione mejor", en:"Improve an article to rank better"},
  p:{es:"Actúa como experto en SEO. Tengo un artículo sobre [TEMA] que no posiciona bien para [KEYWORD]. Sin necesidad de pegarte todo el texto, dame una lista de mejoras que suelen funcionar: cómo mejorar el título y la introducción, qué secciones agregar para que sea más completo, cómo optimizar la keyword, qué le falta frente a los que están en los primeros lugares, y cómo aumentar su relevancia. Práctico y priorizado por impacto.",
     en:"Act as an SEO expert. I have an article about [TOPIC] that doesn't rank well for [KEYWORD]. Without needing to paste the whole text, give me a list of improvements that usually work: how to improve the title and intro, what sections to add to make it more complete, how to optimize the keyword, what it's missing versus those in the top spots, and how to increase its relevance. Practical and prioritized by impact."}},

{ cat:"seo", t:{es:"Encuentra preguntas que la gente busca", en:"Find questions people search for"},
  p:{es:"Eres experto en SEO. Para el tema [TEMA], dame una lista de 15 preguntas reales que la gente busca en Google relacionadas con eso. Organízalas de las más generales a las más específicas, y señala cuáles tienen más potencial para crear contenido que atraiga tráfico. Que me sirvan para crear artículos, FAQs o videos que respondan lo que mi público realmente quiere saber. Útiles y accionables.",
     en:"You're an SEO expert. For the topic [TOPIC], give me a list of 15 real questions people search on Google related to it. Organize them from most general to most specific, and indicate which have the most potential to create traffic-attracting content. They should help me create articles, FAQs or videos that answer what my audience really wants to know. Useful and actionable."}},

{ cat:"seo", t:{es:"Texto SEO para página de servicio", en:"SEO copy for a service page"},
  p:{es:"Actúa como redactor SEO. Escribe el texto optimizado para la página de mi servicio de [SERVICIO] dirigido a [PÚBLICO] en [CIUDAD/ZONA si aplica]. Que incluya la palabra clave principal de forma natural, explique el servicio y sus beneficios, genere confianza, responda dudas comunes, y termine con una llamada a la acción. Optimizado para posicionar en Google y a la vez convencer al visitante de contratarme.",
     en:"Act as an SEO writer. Write the optimized copy for my [SERVICE] service page aimed at [AUDIENCE] in [CITY/AREA if applicable]. It should include the main keyword naturally, explain the service and its benefits, build trust, answer common doubts, and end with a call to action. Optimized to rank on Google while convincing the visitor to hire me."}},

{ cat:"seo", t:{es:"Estrategia de SEO local", en:"Local SEO strategy"},
  p:{es:"Eres experto en SEO local. Tengo un negocio de [TIPO DE NEGOCIO] en [CIUDAD/ZONA] y quiero que me encuentren las personas de mi zona cuando buscan en Google. Dame una estrategia de SEO local: cómo aparecer en las búsquedas locales, qué palabras clave usar con mi ubicación, cómo aprovechar las reseñas, y qué hacer para destacar frente a la competencia local. Práctica y aplicable para atraer clientes cercanos.",
     en:"You're a local SEO expert. I have a [TYPE OF BUSINESS] in [CITY/AREA] and want people in my area to find me when they search on Google. Give me a local SEO strategy: how to appear in local searches, what keywords to use with my location, how to leverage reviews, and what to do to stand out against local competition. Practical and applicable to attract nearby customers."}},

{ cat:"seo", t:{es:"Mejora los títulos de tu blog", en:"Improve your blog titles"},
  p:{es:"Actúa como experto en SEO y titulares. Tengo varios artículos en mi blog de [TEMA] pero reciben pocos clics desde Google. Dame fórmulas y ejemplos de títulos que combinen SEO (con la palabra clave) y atractivo para hacer clic. Explícame qué hace que un título reciba más clics en los resultados de búsqueda, y dame 10 ejemplos de títulos optimizados que pueda adaptar a mis artículos. Prácticos y efectivos.",
     en:"Act as an SEO and headline expert. I have several articles on my [TOPIC] blog but they get few clicks from Google. Give me formulas and examples of titles that combine SEO (with the keyword) and click appeal. Explain what makes a title get more clicks in search results, and give me 10 examples of optimized titles I can adapt to my articles. Practical and effective."}},

{ cat:"seo", t:{es:"Contenido evergreen que dura años", en:"Evergreen content that lasts years"},
  p:{es:"Eres estratega de contenido SEO. Quiero crear contenido evergreen (que se mantenga relevante y atraiga tráfico durante años) para mi blog de [TEMA/NICHO]. Dame: 10 ideas de temas evergreen que la gente siempre busca, por qué se mantienen vigentes, cómo crearlos para que duren, y cómo actualizarlos cada cierto tiempo. Que me traigan tráfico constante sin tener que estar publicando todo el tiempo. Útiles y estratégicos.",
     en:"You're an SEO content strategist. I want to create evergreen content (that stays relevant and attracts traffic for years) for my [TOPIC/NICHE] blog. Give me: 10 evergreen topic ideas people always search for, why they stay relevant, how to create them to last, and how to update them periodically. They should bring me constant traffic without having to publish all the time. Useful and strategic."}},

// ---------- VIDEO Y GUIONES (+10) ----------
{ cat:"video", t:{es:"Guion de video para presentar tu negocio", en:"Script to introduce your business on video"},
  p:{es:"Actúa como guionista de marketing. Escribe el guion de un video corto para presentar mi negocio [NEGOCIO] a quienes no me conocen. Que cuente quién soy, qué ofrezco, a quién ayudo y por qué soy buena opción, de forma cercana y atractiva. Con un buen inicio que enganche y un cierre que invite a contactar o seguirme. Indica qué decir y qué mostrar. Que genere confianza e interés en mi negocio.",
     en:"Act as a marketing scriptwriter. Write the script of a short video to introduce my business [BUSINESS] to those who don't know me. It should tell who I am, what I offer, who I help and why I'm a good option, warmly and attractively. With a good engaging opening and a closing that invites contact or following. Indicate what to say and what to show. It should build trust and interest in my business."}},

{ cat:"video", t:{es:"Ideas de videos que enseñan y venden", en:"Video ideas that teach and sell"},
  p:{es:"Eres estratega de contenido en video. Para mi negocio de [TEMA/NICHO], dame 12 ideas de videos que enseñen algo útil a mi público y a la vez ayuden a vender [PRODUCTO/SERVICIO]. Para cada una: el tema, qué enseña, y cómo conecta sutilmente con lo que vendo. Que aporten valor real (no solo venta) y posicionen mi conocimiento mientras atraen clientes. Ordénalas por potencial. Prácticas y aplicables.",
     en:"You're a video content strategist. For my [TOPIC/NICHE] business, give me 12 video ideas that teach something useful to my audience and at the same time help sell [PRODUCT/SERVICE]. For each: the topic, what it teaches, and how it subtly connects with what I sell. They should provide real value (not just sales) and position my knowledge while attracting customers. Sort them by potential. Practical and applicable."}},

{ cat:"video", t:{es:"Guion para video de preguntas frecuentes", en:"FAQ video script"},
  p:{es:"Actúa como creador de contenido. Escribe el guion de un video donde respondo las preguntas más frecuentes sobre [PRODUCTO/SERVICIO/TEMA]. Que tenga una intro que enganche, las preguntas y respuestas organizadas de forma clara y útil, un tono cercano, y un cierre con llamada a la acción. Que resuelva las dudas de mi público y genere confianza para comprar. Indica qué decir y qué mostrar en cada parte.",
     en:"Act as a content creator. Write the script of a video where I answer the most frequent questions about [PRODUCT/SERVICE/TOPIC]. It should have an engaging intro, the questions and answers organized clearly and usefully, a warm tone, and a closing with a call to action. It should resolve my audience's doubts and build trust to buy. Indicate what to say and what to show in each part."}},

{ cat:"video", t:{es:"Guion para video motivacional", en:"Motivational video script"},
  p:{es:"Eres guionista de contenido inspirador. Escribe el guion de un video corto y motivacional sobre [TEMA] para [PÚBLICO]. Que conecte emocionalmente, transmita un mensaje inspirador o de aliento, use un lenguaje que llegue, y termine dejando a la persona motivada a actuar. Indica el tono, el ritmo y qué imágenes o apoyos visuales usar. Que emocione y se quiera compartir. Auténtico y poderoso, sin clichés vacíos.",
     en:"You're an inspirational content scriptwriter. Write the script of a short, motivational video about [TOPIC] for [AUDIENCE]. It should connect emotionally, convey an inspiring or encouraging message, use language that lands, and end leaving the person motivated to act. Indicate the tone, the pacing and what images or visual aids to use. It should move people and make them want to share. Authentic and powerful, without empty clichés."}},

{ cat:"video", t:{es:"Guion para mostrar cómo funciona tu producto", en:"Script to show how your product works"},
  p:{es:"Actúa como guionista de demostración. Escribe el guion de un video donde muestro cómo funciona [PRODUCTO/SERVICIO] y sus beneficios. Que presente el problema que resuelve, muestre el producto en acción de forma clara, destaque cómo facilita la vida del cliente, y termine invitando a obtenerlo. Indica qué mostrar en pantalla en cada paso y qué decir. Que el espectador entienda el valor y quiera comprarlo. Práctico y convincente.",
     en:"Act as a demo scriptwriter. Write the script of a video where I show how [PRODUCT/SERVICE] works and its benefits. It should present the problem it solves, show the product in action clearly, highlight how it makes the customer's life easier, and end by inviting them to get it. Indicate what to show on screen at each step and what to say. The viewer should understand the value and want to buy it. Practical and convincing."}},

{ cat:"video", t:{es:"Ganchos virales para tus videos", en:"Viral hooks for your videos"},
  p:{es:"Eres experto en contenido viral. Dame 12 ganchos potentes para los primeros segundos de videos sobre [TEMA/NICHO] que capturen la atención y eviten que la gente siga deslizando. Varía los tipos: pregunta intrigante, promesa de valor, afirmación polémica, error común, dato sorprendente, historia. Que generen ganas de seguir viendo. Marca los 4 más fuertes y dime para qué tipo de video usar cada uno.",
     en:"You're a viral content expert. Give me 12 powerful hooks for the first seconds of videos about [TOPIC/NICHE] that capture attention and prevent people from scrolling. Vary the types: intriguing question, value promise, controversial statement, common mistake, surprising fact, story. They should make people want to keep watching. Mark the 4 strongest and tell me what type of video to use each for."}},

{ cat:"video", t:{es:"Guion para anunciar una oferta en video", en:"Script to announce an offer on video"},
  p:{es:"Actúa como guionista de marketing. Escribe el guion de un video corto para anunciar una oferta especial de [PRODUCTO]. Que capte la atención de inmediato, comunique la oferta de forma clara y atractiva, genere urgencia, destaque el beneficio y el ahorro, y termine con una llamada a la acción potente. Indica qué mostrar y qué decir. Dinámico y persuasivo. Que impulse a la gente a aprovechar la oferta ya.",
     en:"Act as a marketing scriptwriter. Write the script of a short video to announce a special offer of [PRODUCT]. It should grab attention immediately, communicate the offer clearly and attractively, create urgency, highlight the benefit and savings, and end with a powerful call to action. Indicate what to show and what to say. Dynamic and persuasive. To drive people to take advantage of the offer now."}},

{ cat:"video", t:{es:"Serie de videos educativos", en:"Educational video series"},
  p:{es:"Eres estratega de contenido educativo. Diséñame una serie de videos educativos sobre [TEMA] para [PÚBLICO] que enseñe el tema de forma progresiva. Dame: el concepto de la serie, 7 videos con su título y qué enseña cada uno, ordenados de lo básico a lo avanzado, y cómo conectarlos para que la gente vea toda la serie. Que eduque, posicione mi conocimiento y haga que mi audiencia me siga. Práctica y aplicable.",
     en:"You're an educational content strategist. Design me a series of educational videos about [TOPIC] for [AUDIENCE] that teaches the topic progressively. Give me: the series concept, 7 videos with their title and what each teaches, ordered from basic to advanced, and how to connect them so people watch the whole series. It should educate, position my knowledge and make my audience follow me. Practical and applicable."}},

{ cat:"video", t:{es:"Guion para un video de tu día a día", en:"Script for a day-in-the-life video"},
  p:{es:"Actúa como creador de contenido. Ayúdame a crear el guion para un video tipo 'un día en mi vida/trabajo' relacionado con [ACTIVIDAD/NEGOCIO] para [RED SOCIAL]. Que muestre de forma atractiva y auténtica lo que hago, conecte con mi público, genere cercanía y de paso muestre mi trabajo o producto. Indica qué momentos grabar, qué decir o qué texto poner, y cómo hacerlo interesante. Que humanice mi marca y conecte.",
     en:"Act as a content creator. Help me create the script for a 'day in my life/work' video related to [ACTIVITY/BUSINESS] for [SOCIAL NETWORK]. It should attractively and authentically show what I do, connect with my audience, create warmth and also showcase my work or product. Indicate what moments to film, what to say or what text to add, and how to make it interesting. It should humanize my brand and connect."}},

{ cat:"video", t:{es:"Convierte un artículo en video", en:"Turn an article into a video"},
  p:{es:"Eres experto en adaptar contenido a video. Tengo un artículo o tema sobre [TEMA] y quiero convertirlo en un video atractivo para [PLATAFORMA]. Ayúdame a adaptarlo: cómo resumir lo esencial, cómo empezar con un buen gancho, cómo hacerlo dinámico y visual, y cómo cerrar con una llamada a la acción. Dame el guion adaptado indicando qué decir y qué mostrar. Que funcione mejor en video que como texto. Práctico y aplicable.",
     en:"You're an expert at adapting content to video. I have an article or topic about [TOPIC] and want to turn it into an engaging video for [PLATFORM]. Help me adapt it: how to summarize the essentials, how to start with a good hook, how to make it dynamic and visual, and how to close with a call to action. Give me the adapted script indicating what to say and what to show. It should work better as video than as text. Practical and applicable."}},

// ---------- MARCA PERSONAL (+5) ----------
{ cat:"personal", t:{es:"Construye tu reputación profesional", en:"Build your professional reputation"},
  p:{es:"Actúa como estratega de marca personal. Quiero construir una buena reputación profesional en [ÁREA/SECTOR]. Dame una estrategia: cómo demostrar mi experiencia y conocimiento, cómo ganar credibilidad con el tiempo, cómo aprovechar testimonios y resultados, cómo manejar mi presencia online, y cómo lograr que me reconozcan como alguien confiable y competente en lo que hago. Práctica y aplicable a largo plazo.",
     en:"Act as a personal brand strategist. I want to build a good professional reputation in [AREA/SECTOR]. Give me a strategy: how to demonstrate my experience and knowledge, how to gain credibility over time, how to leverage testimonials and results, how to manage my online presence, and how to be recognized as someone trustworthy and competent in what I do. Practical and applicable long-term."}},

{ cat:"personal", t:{es:"Networking efectivo", en:"Effective networking"},
  p:{es:"Eres experto en relaciones profesionales. Quiero hacer networking para crecer en [ÁREA/SECTOR] pero no se me da fácil. Dame estrategias prácticas: cómo conectar con personas valiosas de mi sector, cómo presentarme y generar interés, cómo mantener las relaciones en el tiempo, cómo aportar antes de pedir, y cómo aprovechar el networking para oportunidades. Aplicable tanto en persona como en redes profesionales. Que me ayude a construir relaciones útiles.",
     en:"You're a professional relationships expert. I want to network to grow in [AREA/SECTOR] but it doesn't come easy to me. Give me practical strategies: how to connect with valuable people in my sector, how to introduce myself and generate interest, how to maintain relationships over time, how to give before asking, and how to leverage networking for opportunities. Applicable both in person and on professional networks. To help me build useful relationships."}},

{ cat:"personal", t:{es:"Tu mensaje central como profesional", en:"Your core message as a professional"},
  p:{es:"Actúa como experto en marca personal. Ayúdame a definir mi mensaje central: la idea principal por la que quiero ser conocido en [ÁREA/TEMA]. Me dedico a [ACTIVIDAD] y creo en [VALOR/ENFOQUE]. Dame varias versiones de un mensaje claro y consistente que pueda comunicar en todo mi contenido y presentaciones, que refleje quién soy y qué aporto. Que me dé claridad y coherencia en mi comunicación. Auténtico y memorable.",
     en:"Act as a personal branding expert. Help me define my core message: the main idea I want to be known for in [AREA/TOPIC]. I work in [ACTIVITY] and believe in [VALUE/APPROACH]. Give me several versions of a clear, consistent message I can communicate across all my content and presentations, reflecting who I am and what I bring. It should give me clarity and coherence in my communication. Authentic and memorable."}},

{ cat:"personal", t:{es:"Supera el miedo a mostrarte en redes", en:"Overcome the fear of showing yourself online"},
  p:{es:"Eres coach de marca personal. Quiero crear contenido y mostrarme en redes para crecer profesionalmente, pero me da miedo el qué dirán y exponerme. Ayúdame: cómo superar ese miedo, cómo empezar de forma cómoda, cómo manejar las posibles críticas, cómo ganar confianza con el tiempo, y por qué vale la pena hacerlo a pesar del miedo. Consejos prácticos y motivadores para animarme a dar el paso sin presionarme.",
     en:"You're a personal brand coach. I want to create content and show myself online to grow professionally, but I'm afraid of what people will say and exposing myself. Help me: how to overcome that fear, how to start comfortably, how to handle possible criticism, how to gain confidence over time, and why it's worth doing despite the fear. Practical, motivating advice to encourage me to take the step without pressuring myself."}},

{ cat:"personal", t:{es:"Diferénciate en tu sector", en:"Differentiate yourself in your field"},
  p:{es:"Actúa como estratega de marca personal. En mi sector de [ÁREA] hay mucha gente que hace lo mismo que yo. Ayúdame a diferenciarme: cómo encontrar lo que me hace único, cómo destacar mi enfoque o personalidad, cómo comunicar lo que me distingue, y cómo posicionarme de forma que la gente me elija a mí. Que deje de ser uno más y me convierta en una opción memorable y distinta. Práctico y aplicable.",
     en:"Act as a personal brand strategist. In my [AREA] field there are many people who do the same as me. Help me differentiate myself: how to find what makes me unique, how to highlight my approach or personality, how to communicate what distinguishes me, and how to position myself so people choose me. To stop being one more and become a memorable, distinct option. Practical and applicable."}},

// ---------- IA Y AGENTES (+5) ----------
{ cat:"agents", t:{es:"Optimiza tus prompts para mejores respuestas", en:"Optimize your prompts for better answers"},
  p:{es:"Actúa como experto en prompts de IA. Enséñame a escribir mejores prompts para obtener respuestas más útiles de la IA. Dame los elementos clave de un buen prompt (rol, contexto, instrucción clara, formato deseado, ejemplos), errores comunes que arruinan los resultados, y una estructura o plantilla que pueda seguir siempre. Con ejemplos de un prompt malo y su versión mejorada. Práctico, para que aprenda a pedirle mejor a la IA.",
     en:"Act as an AI prompt expert. Teach me to write better prompts to get more useful answers from AI. Give me the key elements of a good prompt (role, context, clear instruction, desired format, examples), common mistakes that ruin results, and a structure or template I can always follow. With examples of a bad prompt and its improved version. Practical, so I learn to ask AI better."}},

{ cat:"agents", t:{es:"Usa la IA para tomar mejores decisiones", en:"Use AI to make better decisions"},
  p:{es:"Eres asesor experto en decisiones. Quiero usar la IA como apoyo para pensar mejor mis decisiones importantes. Enséñame cómo: qué tipo de preguntas hacerle para analizar una decisión, cómo pedirle que considere pros, contras y riesgos, cómo usarla para ver ángulos que no había pensado, y cómo combinarla con mi propio criterio. Dame ejemplos de cómo plantearle una decisión para que me ayude a decidir con más claridad.",
     en:"You're an expert decision advisor. I want to use AI as support to think through my important decisions better. Teach me how: what type of questions to ask it to analyze a decision, how to ask it to consider pros, cons and risks, how to use it to see angles I hadn't thought of, and how to combine it with my own judgment. Give me examples of how to present a decision so it helps me decide with more clarity."}},

{ cat:"agents", t:{es:"Automatiza tu creación de contenido con IA", en:"Automate your content creation with AI"},
  p:{es:"Actúa como experto en IA para creadores. Quiero usar la IA para crear contenido más rápido para [NICHO/NEGOCIO] sin perder calidad ni mi voz. Dame un sistema: cómo usar la IA para generar ideas, borradores, captions y guiones, cómo darle mi estilo para que suene a mí, qué prompts usar para cada tipo de contenido, y cómo revisar y mejorar lo que genera. Práctico, para producir más contenido en menos tiempo.",
     en:"Act as an AI-for-creators expert. I want to use AI to create content faster for [NICHE/BUSINESS] without losing quality or my voice. Give me a system: how to use AI to generate ideas, drafts, captions and scripts, how to give it my style so it sounds like me, what prompts to use for each content type, and how to review and improve what it generates. Practical, to produce more content in less time."}},

{ cat:"agents", t:{es:"Crea un asistente para responder clientes", en:"Create an assistant to answer customers"},
  p:{es:"Eres experto en IA para atención al cliente. Ayúdame a crear las instrucciones para un asistente de IA que responda las preguntas frecuentes de los clientes de mi negocio [NEGOCIO]. Define: el tono y la personalidad, qué información debe conocer sobre mis productos y servicios, cómo responder las dudas más comunes, cómo manejar quejas con empatía, cuándo pasar a un humano, y qué no debe decir. Completo y listo para configurar y usar.",
     en:"You're a customer service AI expert. Help me create the instructions for an AI assistant that answers frequent questions from my business's customers [BUSINESS]. Define: the tone and personality, what information it should know about my products and services, how to answer the most common doubts, how to handle complaints with empathy, when to escalate to a human, and what it shouldn't say. Complete and ready to set up and use."}},

{ cat:"agents", t:{es:"Aprende cualquier tema con la IA", en:"Learn any topic with AI"},
  p:{es:"Actúa como tutor personal experto. Quiero usar la IA para aprender [TEMA/HABILIDAD] de forma efectiva. Enséñame cómo: cómo pedirle que me explique de forma simple, cómo hacer que adapte las explicaciones a mi nivel, cómo pedirle ejemplos y ejercicios, cómo usar la IA para practicar y resolver dudas, y cómo estructurar mi aprendizaje con su ayuda. Dame ejemplos de prompts para aprender mejor. Práctico y aplicable.",
     en:"Act as an expert personal tutor. I want to use AI to learn [TOPIC/SKILL] effectively. Teach me how: how to ask it to explain simply, how to make it adapt explanations to my level, how to ask it for examples and exercises, how to use AI to practice and resolve doubts, and how to structure my learning with its help. Give me examples of prompts to learn better. Practical and applicable."}},

// ---------- EDUCACIÓN (+10) ----------
{ cat:"education", t:{es:"Plan de estudio para un examen", en:"Study plan for an exam"},
  p:{es:"Actúa como tutor experto. Tengo un examen de [MATERIA] en [TIEMPO DISPONIBLE] y necesito organizarme para estudiar. Créame un plan de estudio realista: cómo dividir los temas en el tiempo que tengo, qué estudiar primero, cómo repasar para que se quede, cuándo descansar, y cómo llegar preparado sin estudiar todo a última hora. Práctico y adaptado al tiempo que tengo. Que me ayude a aprobar con menos estrés.",
     en:"Act as an expert tutor. I have an exam on [SUBJECT] in [AVAILABLE TIME] and need to organize my studying. Create a realistic study plan: how to divide the topics in the time I have, what to study first, how to review so it sticks, when to rest, and how to arrive prepared without cramming. Practical and adapted to the time I have. To help me pass with less stress."}},

{ cat:"education", t:{es:"Explica un concepto con ejemplos", en:"Explain a concept with examples"},
  p:{es:"Eres profesor experto en explicar. Explícame [CONCEPTO/TEMA] de forma clara y fácil de entender. Usa una explicación sencilla, varios ejemplos de la vida real que lo ilustren, una analogía que lo haga memorable, y al final un resumen de lo más importante. Adapta la explicación a [NIVEL: principiante, intermedio]. Que entienda el concepto a fondo aunque sea nuevo para mí. Claro y didáctico.",
     en:"You're a teacher who's an expert at explaining. Explain [CONCEPT/TOPIC] to me clearly and easy to understand. Use a simple explanation, several real-life examples that illustrate it, an analogy that makes it memorable, and at the end a summary of the most important. Adapt the explanation to [LEVEL: beginner, intermediate]. So I understand the concept thoroughly even if it's new to me. Clear and didactic."}},

{ cat:"education", t:{es:"Crea ejercicios de práctica", en:"Create practice exercises"},
  p:{es:"Actúa como diseñador educativo. Crea una serie de ejercicios de práctica sobre [TEMA] para nivel [NIVEL]. Dame ejercicios variados de menor a mayor dificultad, con sus respuestas y una breve explicación de cada una. Que me ayuden a practicar y dominar el tema, reforzando lo aprendido. Que cubran los aspectos más importantes del tema. Útiles para estudiar o enseñar. Claros y bien organizados.",
     en:"Act as an educational designer. Create a series of practice exercises about [TOPIC] for [LEVEL] level. Give me varied exercises from easy to hard, with their answers and a brief explanation of each. They should help me practice and master the topic, reinforcing what I learned. They should cover the most important aspects of the topic. Useful for studying or teaching. Clear and well organized."}},

{ cat:"education", t:{es:"Resumen claro de un tema complejo", en:"Clear summary of a complex topic"},
  p:{es:"Eres experto en simplificar. Hazme un resumen claro y organizado de [TEMA COMPLEJO] que destaque solo lo más importante que debo saber. Estructúralo de lo más básico a lo más avanzado, usa lenguaje simple, e incluye los puntos clave de forma que pueda entender y recordar lo esencial. Que me ayude a comprender un tema difícil de forma rápida y clara. Bien organizado y fácil de repasar.",
     en:"You're an expert at simplifying. Make me a clear, organized summary of [COMPLEX TOPIC] highlighting only the most important I should know. Structure it from most basic to most advanced, use simple language, and include the key points so I can understand and remember the essentials. To help me grasp a difficult topic quickly and clearly. Well organized and easy to review."}},

{ cat:"education", t:{es:"Método para memorizar información", en:"Method to memorize information"},
  p:{es:"Actúa como experto en técnicas de memoria. Necesito memorizar [QUÉ NECESITAS MEMORIZAR] para [PROPÓSITO]. Enséñame la mejor técnica para lograrlo y aplícala directamente a mi caso con un ejemplo. Explícame paso a paso cómo usarla, cómo repasar para no olvidar, y cómo hacer que la información se quede en mi memoria a largo plazo. Práctica y aplicable a lo que necesito memorizar. Que de verdad funcione.",
     en:"Act as a memory-technique expert. I need to memorize [WHAT YOU NEED TO MEMORIZE] for [PURPOSE]. Teach me the best technique to do it and apply it directly to my case with an example. Explain step by step how to use it, how to review so I don't forget, and how to make the information stay in my long-term memory. Practical and applicable to what I need to memorize. So it really works."}},

{ cat:"education", t:{es:"Actividad para enseñar un tema", en:"Activity to teach a topic"},
  p:{es:"Eres experto en didáctica. Diseña una actividad práctica y participativa para enseñar [TEMA] a [PÚBLICO/EDAD]. Que sea dinámica, fácil de organizar, con materiales simples, e involucre a los participantes para que aprendan haciendo. Explica el objetivo, los pasos, cómo realizarla, y qué aprenderán. Que haga el aprendizaje entretenido y efectivo. Aplicable en un aula, taller o en casa. Práctica y clara.",
     en:"You're a didactics expert. Design a practical, participatory activity to teach [TOPIC] to [AUDIENCE/AGE]. It should be dynamic, easy to organize, with simple materials, and involve participants so they learn by doing. Explain the objective, the steps, how to do it, and what they'll learn. It should make learning entertaining and effective. Applicable in a classroom, workshop or at home. Practical and clear."}},

{ cat:"education", t:{es:"Explica algo a un niño", en:"Explain something to a child"},
  p:{es:"Actúa como educador infantil experto. Explícame [TEMA] de forma que un niño de [EDAD] lo entienda y le parezca interesante. Usa un lenguaje sencillo y adecuado a su edad, ejemplos y comparaciones con cosas que conoce, y hazlo entretenido para captar su atención. Que el niño entienda el tema y se quede con curiosidad por aprender más. Claro, divertido y apropiado para su edad. Que despierte su interés.",
     en:"Act as an expert children's educator. Explain [TOPIC] to me in a way a [AGE]-year-old child understands and finds interesting. Use simple, age-appropriate language, examples and comparisons with things they know, and make it entertaining to capture their attention. The child should understand the topic and stay curious to learn more. Clear, fun and age-appropriate. To spark their interest."}},

{ cat:"education", t:{es:"Pregunta de pensamiento crítico", en:"Critical thinking question"},
  p:{es:"Eres educador experto en pensamiento crítico. Sobre el tema [TEMA], dame 10 preguntas que estimulen el pensamiento crítico y la reflexión en [PÚBLICO/NIVEL]. Que no se respondan con un simple sí o no, sino que inviten a analizar, comparar, cuestionar, argumentar y pensar en profundidad. Ordénalas de menor a mayor complejidad. Ideales para generar debate, reflexión o aprendizaje profundo. Que hagan pensar de verdad.",
     en:"You're an expert critical thinking educator. On the topic [TOPIC], give me 10 questions that stimulate critical thinking and reflection in [AUDIENCE/LEVEL]. They shouldn't be answered with a simple yes or no, but invite analyzing, comparing, questioning, arguing and thinking deeply. Order them from less to more complex. Ideal for generating debate, reflection or deep learning. They should make people really think."}},

{ cat:"education", t:{es:"Guía para aprender una habilidad nueva", en:"Guide to learn a new skill"},
  p:{es:"Actúa como coach de aprendizaje. Quiero aprender [HABILIDAD] desde cero. Créame una guía de aprendizaje: por dónde empezar, los pasos para ir progresando de principiante a competente, qué practicar en cada etapa, los errores comunes a evitar, cómo medir mi avance, y cuánto tiempo podría tomar. Práctica y motivadora, que me dé un camino claro para aprender la habilidad sin perderme. Realista y aplicable.",
     en:"Act as a learning coach. I want to learn [SKILL] from scratch. Create me a learning guide: where to start, the steps to progress from beginner to competent, what to practice at each stage, the common mistakes to avoid, how to measure my progress, and how long it might take. Practical and motivating, giving me a clear path to learn the skill without getting lost. Realistic and applicable."}},

{ cat:"education", t:{es:"Material de repaso antes de un examen", en:"Review material before an exam"},
  p:{es:"Eres tutor experto. Tengo un examen sobre [TEMA/MATERIA] y quiero repasar lo más importante. Créame un material de repaso: los conceptos clave que debo dominar, las cosas que más suelen preguntar, fórmulas o datos importantes a recordar, y preguntas de práctica con sus respuestas. Organizado de forma que pueda repasar de manera eficiente justo antes del examen. Claro y enfocado en lo esencial. Que me ayude a estar listo.",
     en:"You're an expert tutor. I have an exam on [TOPIC/SUBJECT] and want to review the most important. Create me review material: the key concepts I should master, the things most often asked, important formulas or facts to remember, and practice questions with their answers. Organized so I can review efficiently right before the exam. Clear and focused on the essentials. To help me be ready."}},

// ---------- SALUD Y BIENESTAR (+10) ----------
{ cat:"health", t:{es:"Rutina de bienestar diario", en:"Daily wellness routine"},
  p:{es:"Actúa como coach de bienestar. Ayúdame a crear una rutina diaria sencilla para cuidar mi bienestar físico y mental, considerando que tengo [DESCRIBE TU SITUACIÓN: poco tiempo, mucho estrés, etc.]. Incluye pequeños hábitos saludables fáciles de mantener: movimiento, descanso, alimentación, momentos de calma. Realista y sostenible para mi día a día. Aclara que ante cualquier condición de salud debo consultar a un profesional.",
     en:"Act as a wellness coach. Help me create a simple daily routine to care for my physical and mental wellbeing, considering that I have [DESCRIBE YOUR SITUATION: little time, much stress, etc.]. Include small healthy habits easy to maintain: movement, rest, nutrition, moments of calm. Realistic and sustainable for my daily life. Clarify that for any health condition I should consult a professional."}},

{ cat:"health", t:{es:"Contenido educativo de salud para redes", en:"Health educational content for social media"},
  p:{es:"Actúa como creador de contenido de salud y bienestar. Dame 10 ideas de publicaciones educativas sobre hábitos saludables y bienestar para [PÚBLICO] en redes sociales. Que sean informativas, motivadoras y basadas en recomendaciones generales seguras (no consejos médicos específicos). Para cada idea, el tema y el mensaje principal. Que eduquen y promuevan el bienestar de forma positiva y responsable. Útiles y aplicables.",
     en:"Act as a health and wellness content creator. Give me 10 educational post ideas about healthy habits and wellbeing for [AUDIENCE] on social media. They should be informative, motivating and based on safe general recommendations (not specific medical advice). For each idea, the topic and the main message. They should educate and promote wellbeing positively and responsibly. Useful and applicable."}},

{ cat:"health", t:{es:"Guía de manejo del estrés", en:"Stress management guide"},
  p:{es:"Eres facilitador de bienestar emocional. Crea una guía práctica con técnicas seguras para manejar el estrés del día a día: respiración, pausas, organización, relajación, etc. Para cada técnica, explica cómo hacerla paso a paso y cuándo usarla. Que sean fáciles de aplicar en cualquier momento. Aclara que ante malestar emocional persistente es importante buscar apoyo de un profesional de salud mental. Práctica y útil.",
     en:"You're an emotional wellness facilitator. Create a practical guide with safe techniques to manage everyday stress: breathing, breaks, organization, relaxation, etc. For each technique, explain how to do it step by step and when to use it. They should be easy to apply anytime. Clarify that for persistent emotional distress it's important to seek support from a mental health professional. Practical and useful."}},

{ cat:"health", t:{es:"Hábitos para más energía", en:"Habits for more energy"},
  p:{es:"Actúa como coach de bienestar. Me siento con poca energía durante el día y quiero mejorar eso de forma natural y saludable. Dame hábitos y recomendaciones generales seguras para tener más energía: sobre el descanso, la alimentación, el movimiento, la hidratación y las pausas. Prácticos y fáciles de adoptar. Aclara que si el cansancio persiste o es fuerte, debo consultar a un médico para descartar causas de salud.",
     en:"Act as a wellness coach. I feel low on energy during the day and want to improve that naturally and healthily. Give me safe general habits and recommendations for more energy: about rest, nutrition, movement, hydration and breaks. Practical and easy to adopt. Clarify that if the fatigue persists or is strong, I should consult a doctor to rule out health causes."}},

{ cat:"health", t:{es:"Plan de bienestar para tu equipo", en:"Wellness plan for your team"},
  p:{es:"Actúa como consultor de bienestar organizacional. Diseña un plan sencillo de bienestar para los empleados de [TIPO DE EMPRESA/EQUIPO]. Incluye: pausas activas, manejo del estrés, hábitos saludables durante la jornada, ergonomía básica y actividades de integración. Práctico, de bajo costo y aplicable. Enfocado en mejorar el ambiente, la salud general y el ánimo del equipo de forma positiva. Útil y realista.",
     en:"Act as an organizational wellness consultant. Design a simple wellness plan for the employees of [TYPE OF COMPANY/TEAM]. Include: active breaks, stress management, healthy habits during the workday, basic ergonomics and team-building activities. Practical, low-cost and applicable. Focused on improving the team's environment, general health and mood positively. Useful and realistic."}},

{ cat:"health", t:{es:"Información sobre alimentación balanceada", en:"Information on balanced eating"},
  p:{es:"Actúa como educador en nutrición general. Crea una guía sencilla de alimentación balanceada para una persona promedio sana que quiere comer mejor. Explica el plato saludable, las porciones, los alimentos a incluir más seguido y los a moderar, y consejos prácticos para el día a día con comida accesible. Aclara que para necesidades específicas o condiciones de salud se debe consultar a un nutricionista. Educativa y práctica.",
     en:"Act as a general nutrition educator. Create a simple balanced-eating guide for an average healthy person who wants to eat better. Explain the healthy plate, portions, foods to include more often and to moderate, and practical day-to-day tips with accessible food. Clarify that for specific needs or health conditions a nutritionist should be consulted. Educational and practical."}},

{ cat:"health", t:{es:"Consejos para dormir mejor", en:"Tips to sleep better"},
  p:{es:"Eres educador en higiene del sueño. Dame una guía con recomendaciones generales y seguras para dormir mejor: cómo crear una rutina antes de dormir, el ambiente ideal para descansar, hábitos a evitar, y cómo mantener un horario regular. Prácticas para una persona sana con dificultades leves de sueño por malos hábitos. Aclara que ante insomnio persistente se debe consultar a un profesional de salud. Útil y aplicable.",
     en:"You're a sleep hygiene educator. Give me a guide with safe general recommendations to sleep better: how to create a pre-sleep routine, the ideal environment to rest, habits to avoid, and how to maintain a regular schedule. Practical for a healthy person with mild sleep difficulties due to bad habits. Clarify that for persistent insomnia a health professional should be consulted. Useful and applicable."}},

{ cat:"health", t:{es:"Rutina de ejercicio en casa", en:"Home exercise routine"},
  p:{es:"Actúa como instructor de actividad física. Diseña una rutina de ejercicio suave para hacer en casa, para una persona sana que quiere empezar a moverse más, sin equipo. Incluye calentamiento, ejercicios básicos con repeticiones moderadas, estiramiento, y cómo ir progresando por semanas. Enfócate en la constancia y la técnica segura. Recomienda consultar al médico antes de empezar si hay alguna condición de salud. Práctica y realista.",
     en:"Act as a physical activity instructor. Design a gentle exercise routine to do at home, for a healthy person who wants to start moving more, with no equipment. Include warm-up, basic exercises with moderate reps, stretching, and how to progress weekly. Focus on consistency and safe technique. Recommend consulting a doctor before starting if there's any health condition. Practical and realistic."}},

{ cat:"health", t:{es:"Mensajes motivadores de bienestar", en:"Motivating wellness messages"},
  p:{es:"Actúa como coach de hábitos saludables. Escribe 10 mensajes cortos y motivadores para animar a las personas a cuidar su salud y mantener hábitos saludables (moverse, hidratarse, descansar, alimentarse bien, cuidar su mente). Que sean positivos, cercanos e inspiren a la acción sin culpar ni asustar. Ideales para redes sociales o recordatorios. Que promuevan el bienestar de forma amable y motivadora. Útiles y genuinos.",
     en:"Act as a healthy habits coach. Write 10 short, motivating messages to encourage people to care for their health and maintain healthy habits (move, hydrate, rest, eat well, care for their mind). They should be positive, warm and inspire action without blaming or scaring. Ideal for social media or reminders. They should promote wellbeing kindly and motivatingly. Useful and genuine."}},

{ cat:"health", t:{es:"Rutina de autocuidado para tu bienestar", en:"Self-care routine for your wellbeing"},
  p:{es:"Eres facilitador de bienestar integral. Diseña una rutina de autocuidado semanal sencilla para una persona con vida ocupada que quiere cuidar su salud física y emocional. Incluye momentos de descanso, movimiento, conexión social, desconexión digital, y algo que disfrute. Realista y sostenible, con pequeños hábitos diarios. Que ayude a recargar energía y bajar el estrés de forma equilibrada. Práctica y adaptable a una vida ocupada.",
     en:"You're a holistic wellness facilitator. Design a simple weekly self-care routine for a busy person who wants to care for their physical and emotional health. Include moments of rest, movement, social connection, digital disconnection, and something they enjoy. Realistic and sustainable, with small daily habits. To help recharge energy and lower stress in a balanced way. Practical and adaptable to a busy life."}},

];
