// ============================================================
//  ARSENAL IA — BIBLIOTECA DE PROMPTS (parte 13)
//  Rumbo a 50: Negocios · Diseño · Productividad · E-commerce · Email
// ============================================================

const PROMPTS_13 = [

// ---------- NEGOCIOS (+10) ----------
{ cat:"business", t:{es:"Modelo de negocio en lienzo simple", en:"Business model on a simple canvas"},
  p:{es:"Actúa como consultor de negocios. Ayúdame a definir el modelo de negocio de [IDEA/NEGOCIO] usando un lienzo simple. Cubre: a quién le vendo, qué problema le resuelvo, qué ofrezco, cómo le llego, cómo genero ingresos, qué costos tengo, qué necesito para funcionar, y cuál es mi ventaja. Respóndelo de forma clara y ordenada para tener una visión completa de mi negocio en una sola vista. Práctico y aplicable.",
     en:"Act as a business consultant. Help me define the business model of [IDEA/BUSINESS] using a simple canvas. Cover: who I sell to, what problem I solve for them, what I offer, how I reach them, how I generate revenue, what costs I have, what I need to operate, and what my advantage is. Answer it clearly and orderly to have a complete view of my business in one glance. Practical and applicable."}},

{ cat:"business", t:{es:"Aumenta tus ventas sin gastar más", en:"Increase sales without spending more"},
  p:{es:"Eres consultor de crecimiento. Quiero aumentar las ventas de mi negocio [NEGOCIO] sin invertir mucho dinero. Dame estrategias prácticas y de bajo costo: cómo venderles más a mis clientes actuales, cómo aprovechar mejor lo que ya tengo, cómo mejorar mi oferta, cómo pedir referidos, y cómo cerrar más de las oportunidades que ya llegan. Enfócate en acciones que pueda aplicar ya sin gran presupuesto. Que aumente mis ventas con lo que tengo.",
     en:"You're a growth consultant. I want to increase my business's sales [BUSINESS] without investing much money. Give me practical, low-cost strategies: how to sell more to my current customers, how to better leverage what I already have, how to improve my offer, how to ask for referrals, and how to close more of the opportunities already coming in. Focus on actions I can apply now without a big budget. To increase my sales with what I have."}},

{ cat:"business", t:{es:"Decide si subir tus precios", en:"Decide whether to raise your prices"},
  p:{es:"Actúa como consultor de negocios. Estoy pensando en subir los precios de [PRODUCTO/SERVICIO] pero me da miedo perder clientes. Ayúdame a decidir: cómo saber si mis precios están por debajo de lo que debería, cómo evaluar el impacto de subirlos, cómo comunicar un aumento de precio sin perder clientes, y cómo hacerlo de forma estratégica. Dame un análisis y un enfoque para tomar la mejor decisión sobre mis precios. Práctico y claro.",
     en:"Act as a business consultant. I'm thinking about raising the prices of [PRODUCT/SERVICE] but I'm afraid of losing customers. Help me decide: how to know if my prices are below what they should be, how to evaluate the impact of raising them, how to communicate a price increase without losing customers, and how to do it strategically. Give me an analysis and an approach to make the best decision about my prices. Practical and clear."}},

{ cat:"business", t:{es:"Plan financiero básico de tu negocio", en:"Basic financial plan for your business"},
  p:{es:"Eres asesor financiero de negocios. Ayúdame a crear un plan financiero básico para mi negocio [NEGOCIO]. Explícame de forma simple: cómo proyectar mis ingresos y gastos, cómo saber cuánto necesito vender para no perder, cómo planear mi flujo de dinero, y cómo establecer metas financieras realistas. Sin contabilidad complicada, práctico para alguien que maneja su propio negocio. Que me dé claridad sobre los números de mi negocio para tomar mejores decisiones.",
     en:"You're a business financial advisor. Help me create a basic financial plan for my business [BUSINESS]. Explain simply: how to project my income and expenses, how to know how much I need to sell to not lose money, how to plan my cash flow, and how to set realistic financial goals. Without complicated accounting, practical for someone running their own business. To give me clarity about my business numbers to make better decisions."}},

{ cat:"business", t:{es:"Encuentra tu nicho de mercado", en:"Find your market niche"},
  p:{es:"Actúa como consultor de estrategia. Quiero enfocar mi negocio [NEGOCIO/IDEA] en un nicho específico en vez de tratar de venderle a todos. Ayúdame: cómo identificar un nicho rentable y poco atendido, cómo evaluar si tiene potencial, las ventajas de especializarme, y cómo posicionarme como el especialista de ese nicho. Dame un enfoque para encontrar y elegir mi nicho ideal. Que me ayude a destacar enfocándome en un mercado específico. Práctico y aplicable.",
     en:"Act as a strategy consultant. I want to focus my business [BUSINESS/IDEA] on a specific niche instead of trying to sell to everyone. Help me: how to identify a profitable, underserved niche, how to evaluate if it has potential, the advantages of specializing, and how to position myself as the specialist of that niche. Give me an approach to find and choose my ideal niche. To help me stand out by focusing on a specific market. Practical and applicable."}},

{ cat:"business", t:{es:"Mejora la experiencia de tus clientes", en:"Improve your customers' experience"},
  p:{es:"Eres consultor de experiencia de cliente. Quiero que los clientes de mi negocio [NEGOCIO] tengan una experiencia tan buena que vuelvan y me recomienden. Ayúdame: cómo mejorar cada momento del cliente (antes, durante y después de la compra), qué detalles marcan la diferencia, cómo superar sus expectativas, y cómo convertir clientes satisfechos en fieles. Dame ideas concretas y aplicables. Que mejore la experiencia y aumente la lealtad y las recomendaciones. Práctico para un negocio pequeño.",
     en:"You're a customer experience consultant. I want my business's customers [BUSINESS] to have such a good experience that they return and recommend me. Help me: how to improve each customer moment (before, during and after the purchase), what details make the difference, how to exceed their expectations, and how to turn satisfied customers into loyal ones. Give me concrete, applicable ideas. To improve the experience and increase loyalty and recommendations. Practical for a small business."}},

{ cat:"business", t:{es:"Crea ofertas que se vendan solas", en:"Create offers that sell themselves"},
  p:{es:"Actúa como experto en ofertas. Ayúdame a diseñar ofertas irresistibles para [PRODUCTO/SERVICIO] que sean tan atractivas que se vendan casi solas. Enséñame: cómo aumentar el valor percibido, qué elementos incluir (bonos, garantía, facilidad de pago), cómo presentar el precio, y cómo hacer que comprar sea una decisión obvia. Dame ejemplos de cómo estructurar una oferta ganadora. Que mis ofertas hagan que el cliente sienta que no comprar sería un error. Práctico y aplicable.",
     en:"Act as an offers expert. Help me design irresistible offers for [PRODUCT/SERVICE] so attractive they almost sell themselves. Teach me: how to increase perceived value, what elements to include (bonuses, guarantee, easy payment), how to present the price, and how to make buying an obvious decision. Give me examples of how to structure a winning offer. So my offers make the customer feel that not buying would be a mistake. Practical and applicable."}},

{ cat:"business", t:{es:"Organiza y haz crecer tu negocio", en:"Organize and grow your business"},
  p:{es:"Eres consultor de negocios. Mi negocio [NEGOCIO] funciona pero de forma desorganizada y siento que podría crecer más si lo ordenara. Ayúdame: cómo organizar las áreas clave (ventas, clientes, finanzas, operación), qué sistemas simples implementar, qué priorizar para crecer, y cómo pasar de la informalidad a algo más estructurado sin complicarme. Dame un plan claro para organizar mi negocio y prepararlo para crecer. Práctico y realista para un negocio pequeño.",
     en:"You're a business consultant. My business [BUSINESS] works but in a disorganized way and I feel it could grow more if I organized it. Help me: how to organize the key areas (sales, customers, finances, operations), what simple systems to implement, what to prioritize to grow, and how to go from informality to something more structured without complicating things. Give me a clear plan to organize my business and prepare it to grow. Practical and realistic for a small business."}},

{ cat:"business", t:{es:"Convierte tu pasión en un negocio", en:"Turn your passion into a business"},
  p:{es:"Actúa como consultor de emprendimiento. Me apasiona [TU PASIÓN/HABILIDAD] y quiero convertirlo en un negocio rentable. Ayúdame: cómo encontrar la forma de monetizar lo que me apasiona, qué productos o servicios podría ofrecer, a quién venderle, cómo empezar con poco, y cómo equilibrar la pasión con la rentabilidad. Dame ideas concretas y un primer plan para convertir lo que amo hacer en un negocio que genere ingresos. Realista y motivador.",
     en:"Act as an entrepreneurship consultant. I'm passionate about [YOUR PASSION/SKILL] and want to turn it into a profitable business. Help me: how to find a way to monetize what I'm passionate about, what products or services I could offer, who to sell to, how to start small, and how to balance passion with profitability. Give me concrete ideas and a first plan to turn what I love doing into a business that generates income. Realistic and motivating."}},

{ cat:"business", t:{es:"Supera un momento difícil del negocio", en:"Overcome a tough business moment"},
  p:{es:"Eres asesor de negocios. Mi negocio [NEGOCIO] está pasando por un momento difícil: [DESCRIBE LA SITUACIÓN: bajas ventas, mucha competencia, etc.]. Ayúdame a salir adelante: cómo analizar qué está pasando, qué acciones tomar para mejorar la situación, cómo priorizar lo más urgente, y cómo recuperar el rumbo. Dame un enfoque claro y acciones concretas para enfrentar este momento difícil y reactivar mi negocio. Práctico y realista, con cabeza fría.",
     en:"You're a business advisor. My business [BUSINESS] is going through a tough moment: [DESCRIBE THE SITUATION: low sales, heavy competition, etc.]. Help me get through it: how to analyze what's happening, what actions to take to improve the situation, how to prioritize the most urgent, and how to recover direction. Give me a clear approach and concrete actions to face this tough moment and reactivate my business. Practical and realistic, with a cool head."}},

// ---------- DISEÑO (+10) ----------
{ cat:"design", t:{es:"Genera variaciones de tu logo con IA", en:"Generate logo variations with AI"},
  p:{es:"Crea 3 prompts en inglés para generar con IA distintas variaciones de logo para [MARCA] del sector [SECTOR]. Cada prompt para un estilo diferente (minimalista, moderno, con símbolo, etc.), describiendo los elementos, colores y la sensación a transmitir. Que me den opciones variadas para elegir la dirección de mi logo. Incluye los parámetros recomendados para cada uno. Que pueda probar diferentes estilos y quedarme con el mejor.",
     en:"Create 3 English prompts to generate different logo variations with AI for [BRAND] in the [SECTOR] sector. Each prompt for a different style (minimalist, modern, with a symbol, etc.), describing the elements, colors and feeling to convey. They should give me varied options to choose my logo's direction. Include the recommended parameters for each. So I can try different styles and keep the best."}},

{ cat:"design", t:{es:"Diseño de post para promocionar oferta", en:"Post design to promote an offer"},
  p:{es:"Actúa como diseñador gráfico. Describe el diseño de una publicación para [RED SOCIAL] que promocione una oferta de [PRODUCTO]. Indica: cómo destacar el descuento o la oferta, dónde va el texto y la imagen, qué colores usar para llamar la atención, cómo mostrar el precio, y la llamada a la acción. Que sea llamativo, comunique la oferta de un vistazo y motive a comprar. Con una descripción clara para crearlo. Que detenga el scroll y genere ventas.",
     en:"Act as a graphic designer. Describe the design of a post for [SOCIAL NETWORK] that promotes an offer of [PRODUCT]. Indicate: how to highlight the discount or offer, where the text and image go, what colors to use to grab attention, how to show the price, and the call to action. It should be eye-catching, communicate the offer at a glance and motivate buying. With a clear description to create it. To stop the scroll and generate sales."}},

{ cat:"design", t:{es:"Imagen de fondo para tus diseños con IA", en:"Background image for your designs with AI"},
  p:{es:"Crea un prompt en inglés para generar con IA una imagen de fondo o textura para usar en mis diseños de [USO: publicaciones, presentaciones, banners] de [MARCA/NICHO]. Describe: el estilo, los colores acordes a mi marca, el ambiente, y que tenga espacio para poner texto encima. Que sea versátil y profesional para usar como base en varios diseños. Incluye los parámetros recomendados para buena calidad. Que me dé un fondo atractivo y reutilizable.",
     en:"Create an English prompt to generate a background image or texture with AI to use in my designs for [USE: posts, presentations, banners] of [BRAND/NICHE]. Describe: the style, brand-appropriate colors, the ambiance, and that it has space to put text on top. It should be versatile and professional to use as a base in several designs. Include the recommended parameters for good quality. To give me an attractive, reusable background."}},

{ cat:"design", t:{es:"Diseña la imagen de tu producto digital", en:"Design your digital product's image"},
  p:{es:"Crea un prompt en inglés para generar con IA una imagen atractiva que represente mi producto digital [PRODUCTO: curso, ebook, plantillas, etc.]. Como es digital, ayúdame a mostrarlo de forma visual y tangible. Describe: cómo representarlo (en una pantalla, como un paquete, etc.), el estilo, los colores de mi marca, y la sensación de valor que debe transmitir. Que se vea profesional y deseable para promocionarlo. Con parámetros recomendados para alta calidad.",
     en:"Create an English prompt to generate an attractive image with AI that represents my digital product [PRODUCT: course, ebook, templates, etc.]. Since it's digital, help me show it visually and tangibly. Describe: how to represent it (on a screen, as a package, etc.), the style, my brand colors, and the sense of value it should convey. It should look professional and desirable to promote it. With recommended parameters for high quality."}},

{ cat:"design", t:{es:"Crea una guía de estilo de marca", en:"Create a brand style guide"},
  p:{es:"Actúa como diseñador de marca. Ayúdame a crear una guía de estilo simple para mantener mi marca [MARCA] visualmente coherente. Dame: la paleta de colores con sus códigos y cuándo usar cada uno, las tipografías y su uso, el estilo de las imágenes y gráficos, cómo usar el logo, y las reglas básicas a seguir. Que me sirva para que todo lo que cree (publicaciones, materiales) se vea consistente y profesional. Práctica y fácil de seguir, aunque no sea diseñador experto.",
     en:"Act as a brand designer. Help me create a simple style guide to keep my brand [BRAND] visually coherent. Give me: the color palette with its codes and when to use each, the fonts and their use, the style of images and graphics, how to use the logo, and the basic rules to follow. So it helps everything I create (posts, materials) look consistent and professional. Practical and easy to follow, even if I'm not an expert designer."}},

{ cat:"design", t:{es:"Diseño de miniatura para video", en:"Video thumbnail design"},
  p:{es:"Actúa como experto en miniaturas. Para un video sobre [TEMA], describe el diseño de una miniatura (para YouTube u otra plataforma) que genere muchos clics. Indica: qué imagen o expresión usar, el texto corto e impactante, los colores que resalten, la composición, y el elemento que despierte curiosidad. Que se destaque entre otros videos y haga que la gente quiera ver el mío. Con una descripción clara para crearla. Que aumente los clics en mi video.",
     en:"Act as a thumbnail expert. For a video about [TOPIC], describe the design of a thumbnail (for YouTube or another platform) that gets lots of clicks. Indicate: what image or expression to use, the short impactful text, colors that stand out, the composition, and the element that sparks curiosity. It should stand out among other videos and make people want to watch mine. With a clear description to create it. To increase clicks on my video."}},

{ cat:"design", t:{es:"Ilustración con IA para tu marca", en:"Illustration with AI for your brand"},
  p:{es:"Crea un prompt en inglés para generar con IA una ilustración que represente el concepto o valor de [MARCA/NEGOCIO/MENSAJE]. Describe: el estilo de ilustración acorde a mi marca, los elementos y la escena, la paleta de colores, y la emoción o idea a transmitir. Que sea original y conecte con mi público, útil para mi contenido o material de marca. Incluye los parámetros recomendados. Que me dé una ilustración atractiva y alineada con mi marca.",
     en:"Create an English prompt to generate an illustration with AI that represents the concept or value of [BRAND/BUSINESS/MESSAGE]. Describe: the illustration style fitting my brand, the elements and the scene, the color palette, and the emotion or idea to convey. It should be original and connect with my audience, useful for my content or brand material. Include the recommended parameters. To give me an attractive illustration aligned with my brand."}},

{ cat:"design", t:{es:"Diseña una historia destacada de Instagram", en:"Design an Instagram highlight cover"},
  p:{es:"Actúa como diseñador de redes. Ayúdame a diseñar las portadas de las historias destacadas de mi perfil de Instagram de [NICHO/NEGOCIO] para que se vean profesionales y coherentes. Dame: el estilo a usar, la paleta de colores, qué iconos o elementos usar, cómo nombrar cada destacada, y cómo mantener todas consistentes entre sí. Que hagan que mi perfil se vea ordenado y profesional. Con una descripción clara para crearlas. Que mejoren la imagen de mi perfil.",
     en:"Act as a social designer. Help me design the highlight covers of my Instagram profile for [NICHE/BUSINESS] so they look professional and coherent. Give me: the style to use, the color palette, what icons or elements to use, how to name each highlight, and how to keep them all consistent. They should make my profile look organized and professional. With a clear description to create them. To improve my profile's image."}},

{ cat:"design", t:{es:"Crea una imagen llamativa para anuncio", en:"Create an eye-catching ad image"},
  p:{es:"Crea un prompt en inglés para generar con IA una imagen llamativa para un anuncio de [PRODUCTO] dirigido a [PÚBLICO]. Describe: el estilo visual que detenga el scroll, el ambiente, los colores que llamen la atención, los elementos a incluir, y el espacio para el texto del anuncio. Que sea atractiva, profesional y capte la atención en redes. Incluye los parámetros recomendados para alta calidad. Que mi anuncio destaque visualmente y genere clics.",
     en:"Create an English prompt to generate an eye-catching image with AI for an ad of [PRODUCT] aimed at [AUDIENCE]. Describe: the scroll-stopping visual style, the ambiance, attention-grabbing colors, the elements to include, and space for the ad text. It should be attractive, professional and grab attention on social media. Include the recommended parameters for high quality. So my ad stands out visually and generates clicks."}},

{ cat:"design", t:{es:"Define el estilo visual de tu contenido", en:"Define your content's visual style"},
  p:{es:"Actúa como director de arte. Ayúdame a definir un estilo visual consistente para todo mi contenido de [NICHO/NEGOCIO] en redes, para que mi marca se vea reconocible. Dame: la paleta de colores, las tipografías, el estilo de imágenes y gráficos, los elementos visuales que me identifiquen, y cómo aplicarlo de forma consistente en cada publicación. Que mi contenido sea reconocible de un vistazo y se vea profesional. Práctico y fácil de mantener.",
     en:"Act as an art director. Help me define a consistent visual style for all my [NICHE/BUSINESS] content on social media, so my brand looks recognizable. Give me: the color palette, the fonts, the style of images and graphics, the visual elements that identify me, and how to apply it consistently in each post. So my content is recognizable at a glance and looks professional. Practical and easy to maintain."}},

// ---------- PRODUCTIVIDAD (+10) ----------
{ cat:"productivity", t:{es:"Organiza tus proyectos pendientes", en:"Organize your pending projects"},
  p:{es:"Actúa como experto en gestión. Tengo varios proyectos pendientes y no sé cómo organizarlos. Estos son: [LISTA TUS PROYECTOS]. Ayúdame a organizarlos: cómo priorizarlos según importancia y urgencia, cómo dividir cada uno en pasos, en qué orden abordarlos, y cómo avanzar sin sentirme abrumado por tener tantos. Dame un plan claro para organizar y avanzar en mis proyectos de forma ordenada. Práctico y aplicable a mi situación.",
     en:"Act as a management expert. I have several pending projects and don't know how to organize them. These are: [LIST YOUR PROJECTS]. Help me organize them: how to prioritize them by importance and urgency, how to break each into steps, in what order to tackle them, and how to make progress without feeling overwhelmed by having so many. Give me a clear plan to organize and advance my projects in an orderly way. Practical and applicable to my situation."}},

{ cat:"productivity", t:{es:"Crea una rutina de trabajo productiva", en:"Create a productive work routine"},
  p:{es:"Eres coach de productividad. Ayúdame a diseñar una rutina de trabajo diaria que me haga más productivo. Mi trabajo es [TIPO DE TRABAJO] y dispongo de [HORARIO/TIEMPO]. Incluye: cómo organizar mi día por bloques, cuándo hacer las tareas más importantes, cuándo descansar, cómo manejar las interrupciones, y cómo terminar el día sintiendo que avancé. Realista y sostenible, adaptada a mi tipo de trabajo. Que me ayude a rendir más sin agotarme.",
     en:"You're a productivity coach. Help me design a daily work routine that makes me more productive. My work is [TYPE OF WORK] and I have [SCHEDULE/TIME]. Include: how to organize my day by blocks, when to do the most important tasks, when to rest, how to handle interruptions, and how to end the day feeling I made progress. Realistic and sustainable, adapted to my type of work. To help me perform more without burning out."}},

{ cat:"productivity", t:{es:"Escribe un mensaje difícil", en:"Write a difficult message"},
  p:{es:"Actúa como experto en comunicación. Tengo que escribir un mensaje delicado: [DESCRIBE LA SITUACIÓN: dar una mala noticia, poner un límite, reclamar algo, etc.]. Ayúdame a redactarlo de la mejor forma: que sea claro pero respetuoso, firme pero amable, que logre mi objetivo sin dañar la relación, y con el tono adecuado. Dame el mensaje listo para enviar. Que maneje bien una situación delicada y comunique lo que necesito de forma profesional y cuidadosa.",
     en:"Act as a communication expert. I have to write a delicate message: [DESCRIBE THE SITUATION: deliver bad news, set a boundary, complain about something, etc.]. Help me write it in the best way: clear but respectful, firm but kind, achieving my goal without damaging the relationship, and with the right tone. Give me the message ready to send. To handle a delicate situation well and communicate what I need professionally and carefully."}},

{ cat:"productivity", t:{es:"Mejora tu concentración", en:"Improve your concentration"},
  p:{es:"Eres coach de enfoque. Me cuesta concentrarme cuando trabajo y me distraigo con facilidad. Dame estrategias prácticas para mejorar mi concentración: cómo preparar mi entorno, técnicas para enfocarme por periodos, cómo manejar las distracciones (celular, ruido, pensamientos), cómo entrenar mi atención, y cómo crear momentos de trabajo profundo. Aplicables a mi día a día. Que me ayuden a concentrarme mejor y avanzar más rápido en mi trabajo. Prácticas y realistas.",
     en:"You're a focus coach. I struggle to concentrate when working and get distracted easily. Give me practical strategies to improve my concentration: how to prepare my environment, techniques to focus for periods, how to handle distractions (phone, noise, thoughts), how to train my attention, and how to create deep-work moments. Applicable to my daily life. To help me concentrate better and advance faster in my work. Practical and realistic."}},

{ cat:"productivity", t:{es:"Convierte una meta grande en pasos", en:"Turn a big goal into steps"},
  p:{es:"Actúa como experto en logro de metas. Tengo una meta grande: [DESCRIBE TU META]. Me abruma porque es muy grande. Ayúdame a dividirla en pasos manejables: las etapas para llegar a ella, las acciones concretas de cada etapa, en qué orden hacerlas, cómo medir mi avance, y cómo mantenerme motivado en el camino. Dame un plan claro que convierta esa meta grande en pasos pequeños que pueda ir logrando. Realista y motivador.",
     en:"Act as a goal-achievement expert. I have a big goal: [DESCRIBE YOUR GOAL]. It overwhelms me because it's so big. Help me break it into manageable steps: the stages to reach it, the concrete actions of each stage, in what order to do them, how to measure my progress, and how to stay motivated along the way. Give me a clear plan that turns that big goal into small steps I can achieve. Realistic and motivating."}},

{ cat:"productivity", t:{es:"Aprovecha mejor tu tiempo libre", en:"Make better use of your free time"},
  p:{es:"Eres coach de bienestar y productividad. Quiero aprovechar mejor mi tiempo libre en vez de perderlo en cosas que no me aportan. Ayúdame: cómo identificar en qué se me va el tiempo libre, cómo equilibrar descanso, crecimiento personal y disfrute, qué actividades me sumarían, y cómo organizarlo sin que se sienta como otra obligación. Dame ideas y un enfoque para que mi tiempo libre me recargue y me aporte de verdad. Práctico y equilibrado.",
     en:"You're a wellness and productivity coach. I want to make better use of my free time instead of wasting it on things that don't add value. Help me: how to identify where my free time goes, how to balance rest, personal growth and enjoyment, what activities would add to me, and how to organize it without it feeling like another obligation. Give me ideas and an approach so my free time recharges me and truly adds value. Practical and balanced."}},

{ cat:"productivity", t:{es:"Crea un sistema para tus finanzas personales", en:"Create a system for your personal finances"},
  p:{es:"Actúa como asesor de finanzas personales. Quiero organizar mejor mi dinero personal. Ayúdame a crear un sistema simple: cómo llevar el control de mis ingresos y gastos, cómo presupuestar, cómo separar para ahorrar, cómo identificar gastos innecesarios, y qué hábitos financieros adoptar. Sin cosas complicadas, práctico para el día a día. Que me ayude a tener mis finanzas personales ordenadas, gastar mejor y ahorrar. Realista y fácil de mantener.",
     en:"Act as a personal finance advisor. I want to better organize my personal money. Help me create a simple system: how to track my income and expenses, how to budget, how to set aside savings, how to identify unnecessary expenses, and what financial habits to adopt. Without complicated things, practical for daily life. To help me have my personal finances organized, spend better and save. Realistic and easy to maintain."}},

{ cat:"productivity", t:{es:"Maneja varias responsabilidades a la vez", en:"Juggle multiple responsibilities"},
  p:{es:"Eres coach de productividad. Tengo varias responsabilidades a la vez ([DESCRIBE: trabajo, familia, negocio, estudio, etc.]) y siento que no doy abasto. Ayúdame a manejarlas mejor: cómo organizar mi tiempo entre todas, cómo priorizar, cómo no descuidar lo importante, cómo poner límites, y cómo evitar agotarme. Dame un enfoque y estrategias prácticas para equilibrar mis responsabilidades sin sentir que vivo corriendo. Realista y aplicable a mi situación.",
     en:"You're a productivity coach. I have several responsibilities at once ([DESCRIBE: work, family, business, study, etc.]) and feel I can't keep up. Help me handle them better: how to organize my time among them all, how to prioritize, how to not neglect what's important, how to set limits, and how to avoid burning out. Give me an approach and practical strategies to balance my responsibilities without feeling like I live running. Realistic and applicable to my situation."}},

{ cat:"productivity", t:{es:"Deja de posponer y empieza a actuar", en:"Stop postponing and start acting"},
  p:{es:"Actúa como coach de acción. Tiendo a posponer las cosas y luego me estreso por no haber avanzado. Ayúdame a pasar de la intención a la acción: por qué pospongo, cómo vencer la pereza inicial, cómo empezar aunque no tenga ganas, cómo dividir las tareas para que sean menos pesadas, y cómo crear el impulso para actuar. Dame estrategias prácticas para dejar de posponer y empezar a hacer las cosas. Aplicables hoy mismo, sin fórmulas complicadas.",
     en:"Act as an action coach. I tend to postpone things and then stress about not having made progress. Help me go from intention to action: why I postpone, how to overcome the initial laziness, how to start even when I don't feel like it, how to break tasks so they're less heavy, and how to create the momentum to act. Give me practical strategies to stop postponing and start doing things. Applicable today, without complicated formulas."}},

{ cat:"productivity", t:{es:"Simplifica tu vida y enfócate en lo importante", en:"Simplify your life and focus on what matters"},
  p:{es:"Eres coach de vida y productividad. Siento que tengo demasiadas cosas y me disperso. Quiero simplificar y enfocarme en lo que de verdad importa. Ayúdame: cómo identificar lo esencial vs lo que solo me ocupa, qué puedo eliminar o reducir, cómo decir que no a lo que no aporta, y cómo enfocar mi energía en lo importante. Dame un enfoque para simplificar mi vida y mis prioridades. Que me dé claridad, menos estrés y más enfoque en lo que vale la pena.",
     en:"You're a life and productivity coach. I feel I have too many things and get scattered. I want to simplify and focus on what really matters. Help me: how to identify the essential vs what just occupies me, what I can eliminate or reduce, how to say no to what doesn't add value, and how to focus my energy on what's important. Give me an approach to simplify my life and priorities. To give me clarity, less stress and more focus on what's worth it."}},

// ---------- E-COMMERCE (+10) ----------
{ cat:"ecommerce", t:{es:"Optimiza tus fichas de producto", en:"Optimize your product pages"},
  p:{es:"Actúa como experto en e-commerce. Quiero mejorar las fichas de producto de mi tienda de [PRODUCTOS] para que vendan más. Dame una guía: cómo escribir títulos que vendan, cómo hacer descripciones persuasivas enfocadas en beneficios, qué información incluir, cómo usar las imágenes, cómo responder las dudas antes de que surjan, y qué elementos aumentan la conversión. Práctica y aplicable, para que mis fichas conviertan más visitantes en compradores.",
     en:"Act as an e-commerce expert. I want to improve my [PRODUCTS] store's product pages so they sell more. Give me a guide: how to write titles that sell, how to make persuasive descriptions focused on benefits, what information to include, how to use images, how to answer doubts before they arise, and what elements increase conversion. Practical and applicable, so my pages convert more visitors into buyers."}},

{ cat:"ecommerce", t:{es:"Crea ofertas para tu tienda", en:"Create offers for your store"},
  p:{es:"Eres experto en promociones de e-commerce. Ayúdame a crear ofertas atractivas para mi tienda de [PRODUCTOS] que aumenten las ventas. Dame distintos tipos de ofertas que funcionan (descuentos, 2x1, combos, envío gratis, regalo por compra), cuándo usar cada una, cómo presentarlas para que sean irresistibles, y cómo crear urgencia. Que me ayuden a vender más sin perder rentabilidad. Con ejemplos aplicados a mi tienda. Prácticas y efectivas.",
     en:"You're an e-commerce promotions expert. Help me create attractive offers for my [PRODUCTS] store that increase sales. Give me different types of offers that work (discounts, BOGO, bundles, free shipping, gift with purchase), when to use each, how to present them so they're irresistible, and how to create urgency. They should help me sell more without losing profitability. With examples applied to my store. Practical and effective."}},

{ cat:"ecommerce", t:{es:"Estrategia para vender en redes sociales", en:"Strategy to sell on social media"},
  p:{es:"Actúa como experto en social commerce. Quiero vender los productos de mi tienda de [PRODUCTOS] a través de redes sociales. Dame una estrategia: qué contenido publicar para mostrar y vender mis productos, cómo presentarlos de forma atractiva, cómo usar las historias y Reels para vender, cómo convertir seguidores en compradores, y cómo guiar de la red social a la compra. Práctica y aplicable, para que las redes se conviertan en un canal de ventas para mi tienda.",
     en:"Act as a social commerce expert. I want to sell my [PRODUCTS] store products through social media. Give me a strategy: what content to post to show and sell my products, how to present them attractively, how to use stories and Reels to sell, how to convert followers into buyers, and how to guide from social media to the purchase. Practical and applicable, so social media becomes a sales channel for my store."}},

{ cat:"ecommerce", t:{es:"Descripción que vende para Marketplace", en:"Selling description for Marketplace"},
  p:{es:"Actúa como vendedor experto en Marketplace. Escribe una descripción persuasiva para vender [PRODUCTO] en Facebook Marketplace o plataformas similares. Que tenga un título que llame la atención, destaque los beneficios y características importantes, genere confianza, incluya los detalles que el comprador quiere saber, y termine invitando a contactar. Optimizada para generar mensajes de interesados y cerrar la venta. Clara, atractiva y directa. Que haga que la gente quiera comprar mi producto.",
     en:"Act as an expert Marketplace seller. Write a persuasive description to sell [PRODUCT] on Facebook Marketplace or similar platforms. It should have an attention-grabbing title, highlight the important benefits and features, build trust, include the details the buyer wants to know, and end by inviting contact. Optimized to generate messages from interested buyers and close the sale. Clear, attractive and direct. To make people want to buy my product."}},

{ cat:"ecommerce", t:{es:"Convierte visitantes en compradores", en:"Turn visitors into buyers"},
  p:{es:"Eres consultor de e-commerce. Mi tienda de [PRODUCTOS] recibe visitas pero pocos compran. Ayúdame a aumentar la conversión: qué puede estar frenando la compra, cómo generar más confianza, cómo mejorar la presentación de productos y precios, cómo reducir las dudas, cómo crear urgencia, y cómo facilitar el proceso de compra. Dame acciones concretas para convertir más de mis visitantes en compradores. Práctico y aplicable para vender más con el tráfico que ya tengo.",
     en:"You're an e-commerce consultant. My [PRODUCTS] store gets visits but few buy. Help me increase conversion: what might be stopping the purchase, how to build more trust, how to improve the presentation of products and prices, how to reduce doubts, how to create urgency, and how to ease the buying process. Give me concrete actions to convert more of my visitors into buyers. Practical and applicable to sell more with the traffic I already have."}},

{ cat:"ecommerce", t:{es:"Atrae clientes a tu tienda online", en:"Attract customers to your online store"},
  p:{es:"Actúa como experto en marketing de e-commerce. Tengo una tienda online de [PRODUCTOS] y necesito atraer más clientes. Dame estrategias para llevar tráfico a mi tienda: contenido que atraiga, cómo usar redes sociales, cómo aprovechar el boca a boca, alianzas, y otras formas de bajo costo de conseguir clientes. Prioriza las que dan mejor resultado para una tienda pequeña que empieza. Que aumenten las visitas y clientes de mi tienda. Prácticas y aplicables sin gran presupuesto.",
     en:"Act as an e-commerce marketing expert. I have an online store of [PRODUCTS] and need to attract more customers. Give me strategies to bring traffic to my store: content that attracts, how to use social media, how to leverage word of mouth, partnerships, and other low-cost ways to get customers. Prioritize those that give the best results for a small store starting out. To increase my store's visits and customers. Practical and applicable without a big budget."}},

{ cat:"ecommerce", t:{es:"Vende productos de temporada", en:"Sell seasonal products"},
  p:{es:"Eres experto en e-commerce estacional. Vendo [PRODUCTOS DE TEMPORADA] y quiero aprovechar al máximo la temporada para vender. Dame una estrategia: cómo prepararme antes de la temporada, cómo generar expectativa, qué ofertas y promociones hacer durante la temporada alta, cómo crear urgencia, y cómo maximizar las ventas mientras dura la demanda. Práctica y aplicable, para aprovechar al máximo la temporada y vender la mayor cantidad posible de mis productos.",
     en:"You're a seasonal e-commerce expert. I sell [SEASONAL PRODUCTS] and want to make the most of the season to sell. Give me a strategy: how to prepare before the season, how to build anticipation, what offers and promotions to do during the high season, how to create urgency, and how to maximize sales while the demand lasts. Practical and applicable, to make the most of the season and sell as many of my products as possible."}},

{ cat:"ecommerce", t:{es:"Mejora las fotos de tus productos", en:"Improve your product photos"},
  p:{es:"Actúa como experto en fotografía de producto para e-commerce. Quiero mejorar las fotos de mis productos de [PRODUCTOS] para que se vean más atractivas y vendan más, aunque las tome yo mismo. Dame consejos prácticos: cómo iluminar bien, qué fondos usar, qué ángulos funcionan, cómo mostrar el producto en uso, cómo destacar los detalles, y errores a evitar. Aplicables con recursos básicos (incluso con el celular). Que mis fotos se vean profesionales y ayuden a vender.",
     en:"Act as a product photography expert for e-commerce. I want to improve my product photos for [PRODUCTS] so they look more attractive and sell more, even if I take them myself. Give me practical tips: how to light well, what backgrounds to use, what angles work, how to show the product in use, how to highlight details, and mistakes to avoid. Applicable with basic resources (even with a phone). So my photos look professional and help sell."}},

{ cat:"ecommerce", t:{es:"Recupera clientes que no terminaron la compra", en:"Recover customers who didn't finish buying"},
  p:{es:"Eres experto en conversión de e-commerce. Algunos clientes empiezan a comprar en mi tienda de [PRODUCTOS] pero no terminan. Dame una estrategia para recuperarlos: por qué pueden abandonar la compra, cómo hacer seguimiento para recuperarlos, qué mensajes enviarles, qué incentivo ofrecer para que completen la compra, y cómo facilitarles terminar. Con mensajes listos para usar. Que recuperen ventas que estaban a punto de concretarse. Práctico y aplicable.",
     en:"You're an e-commerce conversion expert. Some customers start buying in my [PRODUCTS] store but don't finish. Give me a strategy to recover them: why they may abandon the purchase, how to follow up to recover them, what messages to send them, what incentive to offer so they complete the purchase, and how to make finishing easier. With ready-to-use messages. To recover sales that were about to close. Practical and applicable."}},

{ cat:"ecommerce", t:{es:"Crea confianza para vender más", en:"Build trust to sell more"},
  p:{es:"Actúa como consultor de e-commerce. Quiero que los clientes confíen más en mi tienda de [PRODUCTOS] y compren sin miedo. Dame estrategias para generar confianza: qué mostrar para verse confiable y profesional, cómo manejar las dudas sobre pagos, envíos y devoluciones, cómo usar reseñas y garantías, cómo dar buena atención, y cómo transmitir que soy un negocio serio. Práctico y aplicable, para que los clientes se sientan seguros de comprar en mi tienda y vendas más.",
     en:"Act as an e-commerce consultant. I want customers to trust my [PRODUCTS] store more and buy without fear. Give me strategies to build trust: what to show to look reliable and professional, how to handle doubts about payments, shipping and returns, how to use reviews and guarantees, how to give good service, and how to convey that I'm a serious business. Practical and applicable, so customers feel safe buying in my store and you sell more."}},

// ---------- EMAIL MARKETING (+10) ----------
{ cat:"email", t:{es:"Secuencia de correos para un lanzamiento", en:"Email sequence for a launch"},
  p:{es:"Actúa como estratega de email marketing. Diseña una secuencia de correos para el lanzamiento de [PRODUCTO] a mi lista. Dame los correos necesarios (de aviso previo, apertura, valor, prueba social, urgencia y cierre), con el objetivo de cada uno, el asunto y los puntos clave del contenido. Que lleven a mi audiencia desde el anuncio hasta la compra de forma estratégica. Que sea una secuencia de lanzamiento que genere ventas. Práctica y lista para adaptar.",
     en:"Act as an email marketing strategist. Design an email sequence for the launch of [PRODUCT] to my list. Give me the necessary emails (pre-announcement, opening, value, social proof, urgency and closing), with the goal of each, the subject and the key content points. They should lead my audience from the announcement to the purchase strategically. It should be a launch sequence that generates sales. Practical and ready to adapt."}},

{ cat:"email", t:{es:"Correo de bienvenida que engancha", en:"Welcome email that hooks"},
  p:{es:"Eres copywriter de email. Escribe un correo de bienvenida para nuevos suscriptores de [NEGOCIO/NICHO] que cause una excelente primera impresión. Que dé la bienvenida de forma cálida, entregue valor de inmediato, cuente brevemente qué pueden esperar, conecte a nivel humano, y deje ganas de abrir el siguiente correo. Con el asunto incluido. Que inicie la relación con buen pie y enganche al nuevo suscriptor. Cercano y profesional, listo para usar.",
     en:"You're an email copywriter. Write a welcome email for new subscribers of [BUSINESS/NICHE] that makes an excellent first impression. It should welcome warmly, deliver value immediately, briefly tell them what to expect, connect on a human level, and leave them wanting to open the next email. With the subject included. To start the relationship on the right foot and hook the new subscriber. Warm and professional, ready to use."}},

{ cat:"email", t:{es:"Correo que cuenta una historia y vende", en:"Email that tells a story and sells"},
  p:{es:"Actúa como copywriter de email con storytelling. Escribe un correo que cuente una historia atractiva relacionada con [TEMA/PROBLEMA] y de forma natural lleve a presentar [PRODUCTO]. Que la historia conecte emocionalmente, mantenga el interés, se relacione con lo que vendo, y termine invitando a comprar sin que se sienta forzado. Con el asunto incluido. Que combine conexión emocional con persuasión para vender. Auténtico y cautivador, listo para usar.",
     en:"Act as a storytelling email copywriter. Write an email that tells an engaging story related to [TOPIC/PROBLEM] and naturally leads to presenting [PRODUCT]. The story should connect emotionally, keep interest, relate to what I sell, and end by inviting purchase without feeling forced. With the subject included. To combine emotional connection with persuasion to sell. Authentic and captivating, ready to use."}},

{ cat:"email", t:{es:"Asuntos de correo irresistibles", en:"Irresistible email subjects"},
  p:{es:"Eres experto en email marketing. Dame 15 líneas de asunto irresistibles para correos sobre [TEMA/OFERTA] dirigidos a [PÚBLICO]. Que logren altas tasas de apertura usando distintas técnicas: curiosidad, beneficio, urgencia, pregunta, número, personalización. Cortas, potentes y específicas. Marca las 3 con mayor probabilidad de apertura y explica por qué funcionan. Que hagan que mi correo destaque y la gente quiera abrirlo. Listas para usar y adaptar.",
     en:"You're an email marketing expert. Give me 15 irresistible subject lines for emails about [TOPIC/OFFER] aimed at [AUDIENCE]. They should achieve high open rates using different techniques: curiosity, benefit, urgency, question, number, personalization. Short, powerful and specific. Mark the 3 with the highest open probability and explain why they work. So my email stands out and people want to open it. Ready to use and adapt."}},

{ cat:"email", t:{es:"Correo para reconectar con tu lista", en:"Email to reconnect with your list"},
  p:{es:"Actúa como experto en email marketing. Hace tiempo que no le escribo a mi lista de [NICHO] y quiero reconectar. Escribe un correo que retome el contacto de forma cercana y genuina: que reconozca la ausencia con honestidad, aporte valor, recuerde quién soy y qué ofrezco, y reactive el interés de mis suscriptores. Con el asunto incluido. Que reconecte con mi audiencia y reactive la relación. Cálido y auténtico, listo para enviar.",
     en:"Act as an email marketing expert. It's been a while since I wrote to my [NICHE] list and I want to reconnect. Write an email that resumes contact warmly and genuinely: acknowledging the absence honestly, providing value, reminding who I am and what I offer, and reactivating my subscribers' interest. With the subject included. To reconnect with my audience and reactivate the relationship. Warm and authentic, ready to send."}},

{ cat:"email", t:{es:"Correo educativo que prepara la venta", en:"Educational email that sets up the sale"},
  p:{es:"Eres estratega de email marketing. Escribe un correo educativo para mi lista de [NICHO] que enseñe algo útil sobre [TEMA] y, sin vender directamente, prepare a mis suscriptores para una futura oferta de [PRODUCTO]. Que aporte valor real, demuestre mi experiencia, genere confianza, y conecte sutilmente con cómo mi producto puede ayudar. Con el asunto incluido. Que entregue valor mientras prepara el terreno para vender después. Valioso y estratégico, listo para usar.",
     en:"You're an email marketing strategist. Write an educational email for my [NICHE] list that teaches something useful about [TOPIC] and, without selling directly, prepares my subscribers for a future offer of [PRODUCT]. It should provide real value, demonstrate my expertise, build trust, and subtly connect with how my product can help. With the subject included. To deliver value while setting the stage to sell later. Valuable and strategic, ready to use."}},

{ cat:"email", t:{es:"Correo con oferta de último momento", en:"Last-minute offer email"},
  p:{es:"Actúa como experto en email de ventas. Escribe un correo de 'último momento' para una oferta de [PRODUCTO] que está por terminar. Que genere urgencia real, recuerde el beneficio principal y lo que se pierde si no actúa ya, y motive a comprar antes de que se acabe. Con un asunto que invite a abrir de inmediato. Que cree esa urgencia final para impulsar a los indecisos a comprar. Persuasivo y directo, listo para usar.",
     en:"Act as a sales email expert. Write a 'last-minute' email for an offer of [PRODUCT] that's about to end. It should create real urgency, remind of the main benefit and what's lost if they don't act now, and motivate buying before it ends. With a subject that invites opening immediately. To create that final urgency to push the undecided to buy. Persuasive and direct, ready to use."}},

{ cat:"email", t:{es:"Correo de agradecimiento que fideliza", en:"Thank you email that builds loyalty"},
  p:{es:"Eres experto en fidelización por email. Escribe un correo de agradecimiento para enviar después de que un cliente compra [PRODUCTO]. Que agradezca de forma genuina, reafirme que tomó una buena decisión, le ayude a aprovechar al máximo lo que compró, y abra la puerta a seguir en contacto. Con el asunto incluido. Que haga que el cliente se sienta valorado y quiera volver a comprar. Cálido y genuino, listo para usar. Que fortalezca la relación después de la venta.",
     en:"You're an email loyalty expert. Write a thank you email to send after a customer buys [PRODUCT]. It should thank genuinely, reaffirm they made a good decision, help them make the most of what they bought, and open the door to staying in touch. With the subject included. To make the customer feel valued and want to buy again. Warm and genuine, ready to use. To strengthen the relationship after the sale."}},

{ cat:"email", t:{es:"Newsletter con valor para tu audiencia", en:"Newsletter with value for your audience"},
  p:{es:"Actúa como experto en newsletters. Ayúdame a crear una edición de newsletter para mi audiencia de [NICHO]. Dame: un tema interesante y relevante, una estructura que mantenga el interés de principio a fin, contenido de valor que conecte, un toque personal, y una sección que lleve sutilmente hacia lo que ofrezco. Con el asunto incluido. Que aporte valor real y mantenga a mi audiencia enganchada con lo que comparto. Lista para enviar, atractiva y valiosa.",
     en:"Act as a newsletter expert. Help me create a newsletter edition for my [NICHE] audience. Give me: an interesting, relevant topic, a structure that keeps interest from start to finish, valuable content that connects, a personal touch, and a section that subtly leads toward what I offer. With the subject included. To provide real value and keep my audience engaged with what I share. Ready to send, attractive and valuable."}},

{ cat:"email", t:{es:"Correo para promover un descuento", en:"Email to promote a discount"},
  p:{es:"Eres copywriter de email. Escribe un correo para promover un descuento especial en [PRODUCTO] a mi lista. Que comunique la oferta de forma atractiva, destaque el ahorro y el valor, genere urgencia con una fecha límite clara, refuerce el beneficio principal, y motive a aprovechar el descuento ya. Con un asunto que invite a abrir. Que impulse ventas rápido aprovechando el atractivo de un buen descuento. Persuasivo y directo, listo para usar.",
     en:"You're an email copywriter. Write an email to promote a special discount on [PRODUCT] to my list. It should communicate the offer attractively, highlight the savings and value, create urgency with a clear deadline, reinforce the main benefit, and motivate taking advantage of the discount now. With a subject that invites opening. To drive sales fast leveraging the appeal of a good discount. Persuasive and direct, ready to use."}},

];
