// ============================================================
//  ARSENAL IA — BIBLIOTECA DE PROMPTS (parte 14)
//  Rumbo a 50: SEO · Video · Marca personal · Agentes · Educación · Salud
// ============================================================

const PROMPTS_14 = [

// ---------- SEO Y BLOGS (+10) ----------
{ cat:"seo", t:{es:"Estrategia SEO para tu negocio", en:"SEO strategy for your business"},
  p:{es:"Actúa como consultor SEO. Quiero que mi negocio de [SECTOR/TEMA] aparezca en Google cuando la gente busca lo que ofrezco. Dame una estrategia SEO completa pero simple: qué palabras clave apuntar, qué contenido crear, cómo estructurar mi sitio o blog, qué priorizar para empezar a posicionar, y qué resultados esperar con el tiempo. Práctica y aplicable para alguien que no es experto en SEO. Que me dé un plan claro para que me encuentren en Google.",
     en:"Act as an SEO consultant. I want my [SECTOR/TOPIC] business to appear on Google when people search for what I offer. Give me a complete but simple SEO strategy: what keywords to target, what content to create, how to structure my site or blog, what to prioritize to start ranking, and what results to expect over time. Practical and applicable for someone who isn't an SEO expert. To give me a clear plan to be found on Google."}},

{ cat:"seo", t:{es:"Escribe un artículo que posicione", en:"Write an article that ranks"},
  p:{es:"Actúa como redactor SEO experto. Escribe un artículo de blog optimizado sobre [TEMA] para la palabra clave [KEYWORD], dirigido a [PÚBLICO]. Incluye: un título atractivo con la keyword, una introducción que enganche, subtítulos bien organizados, contenido de valor real y completo, la palabra clave usada de forma natural, y una conclusión con llamada a la acción. Que responda mejor que la competencia y tenga potencial de posicionar. Bien estructurado y listo para publicar.",
     en:"Act as an expert SEO writer. Write an optimized blog article about [TOPIC] for the keyword [KEYWORD], aimed at [AUDIENCE]. Include: an attractive title with the keyword, an engaging introduction, well-organized subheadings, real and complete valuable content, the keyword used naturally, and a conclusion with a call to action. It should answer better than the competition and have ranking potential. Well structured and ready to publish."}},

{ cat:"seo", t:{es:"Investiga palabras clave fáciles de posicionar", en:"Research easy-to-rank keywords"},
  p:{es:"Eres experto en SEO. Para mi sitio de [TEMA/NICHO], dame 20 palabras clave que tengan buen potencial pero poca competencia, fáciles de posicionar para un sitio que empieza. Organízalas por subtema, indica la intención de búsqueda de cada grupo, y señala cuáles atacar primero. Adaptadas a búsquedas reales del mercado hispano. Que me sirvan para crear contenido que pueda posicionar pronto sin competir con sitios gigantes. Útiles y accionables.",
     en:"You're an SEO expert. For my [TOPIC/NICHE] site, give me 20 keywords with good potential but low competition, easy to rank for a starting site. Organize them by subtopic, indicate the search intent of each group, and point out which to target first. Adapted to real searches in the relevant market. So they help me create content I can rank soon without competing with giant sites. Useful and actionable."}},

{ cat:"seo", t:{es:"Optimiza tu página para Google", en:"Optimize your page for Google"},
  p:{es:"Actúa como consultor SEO. Tengo una página sobre [TEMA] y quiero optimizarla para posicionar mejor en Google para [KEYWORD]. Dame una lista de optimizaciones que suelen funcionar: cómo mejorar el título y la meta descripción, cómo estructurar el contenido, dónde usar la palabra clave, qué agregar para que sea más completa, y qué le falta frente a los que están arriba. Priorizadas por impacto. Prácticas y aplicables para mejorar el posicionamiento de mi página.",
     en:"Act as an SEO consultant. I have a page about [TOPIC] and want to optimize it to rank better on Google for [KEYWORD]. Give me a list of optimizations that usually work: how to improve the title and meta description, how to structure the content, where to use the keyword, what to add to make it more complete, and what it's missing versus those above. Prioritized by impact. Practical and applicable to improve my page's ranking."}},

{ cat:"seo", t:{es:"Ideas de contenido que atraen tráfico", en:"Content ideas that attract traffic"},
  p:{es:"Eres estratega de SEO. Para un blog de [TEMA/NICHO], dame 15 ideas de artículos con buen potencial de atraer tráfico desde Google. Para cada idea: el título optimizado, la palabra clave objetivo, la intención de búsqueda, y por qué le interesaría a [PÚBLICO]. Enfócate en temas que la gente realmente busca y que puedan traer visitas constantes. Ordénalas por potencial de tráfico. Que me den un banco de ideas de contenido para posicionar y atraer visitantes.",
     en:"You're an SEO strategist. For a blog about [TOPIC/NICHE], give me 15 article ideas with good potential to attract traffic from Google. For each idea: the optimized title, the target keyword, the search intent, and why [AUDIENCE] would care. Focus on topics people actually search for and that can bring constant visits. Sort them by traffic potential. To give me a bank of content ideas to rank and attract visitors."}},

{ cat:"seo", t:{es:"Estructura tu artículo para posicionar", en:"Structure your article to rank"},
  p:{es:"Actúa como experto en SEO de contenidos. Dame la estructura completa de un artículo optimizado sobre [TEMA] para la palabra clave [KEYWORD]. Incluye: el título con la keyword, la meta descripción, los subtítulos (H2, H3) organizados lógicamente, qué cubrir en cada sección, dónde colocar la palabra clave de forma natural, y qué incluir para que sea más completo que la competencia. Listo para que solo tenga que redactar siguiendo la estructura. Claro y bien organizado.",
     en:"Act as a content SEO expert. Give me the complete structure of an optimized article about [TOPIC] for the keyword [KEYWORD]. Include: the title with the keyword, the meta description, the subheadings (H2, H3) logically organized, what to cover in each section, where to place the keyword naturally, and what to include to be more complete than the competition. Ready so I just have to write following the structure. Clear and well organized."}},

{ cat:"seo", t:{es:"Títulos optimizados para más clics", en:"Optimized titles for more clicks"},
  p:{es:"Eres experto en SEO y titulares. Para un artículo sobre [TEMA] con la palabra clave [KEYWORD], dame 12 títulos optimizados que combinen SEO con poder de atracción para generar más clics desde Google. Varía los formatos: listas, cómo hacer, preguntas, guías, números. Que incluyan la keyword sin sonar forzados. Marca los 3 con mejor equilibrio entre SEO y atractivo. Que ayuden a que mi artículo reciba más clics en los resultados de búsqueda. Prácticos y efectivos.",
     en:"You're an SEO and headline expert. For an article about [TOPIC] with the keyword [KEYWORD], give me 12 optimized titles that combine SEO with attraction power to generate more clicks from Google. Vary the formats: lists, how-to, questions, guides, numbers. They should include the keyword without sounding forced. Mark the 3 with the best balance between SEO and appeal. To help my article get more clicks in search results. Practical and effective."}},

{ cat:"seo", t:{es:"Responde lo que busca tu público", en:"Answer what your audience searches"},
  p:{es:"Actúa como experto en SEO. Cuando alguien de [PÚBLICO] busca sobre [TEMA] en Google, ¿qué busca realmente y qué espera encontrar? Analiza la intención de búsqueda, qué tipo de contenido deberías crear para satisfacerla mejor que otros, qué preguntas relacionadas responder, y cómo estructurarlo para posicionar. Que me ayude a crear contenido que responda exactamente lo que mi público quiere saber y que Google quiera mostrar. Detallado y práctico.",
     en:"Act as an SEO expert. When someone from [AUDIENCE] searches about [TOPIC] on Google, what are they really looking for and what do they expect to find? Analyze the search intent, what type of content I should create to satisfy it better than others, what related questions to answer, and how to structure it to rank. To help me create content that answers exactly what my audience wants to know and that Google wants to show. Detailed and practical."}},

{ cat:"seo", t:{es:"Plan de contenidos SEO para un mes", en:"SEO content plan for a month"},
  p:{es:"Eres estratega de SEO. Crea un plan de contenidos SEO para un mes para un blog de [TEMA/NICHO]. Dame 8 artículos a publicar, cada uno con: su título optimizado, la palabra clave objetivo, la intención de búsqueda, y de qué tratará. Que estén conectados temáticamente para construir autoridad, e incluyan una mezcla de temas para atraer tráfico y temas para vender. Organizado y realista de mantener. Que me dé un plan claro de qué publicar este mes para posicionar.",
     en:"You're an SEO strategist. Create an SEO content plan for a month for a blog about [TOPIC/NICHE]. Give me 8 articles to publish, each with: its optimized title, the target keyword, the search intent, and what it'll be about. They should be thematically connected to build authority, and include a mix of topics to attract traffic and topics to sell. Organized and realistic to maintain. To give me a clear plan of what to publish this month to rank."}},

{ cat:"seo", t:{es:"Mejora el SEO de tu sitio web", en:"Improve your website's SEO"},
  p:{es:"Actúa como consultor SEO. Quiero mejorar el SEO general de mi sitio web de [NEGOCIO/TEMA] para que aparezca mejor en Google. Dame una lista de mejoras prácticas y priorizadas: sobre el contenido, las palabras clave, la estructura, los títulos y descripciones, y las buenas prácticas básicas. Explícamelo de forma simple, sin tecnicismos complicados, para alguien que no es experto. Que me dé acciones concretas para mejorar cómo me ve Google y posicionar mejor mi sitio.",
     en:"Act as an SEO consultant. I want to improve the overall SEO of my [BUSINESS/TOPIC] website so it appears better on Google. Give me a list of practical, prioritized improvements: about content, keywords, structure, titles and descriptions, and basic best practices. Explain it simply, without complicated jargon, for someone who isn't an expert. To give me concrete actions to improve how Google sees me and rank my site better."}},

// ---------- VIDEO Y GUIONES (+10) ----------
{ cat:"video", t:{es:"Guion de video para vender un producto", en:"Video script to sell a product"},
  p:{es:"Actúa como guionista de marketing. Escribe el guion de un video para vender [PRODUCTO] dirigido a [PÚBLICO]. Que tenga: un gancho que capte la atención, la presentación del problema que resuelve, mi producto como solución mostrando sus beneficios, prueba o credibilidad, y una llamada a la acción clara. Indica qué decir y qué mostrar en cada parte. Persuasivo y enfocado en lograr la venta. Adaptable a redes o página. Que genere deseo y ventas con el video.",
     en:"Act as a marketing scriptwriter. Write the script of a video to sell [PRODUCT] aimed at [AUDIENCE]. It should have: a hook that grabs attention, the presentation of the problem it solves, my product as the solution showing its benefits, proof or credibility, and a clear call to action. Indicate what to say and what to show in each part. Persuasive and focused on achieving the sale. Adaptable to social media or a page. To generate desire and sales with the video."}},

{ cat:"video", t:{es:"Ideas de Reels para tu nicho", en:"Reel ideas for your niche"},
  p:{es:"Eres experto en contenido para redes. Dame 12 ideas de Reels para el nicho de [NICHO] dirigidas a [PÚBLICO]. Para cada una: el concepto, el gancho de los primeros segundos, el formato, y por qué le interesaría a mi audiencia. Varía entre educativos, de entretenimiento, de tendencias, de venta y de conexión. Ordénalas por potencial. Que me den un banco de ideas de Reels listas para grabar y que ayuden a hacer crecer mi cuenta. Prácticas y aplicables.",
     en:"You're a social content expert. Give me 12 Reel ideas for the [NICHE] niche aimed at [AUDIENCE]. For each: the concept, the first-seconds hook, the format, and why my audience would care. Vary between educational, entertainment, trends, sales and connection. Sort them by potential. To give me a bank of Reel ideas ready to film that help grow my account. Practical and applicable."}},

{ cat:"video", t:{es:"Guion para video educativo corto", en:"Short educational video script"},
  p:{es:"Actúa como creador de contenido educativo. Escribe el guion de un video corto (menos de 60 segundos) que enseñe algo útil sobre [TEMA] para [NICHO]. Incluye: un gancho que enganche en los primeros segundos, el contenido educativo resumido en lo esencial y fácil de entender, el texto en pantalla, y un cierre con llamada a la acción. Que aporte valor real, sea fácil de seguir, y haga que la gente lo guarde y comparta. Listo para grabar. Práctico y aplicable.",
     en:"Act as an educational content creator. Write the script of a short video (under 60 seconds) that teaches something useful about [TOPIC] for [NICHE]. Include: a hook that engages in the first seconds, the educational content summarized to the essentials and easy to understand, the on-screen text, and a closing with a call to action. It should provide real value, be easy to follow, and make people save and share it. Ready to film. Practical and applicable."}},

{ cat:"video", t:{es:"Guion para presentarte en video", en:"Script to introduce yourself on video"},
  p:{es:"Eres guionista de contenido. Escribe el guion de un video corto para presentarme a mi audiencia de [NICHO] y que me conozcan mejor. Que cuente quién soy, qué hago, por qué lo hago, y cómo puedo ayudarlos, de forma cercana y auténtica. Con un buen inicio que enganche y un cierre que invite a seguirme. Indica qué decir y qué mostrar. Que genere conexión y confianza, y humanice mi marca. Cálido y genuino, listo para grabar. Que la gente conecte conmigo.",
     en:"You're a content scriptwriter. Write the script of a short video to introduce me to my [NICHE] audience so they know me better. It should tell who I am, what I do, why I do it, and how I can help them, warmly and authentically. With a good engaging opening and a closing that invites following me. Indicate what to say and what to show. To generate connection and trust, and humanize my brand. Warm and genuine, ready to film. So people connect with me."}},

{ cat:"video", t:{es:"Guion de video para una promoción", en:"Video script for a promotion"},
  p:{es:"Actúa como guionista de marketing. Escribe el guion de un video corto para anunciar una oferta especial de [PRODUCTO]. Que capte la atención de inmediato, comunique la oferta de forma clara y atractiva, genere urgencia, destaque el beneficio y el ahorro, y termine con una llamada a la acción potente. Indica qué mostrar y qué decir. Dinámico y persuasivo, adaptado a redes. Que impulse a la gente a aprovechar la oferta ya. Listo para grabar y que genere ventas.",
     en:"Act as a marketing scriptwriter. Write the script of a short video to announce a special offer of [PRODUCT]. It should grab attention immediately, communicate the offer clearly and attractively, create urgency, highlight the benefit and savings, and end with a powerful call to action. Indicate what to show and what to say. Dynamic and persuasive, adapted to social media. To drive people to take advantage of the offer now. Ready to film and generate sales."}},

{ cat:"video", t:{es:"Ganchos para retener en tus videos", en:"Hooks to retain in your videos"},
  p:{es:"Eres experto en retención de video. Para videos sobre [TEMA/NICHO], dame 12 ganchos potentes para los primeros 3-5 segundos que capturen la atención y eviten que la gente siga deslizando. Varía los tipos: pregunta intrigante, promesa de valor, afirmación polémica, error común, dato sorprendente, historia. Que generen ganas de seguir viendo. Marca los 4 más fuertes y dime para qué tipo de video usar cada uno. Que aumenten la retención de mis videos. Listos para usar.",
     en:"You're a video retention expert. For videos about [TOPIC/NICHE], give me 12 powerful hooks for the first 3-5 seconds that capture attention and prevent people from scrolling. Vary the types: intriguing question, value promise, controversial statement, common mistake, surprising fact, story. They should make people want to keep watching. Mark the 4 strongest and tell me what type of video to use each for. To increase my videos' retention. Ready to use."}},

{ cat:"video", t:{es:"Guion para video tutorial paso a paso", en:"Step-by-step tutorial video script"},
  p:{es:"Actúa como creador de tutoriales. Escribe el guion de un video tutorial que enseñe a [HACER ALGO] paso a paso. Incluye: una intro que diga qué van a aprender y por qué les sirve, los pasos explicados de forma clara y ordenada, consejos o errores a evitar en cada paso, y un cierre. Indica qué decir y qué mostrar en pantalla en cada momento. Fácil de seguir, que cualquiera pueda lograr el resultado siguiendo el video. Práctico y bien estructurado.",
     en:"Act as a tutorial creator. Write the script of a tutorial video that teaches how to [DO SOMETHING] step by step. Include: an intro saying what they'll learn and why it's useful, the steps explained clearly and in order, tips or mistakes to avoid at each step, and a closing. Indicate what to say and what to show on screen at each moment. Easy to follow, so anyone can achieve the result following the video. Practical and well structured."}},

{ cat:"video", t:{es:"Serie de videos para tu canal", en:"Video series for your channel"},
  p:{es:"Eres estratega de contenido en video. Diséñame una serie de videos sobre [TEMA] para [PÚBLICO] que mantenga a mi audiencia esperando el siguiente. Dame: el concepto de la serie, su nombre, 7 episodios con su título y qué trata cada uno, ordenados de forma lógica, y cómo conectarlos para que la gente vea toda la serie. Que eduque o entretenga, posicione mi conocimiento, y haga que mi audiencia me siga. Práctica y aplicable, lista para empezar a producir.",
     en:"You're a video content strategist. Design me a video series about [TOPIC] for [AUDIENCE] that keeps my audience waiting for the next one. Give me: the series concept, its name, 7 episodes with their title and what each is about, ordered logically, and how to connect them so people watch the whole series. It should educate or entertain, position my knowledge, and make my audience follow me. Practical and applicable, ready to start producing."}},

{ cat:"video", t:{es:"Guion para mostrar resultados o testimonios", en:"Script to show results or testimonials"},
  p:{es:"Actúa como experto en video marketing. Escribe el guion para un video que muestre resultados o testimonios sobre [PRODUCTO/SERVICIO] para generar confianza y vender. Estructura: la situación antes, el problema que tenía el cliente, cómo mi producto ayudó, el resultado obtenido, y una recomendación. Que sea creíble, genere confianza y motive a otros a comprar. Indica qué mostrar y qué decir. Natural y persuasivo, no robótico. Que use la prueba social para vender más.",
     en:"Act as a video marketing expert. Write the script for a video that shows results or testimonials about [PRODUCT/SERVICE] to build trust and sell. Structure: the situation before, the problem the customer had, how my product helped, the result achieved, and a recommendation. It should be believable, build trust and motivate others to buy. Indicate what to show and what to say. Natural and persuasive, not robotic. To use social proof to sell more."}},

{ cat:"video", t:{es:"Convierte un tema en guion de video", en:"Turn a topic into a video script"},
  p:{es:"Eres experto en adaptar contenido a video. Toma este tema o contenido sobre [TEMA] y conviértelo en un guion de video atractivo para [PLATAFORMA]. Adáptalo a un formato dinámico: con un buen gancho al inicio, el contenido resumido en lo esencial y atractivo, buen ritmo, y un cierre con llamada a la acción. Indica qué decir y qué mostrar mientras se narra. Que funcione mejor en video que como texto. Práctico y aplicable, listo para grabar siguiendo el guion.",
     en:"You're an expert at adapting content to video. Take this topic or content about [TOPIC] and turn it into an engaging video script for [PLATFORM]. Adapt it to a dynamic format: with a good hook at the start, the content summarized to the essentials and engaging, good pacing, and a closing with a call to action. Indicate what to say and what to show while narrating. It should work better as video than as text. Practical and applicable, ready to film following the script."}},

// ---------- MARCA PERSONAL (+10) ----------
{ cat:"personal", t:{es:"Define tu marca personal con claridad", en:"Define your personal brand clearly"},
  p:{es:"Actúa como estratega de marca personal. Ayúdame a definir mi marca personal con claridad. Me dedico a [ACTIVIDAD] y quiero ser conocido en [ÁREA/TEMA]. Dame: cuál podría ser mi mensaje central, qué me diferencia, qué temas debería tratar, qué valores transmitir, qué tono usar, y cómo quiero que me perciban. Que tenga claridad total sobre quién soy como marca y cómo comunicarlo de forma auténtica y coherente. Práctica y aplicable.",
     en:"Act as a personal brand strategist. Help me define my personal brand clearly. I work in [ACTIVITY] and want to be known in [AREA/TOPIC]. Give me: what my central message could be, what differentiates me, what topics I should cover, what values to convey, what tone to use, and how I want to be perceived. So I have total clarity about who I am as a brand and how to communicate it authentically and coherently. Practical and applicable."}},

{ cat:"personal", t:{es:"Crea contenido que demuestre tu experiencia", en:"Create content that shows your expertise"},
  p:{es:"Eres estratega de marca personal. Dame 10 ideas de contenido para demostrar mi experiencia y posicionarme como referente en [TEMA/ÁREA] ante [PÚBLICO]. Para cada idea: el tema, el formato ideal, y qué demuestra de mi conocimiento o experiencia. Que combinen compartir lo que sé, casos reales, opiniones de valor, y lecciones aprendidas. Que generen credibilidad y confianza con mi audiencia, y me posicionen como alguien que sabe de lo que habla. Prácticas y aplicables.",
     en:"You're a personal brand strategist. Give me 10 content ideas to demonstrate my experience and position myself as a reference in [TOPIC/AREA] for [AUDIENCE]. For each idea: the topic, the ideal format, and what it demonstrates of my knowledge or experience. They should combine sharing what I know, real cases, valuable opinions, and lessons learned. They should build credibility and trust with my audience, and position me as someone who knows what they're talking about. Practical and applicable."}},

{ cat:"personal", t:{es:"Optimiza tu perfil profesional", en:"Optimize your professional profile"},
  p:{es:"Actúa como experto en marca personal. Ayúdame a optimizar mi perfil profesional en [RED SOCIAL/LINKEDIN] para que me posicione y atraiga oportunidades en [ÁREA/SECTOR]. Dame: un titular profesional potente, un texto de presentación que comunique mi valor y conecte, cómo describir mi experiencia enfocándola en logros y resultados, y qué incluir para que me encuentren y contacten. Profesional y atractivo. Que mi perfil me represente bien y genere oportunidades.",
     en:"Act as a personal branding expert. Help me optimize my professional profile on [SOCIAL NETWORK/LINKEDIN] so it positions me and attracts opportunities in [AREA/SECTOR]. Give me: a powerful professional headline, a presentation text that communicates my value and connects, how to describe my experience focusing on achievements and results, and what to include so I'm found and contacted. Professional and attractive. So my profile represents me well and generates opportunities."}},

{ cat:"personal", t:{es:"Cuenta tu historia para conectar", en:"Tell your story to connect"},
  p:{es:"Eres experto en storytelling personal. Ayúdame a contar mi historia profesional o personal de forma que conecte e inspire a mi audiencia de [NICHO/ÁREA]. Mi trayectoria es: [RESUME TU HISTORIA]. Conviértela en un relato auténtico y atractivo que muestre mi propósito, los retos que superé, y el valor que aporto hoy. Que genere conexión, identificación y confianza con quien lo lea. Auténtico, emotivo y memorable. Listo para usar en una publicación o video.",
     en:"You're a personal storytelling expert. Help me tell my professional or personal story in a way that connects and inspires my [NICHE/AREA] audience. My background is: [SUMMARIZE YOUR STORY]. Turn it into an authentic, engaging narrative that shows my purpose, the challenges I overcame, and the value I bring today. It should generate connection, identification and trust with whoever reads it. Authentic, emotional and memorable. Ready to use in a post or video."}},

{ cat:"personal", t:{es:"Plan de contenido para tu marca personal", en:"Content plan for your personal brand"},
  p:{es:"Actúa como estratega de contenido personal. Crea un plan de contenido para construir mi marca personal en [RED SOCIAL] sobre [TEMA/ÁREA]. Dame: los pilares de contenido (qué temas tratar), una mezcla equilibrada de tipos de publicación (mostrar experiencia, aportar valor, conectar a nivel humano, contar mi historia), con qué frecuencia publicar, y cómo mantener consistencia. Realista y sostenible. Que me dé una guía clara de qué publicar para construir mi marca personal paso a paso.",
     en:"Act as a personal content strategist. Create a content plan to build my personal brand on [SOCIAL NETWORK] about [TOPIC/AREA]. Give me: the content pillars (what topics to cover), a balanced mix of post types (show experience, provide value, connect on a human level, tell my story), how often to publish, and how to maintain consistency. Realistic and sustainable. To give me a clear guide of what to publish to build my personal brand step by step."}},

{ cat:"personal", t:{es:"Construye autoridad en tu especialidad", en:"Build authority in your specialty"},
  p:{es:"Eres estratega de marca personal. Quiero posicionarme como experto en [TEMA] ante [PÚBLICO]. Dame una estrategia: qué tipo de contenido demuestra mi conocimiento, cómo compartir mi experiencia con autoridad sin sonar arrogante, qué temas tratar para destacar, cómo aprovechar resultados y testimonios, y cómo ganar credibilidad con el tiempo. Dame un plan concreto y aplicable para construir mi autoridad. Que la gente me reconozca como un referente confiable en mi tema.",
     en:"You're a personal brand strategist. I want to position myself as an expert in [TOPIC] for [AUDIENCE]. Give me a strategy: what type of content demonstrates my knowledge, how to share my experience with authority without sounding arrogant, what topics to cover to stand out, how to leverage results and testimonials, and how to gain credibility over time. Give me a concrete, applicable plan to build my authority. So people recognize me as a trustworthy reference in my topic."}},

{ cat:"personal", t:{es:"Escribe una publicación que genere interacción", en:"Write a post that drives interaction"},
  p:{es:"Actúa como experto en contenido de marca personal. Escribe una publicación sobre [TEMA/EXPERIENCIA] para [RED SOCIAL] que genere interacción y me posicione como referente en [ÁREA]. Que tenga un inicio que enganche, una historia, aprendizaje o reflexión de valor, un mensaje que aporte, y una invitación a comentar o reflexionar. Profesional pero cercano, en el estilo que funciona en esa red. Que genere conversación y fortalezca mi marca personal. Lista para publicar.",
     en:"Act as a personal brand content expert. Write a post about [TOPIC/EXPERIENCE] for [SOCIAL NETWORK] that drives interaction and positions me as a reference in [AREA]. It should have an engaging opening, a story, valuable lesson or reflection, a message that adds value, and an invitation to comment or reflect. Professional but warm, in the style that works on that network. To generate conversation and strengthen my personal brand. Ready to publish."}},

{ cat:"personal", t:{es:"Comunica tu propuesta de valor", en:"Communicate your value proposition"},
  p:{es:"Eres experto en marca personal. Ayúdame a definir y comunicar mi propuesta de valor profesional. Me dedico a [ACTIVIDAD], mi experiencia es [EXPERIENCIA] y ayudo a [PÚBLICO]. Resume en una declaración clara: qué hago, para quién, qué problema resuelvo, y qué me hace diferente. Dame 3 versiones que pueda usar para presentarme con seguridad en distintos contextos. Clara, convincente y memorable. Que comunique mi valor de forma que la gente entienda por qué elegirme.",
     en:"You're a personal branding expert. Help me define and communicate my professional value proposition. I work in [ACTIVITY], my experience is [EXPERIENCE] and I help [AUDIENCE]. Summarize in a clear statement: what I do, for whom, what problem I solve, and what makes me different. Give me 3 versions I can use to introduce myself with confidence in different contexts. Clear, convincing and memorable. To communicate my value so people understand why to choose me."}},

{ cat:"personal", t:{es:"Ideas para empezar a crear contenido", en:"Ideas to start creating content"},
  p:{es:"Actúa como coach de marca personal. Quiero empezar a crear contenido en [RED SOCIAL] sobre [TEMA] pero no sé por dónde empezar y me da algo de miedo. Dame 10 ideas de primeras publicaciones fáciles de hacer, que rompan el hielo, muestren quién soy, y aporten valor sin necesidad de ser perfecto. Que me ayuden a arrancar con confianza y a soltar el miedo de exponerme. Concretas y accionables, para que pueda empezar a crear contenido hoy mismo sin presionarme.",
     en:"Act as a personal brand coach. I want to start creating content on [SOCIAL NETWORK] about [TOPIC] but don't know where to start and I'm a bit afraid. Give me 10 easy first-post ideas that break the ice, show who I am, and add value without needing to be perfect. They should help me start with confidence and let go of the fear of exposing myself. Concrete and actionable, so I can start creating content today without pressuring myself."}},

{ cat:"personal", t:{es:"Diferénciate de otros en tu área", en:"Differentiate yourself from others in your area"},
  p:{es:"Eres estratega de marca personal. En mi área de [ÁREA] hay mucha gente que hace lo mismo que yo, y quiero destacar. Ayúdame a diferenciarme: cómo encontrar lo que me hace único, cómo resaltar mi enfoque, estilo o personalidad, cómo comunicar lo que me distingue de los demás, y cómo posicionarme de forma que la gente me elija a mí. Dame un enfoque para dejar de ser uno más y convertirme en una opción memorable y diferente. Práctico y aplicable.",
     en:"You're a personal brand strategist. In my [AREA] area there are many people who do the same as me, and I want to stand out. Help me differentiate myself: how to find what makes me unique, how to highlight my approach, style or personality, how to communicate what distinguishes me from others, and how to position myself so people choose me. Give me an approach to stop being one more and become a memorable, different option. Practical and applicable."}},

// ---------- IA Y AGENTES (+10) ----------
{ cat:"agents", t:{es:"Crea instrucciones para un asistente de IA", en:"Create instructions for an AI assistant"},
  p:{es:"Actúa como experto en configuración de agentes de IA. Ayúdame a crear las instrucciones para un asistente de IA especializado en [TAREA/FUNCIÓN]. Dame: el rol que debe asumir, su personalidad y tono, qué debe hacer paso a paso, qué información pedir al usuario, qué formato de respuesta usar, y qué NO debe hacer. Que quede como un asistente útil y bien definido para lo que necesito. Listo para copiar y configurar. Completo y bien estructurado.",
     en:"Act as an AI agent configuration expert. Help me create the instructions for an AI assistant specialized in [TASK/FUNCTION]. Give me: the role it should take, its personality and tone, what it should do step by step, what information to ask the user, what response format to use, and what it should NOT do. So it becomes a useful, well-defined assistant for what I need. Ready to copy and configure. Complete and well structured."}},

{ cat:"agents", t:{es:"Mejora tus prompts para mejores resultados", en:"Improve your prompts for better results"},
  p:{es:"Actúa como experto en prompts de IA. Enséñame a escribir mejores prompts para obtener respuestas más útiles. Dame los elementos clave de un buen prompt (rol, contexto, instrucción clara, formato deseado, ejemplos), los errores comunes que arruinan los resultados, y una plantilla o estructura que pueda seguir siempre. Con un ejemplo de un prompt malo y su versión mejorada. Práctico, para que aprenda a pedirle mejor a la IA y obtenga respuestas de más calidad.",
     en:"Act as an AI prompt expert. Teach me to write better prompts to get more useful answers. Give me the key elements of a good prompt (role, context, clear instruction, desired format, examples), the common mistakes that ruin results, and a template or structure I can always follow. With an example of a bad prompt and its improved version. Practical, so I learn to ask AI better and get higher-quality answers."}},

{ cat:"agents", t:{es:"Usa la IA para crear contenido de tu negocio", en:"Use AI to create your business content"},
  p:{es:"Actúa como experto en IA para negocios. Quiero usar la IA para crear contenido para mi negocio de [NEGOCIO/NICHO] más rápido y sin perder calidad ni mi estilo. Dame un sistema práctico: cómo usar la IA para generar ideas, crear y mejorar textos, captions y guiones, cómo darle mi estilo para que suene a mí, qué prompts usar para cada tipo de contenido, y cómo revisar lo que genera. Que me ayude a producir más contenido en menos tiempo manteniendo mi voz. Práctico y aplicable.",
     en:"Act as an AI-for-business expert. I want to use AI to create content for my [BUSINESS/NICHE] business faster and without losing quality or my style. Give me a practical system: how to use AI to generate ideas, create and improve texts, captions and scripts, how to give it my style so it sounds like me, what prompts to use for each content type, and how to review what it generates. To help me produce more content in less time keeping my voice. Practical and applicable."}},

{ cat:"agents", t:{es:"Configura un asistente IA para tu empresa", en:"Set up an AI assistant for your company"},
  p:{es:"Eres experto en automatización con IA. Ayúdame a diseñar un asistente de IA para mi negocio [NEGOCIO] que me ahorre tiempo en [TAREA: atención a clientes, contenido, organización, etc.]. Dame las instrucciones completas: qué rol darle, qué debe saber sobre mi negocio, cómo debe responder, qué tareas puede manejar, qué información necesita de mí, y cómo integrarlo en mi día a día. Que quede como un asistente útil y listo para usar. Práctico y bien estructurado.",
     en:"You're an AI automation expert. Help me design an AI assistant for my business [BUSINESS] that saves me time on [TASK: customer service, content, organization, etc.]. Give me the complete instructions: what role to give it, what it should know about my business, how it should respond, what tasks it can handle, what information it needs from me, and how to integrate it into my daily routine. So it becomes a useful assistant ready to use. Practical and well structured."}},

{ cat:"agents", t:{es:"Resuelve problemas con ayuda de la IA", en:"Solve problems with AI's help"},
  p:{es:"Actúa como consultor experto. Tengo este problema o reto: [DESCRIBE EL PROBLEMA]. Ayúdame a resolverlo pensándolo paso a paso: hazme las preguntas necesarias para entenderlo bien, analiza las posibles causas, propón varias soluciones con sus pros y contras, y recomiéndame el mejor camino a seguir. Que me ayudes a ver el problema con claridad y a salir del estancamiento con un plan concreto. Práctico y orientado a la solución.",
     en:"Act as an expert consultant. I have this problem or challenge: [DESCRIBE THE PROBLEM]. Help me solve it by thinking step by step: ask me the necessary questions to understand it well, analyze the possible causes, propose several solutions with their pros and cons, and recommend the best path forward. Help me see the problem clearly and get unstuck with a concrete plan. Practical and solution-oriented."}},

{ cat:"agents", t:{es:"Aprende un tema nuevo con la IA", en:"Learn a new topic with AI"},
  p:{es:"Actúa como tutor personal experto. Quiero usar la IA para aprender [TEMA/HABILIDAD] de forma efectiva, adaptándote a mi ritmo. Empieza evaluando qué sé, luego enséñame paso a paso de lo básico a lo avanzado, con explicaciones simples y ejemplos, y hazme preguntas o ejercicios para comprobar que entiendo antes de seguir. Acompáñame como un profesor paciente hasta que domine el tema. Que me ayudes a aprender de forma estructurada y efectiva con tu ayuda.",
     en:"Act as an expert personal tutor. I want to use AI to learn [TOPIC/SKILL] effectively, adapting to my pace. Start by assessing what I know, then teach me step by step from basic to advanced, with simple explanations and examples, and ask me questions or exercises to check I understand before continuing. Accompany me like a patient teacher until I master the topic. Help me learn in a structured and effective way with your help."}},

{ cat:"agents", t:{es:"Crea prompts encadenados para una tarea", en:"Create chained prompts for a task"},
  p:{es:"Eres experto en flujos de trabajo con IA. Quiero lograr [OBJETIVO/RESULTADO] usando la IA, pero es un proceso de varios pasos. Diséñame una serie de prompts encadenados: el primero para el paso inicial, cuyo resultado alimenta al segundo, y así sucesivamente hasta lograr el resultado final. Dame cada prompt listo para usar y explícame cómo usar la salida de uno como entrada del siguiente. Práctico y aplicable, para resolver una tarea compleja paso a paso con la IA.",
     en:"You're an AI workflow expert. I want to achieve [GOAL/RESULT] using AI, but it's a multi-step process. Design me a series of chained prompts: the first for the initial step, whose result feeds the second, and so on until achieving the final result. Give me each prompt ready to use and explain how to use the output of one as the input of the next. Practical and applicable, to solve a complex task step by step with AI."}},

{ cat:"agents", t:{es:"Aplica la IA a tu profesión", en:"Apply AI to your profession"},
  p:{es:"Actúa como experto en productividad con IA. Trabajo en [ÁREA/PROFESIÓN] y quiero usar la IA para ser más eficiente y mejorar mis resultados. Dame ideas concretas de cómo aplicarla a mis tareas: en qué me puede ayudar específicamente, con ejemplos de para qué usarla, qué prompts probar, y cómo integrarla en mi rutina de trabajo. Enfócate en usos prácticos y reales que me ahorren tiempo y me ayuden a trabajar mejor. Aplicable a lo que hago en mi día a día.",
     en:"Act as an AI productivity expert. I work in [AREA/PROFESSION] and want to use AI to be more efficient and improve my results. Give me concrete ideas on how to apply it to my tasks: what it can specifically help me with, with examples of what to use it for, what prompts to try, and how to integrate it into my work routine. Focus on practical, real uses that save me time and help me work better. Applicable to what I do day to day."}},

{ cat:"agents", t:{es:"Haz una sesión de ideas con la IA", en:"Run an idea session with AI"},
  p:{es:"Actúa como facilitador creativo experto. Ayúdame con una lluvia de ideas sobre [TEMA/PROBLEMA/PROYECTO]. Genera muchas ideas variadas y creativas, desde las más obvias hasta las más originales, organízalas por enfoque o tipo, y al final destaca las 5 con más potencial explicando por qué. Que me ayudes a desbloquear opciones e ideas que no había pensado, y a ver el tema desde distintos ángulos. Creativo y práctico, para impulsar mi creatividad con la IA.",
     en:"Act as an expert creative facilitator. Help me brainstorm about [TOPIC/PROBLEM/PROJECT]. Generate many varied, creative ideas, from the most obvious to the most original, organize them by approach or type, and at the end highlight the 5 with the most potential explaining why. Help me unlock options and ideas I hadn't thought of, and see the topic from different angles. Creative and practical, to boost my creativity with AI."}},

{ cat:"agents", t:{es:"Crea un prompt maestro reutilizable", en:"Create a reusable master prompt"},
  p:{es:"Actúa como experto en prompts. Hago seguido esta tarea con la IA: [DESCRIBE LA TAREA]. Ayúdame a crear un 'prompt maestro' reutilizable que me dé buenos resultados siempre. Inclúyele el rol, el contexto, las instrucciones claras paso a paso, el formato de salida que quiero, y espacios donde yo solo cambie los datos variables. Que quede listo para guardar y reutilizar cada vez que necesite hacer esta tarea, ahorrándome tiempo y dándome resultados consistentes. Práctico y bien estructurado.",
     en:"Act as a prompt expert. I often do this task with AI: [DESCRIBE THE TASK]. Help me create a reusable 'master prompt' that gives me good results every time. Include the role, the context, clear step-by-step instructions, the output format I want, and slots where I only change the variable data. So it's ready to save and reuse each time I need to do this task, saving me time and giving me consistent results. Practical and well structured."}},

// ---------- EDUCACIÓN (+10) ----------
{ cat:"education", t:{es:"Crea un plan de estudio completo", en:"Create a complete study plan"},
  p:{es:"Actúa como tutor experto. Quiero estudiar [MATERIA/TEMA] y necesito un plan de estudio organizado. Tengo [TIEMPO DISPONIBLE]. Créame un plan: cómo dividir los temas en el tiempo que tengo, qué estudiar primero, cómo avanzar de forma progresiva, cómo repasar para que se quede, cuándo descansar, y cómo medir mi avance. Realista y adaptado a mi tiempo. Que me dé una ruta clara para estudiar de forma efectiva y dominar el tema sin agobiarme. Práctico y aplicable.",
     en:"Act as an expert tutor. I want to study [SUBJECT/TOPIC] and need an organized study plan. I have [AVAILABLE TIME]. Create a plan: how to divide the topics in the time I have, what to study first, how to advance progressively, how to review so it sticks, when to rest, and how to measure my progress. Realistic and adapted to my time. To give me a clear route to study effectively and master the topic without overwhelming myself. Practical and applicable."}},

{ cat:"education", t:{es:"Explícame un tema difícil de forma simple", en:"Explain a difficult topic simply"},
  p:{es:"Eres profesor experto en explicar. Explícame [TEMA/CONCEPTO DIFÍCIL] de forma clara y fácil de entender, como si no supiera nada del tema. Usa una explicación sencilla, ejemplos de la vida real, una analogía que lo haga memorable, y al final un resumen de lo más importante. Adapta la explicación a nivel [NIVEL: principiante, intermedio]. Que entienda el concepto a fondo aunque sea complicado o nuevo para mí. Claro, didáctico y fácil de seguir.",
     en:"You're a teacher who's an expert at explaining. Explain [DIFFICULT TOPIC/CONCEPT] to me clearly and easy to understand, as if I knew nothing about the topic. Use a simple explanation, real-life examples, an analogy that makes it memorable, and at the end a summary of the most important. Adapt the explanation to [LEVEL: beginner, intermediate] level. So I understand the concept thoroughly even if it's complicated or new to me. Clear, didactic and easy to follow."}},

{ cat:"education", t:{es:"Crea ejercicios para practicar un tema", en:"Create exercises to practice a topic"},
  p:{es:"Actúa como diseñador educativo. Crea una serie de ejercicios de práctica sobre [TEMA] para nivel [NIVEL]. Dame ejercicios variados de menor a mayor dificultad, con sus respuestas y una breve explicación de cada una. Que cubran los aspectos más importantes del tema y me ayuden a practicar y dominarlo, reforzando lo aprendido. Útiles para estudiar por mi cuenta o para enseñar. Claros y bien organizados. Que me permitan practicar de forma efectiva y comprobar que entendí.",
     en:"Act as an educational designer. Create a series of practice exercises about [TOPIC] for [LEVEL] level. Give me varied exercises from easy to hard, with their answers and a brief explanation of each. They should cover the most important aspects of the topic and help me practice and master it, reinforcing what I learned. Useful to study on my own or to teach. Clear and well organized. So they let me practice effectively and confirm I understood."}},

{ cat:"education", t:{es:"Resume lo más importante de un tema", en:"Summarize the most important of a topic"},
  p:{es:"Eres experto en simplificar. Hazme un resumen claro y organizado de [TEMA] que destaque solo lo más importante que debo saber. Estructúralo de lo más básico a lo más avanzado, usa lenguaje simple, e incluye los puntos clave de forma que pueda entender y recordar lo esencial fácilmente. Que me ayude a comprender o repasar un tema de forma rápida y clara, quedándome con lo que de verdad importa. Bien organizado y fácil de estudiar o repasar.",
     en:"You're an expert at simplifying. Make me a clear, organized summary of [TOPIC] highlighting only the most important I should know. Structure it from most basic to most advanced, use simple language, and include the key points so I can understand and remember the essentials easily. To help me grasp or review a topic quickly and clearly, keeping what really matters. Well organized and easy to study or review."}},

{ cat:"education", t:{es:"Técnica para memorizar lo que estudias", en:"Technique to memorize what you study"},
  p:{es:"Actúa como experto en técnicas de memoria. Necesito memorizar [QUÉ NECESITAS MEMORIZAR] para [PROPÓSITO]. Enséñame la mejor técnica para lograrlo y aplícala directamente a mi caso con un ejemplo concreto. Explícame paso a paso cómo usarla, cómo repasar para no olvidar, y cómo hacer que la información se quede en mi memoria a largo plazo. Práctica y aplicable a lo que necesito memorizar. Que de verdad me funcione para recordar lo que estudio.",
     en:"Act as a memory-technique expert. I need to memorize [WHAT YOU NEED TO MEMORIZE] for [PURPOSE]. Teach me the best technique to do it and apply it directly to my case with a concrete example. Explain step by step how to use it, how to review so I don't forget, and how to make the information stay in my long-term memory. Practical and applicable to what I need to memorize. So it really works for me to remember what I study."}},

{ cat:"education", t:{es:"Diseña una clase o taller", en:"Design a class or workshop"},
  p:{es:"Eres experto en diseño de clases. Ayúdame a diseñar una clase o taller para enseñar [TEMA] a [PÚBLICO/EDAD]. Dame: el objetivo de aprendizaje, la estructura (inicio, desarrollo, cierre), las actividades para que aprendan haciendo, cómo mantener el interés, los materiales necesarios, y cómo comprobar que aprendieron. Que sea dinámica, participativa y efectiva. Práctica y aplicable, lista para impartir. Que haga el aprendizaje entretenido y logre que los participantes aprendan de verdad.",
     en:"You're a class design expert. Help me design a class or workshop to teach [TOPIC] to [AUDIENCE/AGE]. Give me: the learning objective, the structure (opening, development, closing), the activities so they learn by doing, how to keep interest, the materials needed, and how to check they learned. It should be dynamic, participatory and effective. Practical and applicable, ready to deliver. To make learning entertaining and ensure participants really learn."}},

{ cat:"education", t:{es:"Explica un tema a alguien sin conocimientos", en:"Explain a topic to a beginner"},
  p:{es:"Actúa como educador experto. Explícame [TEMA] de forma que alguien que no sabe nada del tema lo entienda y le parezca interesante. Usa un lenguaje sencillo, evita tecnicismos (y si los usas, explícalos), pon ejemplos y comparaciones con cosas conocidas, y hazlo ameno para mantener la atención. Que la persona entienda el tema desde cero y se quede con ganas de aprender más. Claro, sencillo y entretenido. Que cualquiera pueda entenderlo sin conocimientos previos.",
     en:"Act as an expert educator. Explain [TOPIC] to me in a way that someone who knows nothing about it understands and finds interesting. Use simple language, avoid jargon (and if you use it, explain it), give examples and comparisons with familiar things, and make it enjoyable to keep attention. So the person understands the topic from scratch and stays wanting to learn more. Clear, simple and entertaining. So anyone can understand it without prior knowledge."}},

{ cat:"education", t:{es:"Guía para aprender una habilidad", en:"Guide to learn a skill"},
  p:{es:"Actúa como coach de aprendizaje. Quiero aprender [HABILIDAD] desde cero. Créame una guía de aprendizaje: por dónde empezar, los pasos para progresar de principiante a competente, qué practicar en cada etapa, los errores comunes a evitar, cómo medir mi avance, y cuánto tiempo podría tomar. Práctica y motivadora. Que me dé un camino claro para aprender la habilidad sin perderme ni frustrarme, y que pueda ir avanzando paso a paso. Realista y aplicable a mi situación.",
     en:"Act as a learning coach. I want to learn [SKILL] from scratch. Create me a learning guide: where to start, the steps to progress from beginner to competent, what to practice at each stage, the common mistakes to avoid, how to measure my progress, and how long it might take. Practical and motivating. To give me a clear path to learn the skill without getting lost or frustrated, and to advance step by step. Realistic and applicable to my situation."}},

{ cat:"education", t:{es:"Crea preguntas para evaluar el aprendizaje", en:"Create questions to assess learning"},
  p:{es:"Eres experto en evaluación educativa. Sobre el tema [TEMA], crea un conjunto de preguntas para evaluar qué tanto se ha aprendido, para nivel [NIVEL]. Dame preguntas variadas (de opción, de desarrollo, de aplicación) de menor a mayor dificultad, con sus respuestas correctas. Que cubran los aspectos clave del tema y permitan comprobar la comprensión real, no solo la memorización. Útiles para evaluarme a mí mismo o a estudiantes. Claras y bien diseñadas. Que midan el aprendizaje de forma efectiva.",
     en:"You're an educational assessment expert. On the topic [TOPIC], create a set of questions to assess how much has been learned, for [LEVEL] level. Give me varied questions (multiple choice, open-ended, application) from easy to hard, with their correct answers. They should cover the key aspects of the topic and allow checking real understanding, not just memorization. Useful to assess myself or students. Clear and well designed. To measure learning effectively."}},

{ cat:"education", t:{es:"Material de repaso para un examen", en:"Review material for an exam"},
  p:{es:"Actúa como tutor experto. Tengo un examen sobre [TEMA/MATERIA] y quiero repasar lo más importante. Créame un material de repaso: los conceptos clave que debo dominar, lo que más suelen preguntar, datos o fórmulas importantes a recordar, y preguntas de práctica con sus respuestas. Organizado de forma que pueda repasar de manera eficiente antes del examen. Claro y enfocado en lo esencial. Que me ayude a llegar preparado y con confianza al examen, repasando lo que de verdad importa.",
     en:"Act as an expert tutor. I have an exam on [TOPIC/SUBJECT] and want to review the most important. Create me review material: the key concepts I should master, what's most often asked, important facts or formulas to remember, and practice questions with their answers. Organized so I can review efficiently before the exam. Clear and focused on the essentials. To help me arrive prepared and confident to the exam, reviewing what really matters."}},

// ---------- SALUD Y BIENESTAR (+10) ----------
{ cat:"health", t:{es:"Rutina simple de bienestar", en:"Simple wellness routine"},
  p:{es:"Actúa como coach de bienestar. Ayúdame a crear una rutina diaria sencilla para cuidar mi bienestar físico y mental, considerando que tengo [DESCRIBE TU SITUACIÓN: poco tiempo, mucho estrés, etc.]. Incluye pequeños hábitos saludables fáciles de mantener: movimiento, descanso, momentos de calma, hidratación. Realista y sostenible para mi día a día. Aclara que ante cualquier condición de salud específica debo consultar a un profesional. Práctica y adaptada a mi situación.",
     en:"Act as a wellness coach. Help me create a simple daily routine to care for my physical and mental wellbeing, considering that I have [DESCRIBE YOUR SITUATION: little time, much stress, etc.]. Include small healthy habits easy to maintain: movement, rest, moments of calm, hydration. Realistic and sustainable for my daily life. Clarify that for any specific health condition I should consult a professional. Practical and adapted to my situation."}},

{ cat:"health", t:{es:"Ideas de publicaciones de salud y bienestar", en:"Health and wellness post ideas"},
  p:{es:"Actúa como creador de contenido de salud y bienestar. Dame 10 ideas de publicaciones educativas sobre hábitos saludables y bienestar para [PÚBLICO] en redes sociales. Que sean informativas, motivadoras y basadas en recomendaciones generales seguras (no consejos médicos específicos). Para cada idea: el tema y el mensaje principal. Que eduquen y promuevan el bienestar de forma positiva y responsable, y conecten con mi audiencia. Útiles y aplicables, listas para crear contenido de valor sobre bienestar.",
     en:"Act as a health and wellness content creator. Give me 10 educational post ideas about healthy habits and wellbeing for [AUDIENCE] on social media. They should be informative, motivating and based on safe general recommendations (not specific medical advice). For each idea: the topic and the main message. They should educate and promote wellbeing positively and responsibly, and connect with my audience. Useful and applicable, ready to create valuable content about wellbeing."}},

{ cat:"health", t:{es:"Técnicas para manejar el estrés", en:"Techniques to manage stress"},
  p:{es:"Eres facilitador de bienestar emocional. Crea una guía práctica con técnicas seguras para manejar el estrés del día a día: respiración, pausas, organización, relajación, movimiento. Para cada técnica, explica cómo hacerla paso a paso y cuándo usarla. Que sean fáciles de aplicar en cualquier momento. Aclara que ante malestar emocional persistente es importante buscar apoyo de un profesional de salud mental. Práctica y útil, para tener herramientas que me ayuden a manejar el estrés de forma saludable.",
     en:"You're an emotional wellness facilitator. Create a practical guide with safe techniques to manage everyday stress: breathing, breaks, organization, relaxation, movement. For each technique, explain how to do it step by step and when to use it. They should be easy to apply anytime. Clarify that for persistent emotional distress it's important to seek support from a mental health professional. Practical and useful, to have tools that help me manage stress healthily."}},

{ cat:"health", t:{es:"Hábitos para tener más energía", en:"Habits for more energy"},
  p:{es:"Actúa como coach de bienestar. Me siento con poca energía durante el día y quiero mejorarlo de forma natural y saludable. Dame hábitos y recomendaciones generales seguras para tener más energía: sobre el descanso, la alimentación, el movimiento, la hidratación, y las pausas. Prácticos y fáciles de adoptar en mi rutina. Aclara que si el cansancio persiste o es fuerte, debo consultar a un médico para descartar causas de salud. Que me ayuden a sentirme con más energía en el día a día de forma sana.",
     en:"Act as a wellness coach. I feel low on energy during the day and want to improve it naturally and healthily. Give me safe general habits and recommendations for more energy: about rest, nutrition, movement, hydration, and breaks. Practical and easy to adopt in my routine. Clarify that if the fatigue persists or is strong, I should consult a doctor to rule out health causes. To help me feel more energized day to day in a healthy way."}},

{ cat:"health", t:{es:"Mejora la calidad de tu sueño", en:"Improve your sleep quality"},
  p:{es:"Eres educador en higiene del sueño. Dame una guía con recomendaciones generales y seguras para dormir mejor: cómo crear una rutina relajante antes de dormir, el ambiente ideal para descansar, hábitos a evitar (como pantallas o cafeína), y cómo mantener un horario regular. Prácticas para una persona sana con dificultades leves de sueño por malos hábitos. Aclara que ante insomnio persistente se debe consultar a un profesional de salud. Útil y aplicable, para mejorar la calidad de mi descanso.",
     en:"You're a sleep hygiene educator. Give me a guide with safe general recommendations to sleep better: how to create a relaxing pre-sleep routine, the ideal environment to rest, habits to avoid (like screens or caffeine), and how to maintain a regular schedule. Practical for a healthy person with mild sleep difficulties due to bad habits. Clarify that for persistent insomnia a health professional should be consulted. Useful and applicable, to improve the quality of my rest."}},

{ cat:"health", t:{es:"Información sobre alimentación saludable", en:"Information on healthy eating"},
  p:{es:"Actúa como educador en nutrición general. Crea una guía sencilla de alimentación saludable para una persona promedio sana que quiere comer mejor. Explica el plato saludable, las porciones, los alimentos a incluir más seguido y los a moderar, y consejos prácticos para el día a día con comida accesible. Aclara que para necesidades específicas o condiciones de salud se debe consultar a un nutricionista. Educativa y práctica, para tener una guía general de cómo alimentarme de forma más saludable.",
     en:"Act as a general nutrition educator. Create a simple healthy-eating guide for an average healthy person who wants to eat better. Explain the healthy plate, portions, foods to include more often and to moderate, and practical day-to-day tips with accessible food. Clarify that for specific needs or health conditions a nutritionist should be consulted. Educational and practical, to have a general guide on how to eat more healthily."}},

{ cat:"health", t:{es:"Rutina de ejercicio suave en casa", en:"Gentle home exercise routine"},
  p:{es:"Actúa como instructor de actividad física. Diseña una rutina de ejercicio suave para hacer en casa, para una persona sana que quiere empezar a moverse más, sin equipo. Incluye calentamiento, ejercicios básicos con repeticiones moderadas, estiramiento, y cómo ir progresando por semanas. Enfócate en la constancia y la técnica segura. Recomienda consultar al médico antes de empezar si hay alguna condición de salud. Práctica y realista, para empezar a hacer ejercicio en casa de forma segura y gradual.",
     en:"Act as a physical activity instructor. Design a gentle exercise routine to do at home, for a healthy person who wants to start moving more, with no equipment. Include warm-up, basic exercises with moderate reps, stretching, and how to progress weekly. Focus on consistency and safe technique. Recommend consulting a doctor before starting if there's any health condition. Practical and realistic, to start exercising at home safely and gradually."}},

{ cat:"health", t:{es:"Plan de bienestar para tu equipo de trabajo", en:"Wellness plan for your work team"},
  p:{es:"Actúa como consultor de bienestar organizacional. Diseña un plan sencillo de bienestar para los empleados de [TIPO DE EMPRESA/EQUIPO]. Incluye: pausas activas, manejo del estrés, hábitos saludables durante la jornada, ergonomía básica, y actividades de integración. Práctico, de bajo costo y aplicable. Enfocado en mejorar el ambiente, la salud general y el ánimo del equipo de forma positiva. Útil y realista, para promover el bienestar en mi equipo de trabajo de forma sencilla y efectiva.",
     en:"Act as an organizational wellness consultant. Design a simple wellness plan for the employees of [TYPE OF COMPANY/TEAM]. Include: active breaks, stress management, healthy habits during the workday, basic ergonomics, and team-building activities. Practical, low-cost and applicable. Focused on improving the team's environment, general health and mood positively. Useful and realistic, to promote wellbeing in my work team simply and effectively."}},

{ cat:"health", t:{es:"Mensajes motivadores sobre bienestar", en:"Motivating wellness messages"},
  p:{es:"Actúa como coach de hábitos saludables. Escribe 10 mensajes cortos y motivadores para animar a las personas a cuidar su salud y mantener hábitos saludables (moverse, hidratarse, descansar, alimentarse bien, cuidar su mente). Que sean positivos, cercanos e inspiren a la acción sin culpar ni asustar. Ideales para redes sociales o recordatorios. Que promuevan el bienestar de forma amable y motivadora. Útiles y genuinos, listos para compartir y motivar a cuidar la salud de forma positiva.",
     en:"Act as a healthy habits coach. Write 10 short, motivating messages to encourage people to care for their health and maintain healthy habits (move, hydrate, rest, eat well, care for their mind). They should be positive, warm and inspire action without blaming or scaring. Ideal for social media or reminders. They should promote wellbeing kindly and motivatingly. Useful and genuine, ready to share and motivate caring for health positively."}},

{ cat:"health", t:{es:"Rutina de autocuidado semanal", en:"Weekly self-care routine"},
  p:{es:"Eres facilitador de bienestar integral. Diseña una rutina de autocuidado semanal sencilla para una persona con vida ocupada que quiere cuidar su salud física y emocional. Incluye momentos de descanso, movimiento, conexión social, desconexión digital, y algo que disfrute. Realista y sostenible, con pequeños hábitos diarios. Que ayude a recargar energía y bajar el estrés de forma equilibrada. Práctica y adaptable a una vida ocupada, para cuidarme de forma integral sin que sea una carga.",
     en:"You're a holistic wellness facilitator. Design a simple weekly self-care routine for a busy person who wants to care for their physical and emotional health. Include moments of rest, movement, social connection, digital disconnection, and something they enjoy. Realistic and sustainable, with small daily habits. To help recharge energy and lower stress in a balanced way. Practical and adaptable to a busy life, to care for myself holistically without it being a burden."}},

];
