// ============================================================
//  ARSENAL IA — BIBLIOTECA DE PROMPTS (parte 12)
//  Rumbo a 50: Marketing · Ventas · Redes · Copywriting (+10 c/u)
// ============================================================

const PROMPTS_12 = [

// ---------- MARKETING (+10) ----------
{ cat:"marketing", t:{es:"Propuesta única de venta (PUV)", en:"Unique selling proposition (USP)"},
  p:{es:"Actúa como estratega de marketing. Ayúdame a definir la propuesta única de venta de [PRODUCTO/NEGOCIO]: eso que me hace diferente y mejor que la competencia y que ningún otro puede decir igual. Dame 5 opciones de PUV claras y potentes, explica por qué cada una funcionaría, y marca la más fuerte. Que sea el centro de toda mi comunicación. Convincente y verdadera.",
     en:"Act as a marketing strategist. Help me define the unique selling proposition of [PRODUCT/BUSINESS]: what makes me different and better than the competition that no one else can claim the same. Give me 5 clear, powerful USP options, explain why each would work, and mark the strongest. It should be the center of all my communication. Convincing and true."}},

{ cat:"marketing", t:{es:"Plan de marketing trimestral", en:"Quarterly marketing plan"},
  p:{es:"Eres director de marketing. Crea un plan de marketing para los próximos 3 meses para [NEGOCIO]. Define: los objetivos del trimestre, las acciones por mes, en qué canales enfocarme, qué contenido y campañas hacer, y cómo medir resultados. Organízalo de forma clara y realista para un negocio pequeño. Que me dé un rumbo claro de qué hacer cada mes para crecer. Práctico y accionable.",
     en:"You're a marketing director. Create a marketing plan for the next 3 months for [BUSINESS]. Define: the quarter's objectives, the actions per month, what channels to focus on, what content and campaigns to do, and how to measure results. Organize it clearly and realistically for a small business. It should give me a clear direction of what to do each month to grow. Practical and actionable."}},

{ cat:"marketing", t:{es:"Estrategia de contenido que atrae clientes", en:"Content strategy that attracts customers"},
  p:{es:"Actúa como experto en marketing de atracción. Diséñame una estrategia de contenido para atraer clientes hacia [NEGOCIO/PRODUCTO] de forma orgánica. Define: qué temas tratar que interesen a mi cliente ideal, qué formatos usar, cómo convertir a quien consume mi contenido en cliente, y cómo ser constante. Que atraiga gente interesada y la lleve naturalmente hacia la compra. Práctica y enfocada en resultados.",
     en:"Act as an inbound marketing expert. Design me a content strategy to attract customers to [BUSINESS/PRODUCT] organically. Define: what topics to cover that interest my ideal customer, what formats to use, how to convert content consumers into customers, and how to be consistent. It should attract interested people and lead them naturally toward purchase. Practical and results-focused."}},

{ cat:"marketing", t:{es:"Campaña para una fecha comercial", en:"Campaign for a commercial date"},
  p:{es:"Eres experto en marketing estacional. Para [FECHA COMERCIAL: día sin IVA, hot sale, navidad, etc.], diséñame una campaña completa para vender [PRODUCTO]. Incluye: el ángulo y mensaje acorde a la fecha, la oferta especial, las publicaciones para anunciarla, la estrategia de urgencia, y cómo maximizar las ventas en esos días. Que aproveche al máximo la fecha comercial para vender más. Práctica y lista para ejecutar.",
     en:"You're a seasonal marketing expert. For [COMMERCIAL DATE: tax-free day, hot sale, Christmas, etc.], design me a complete campaign to sell [PRODUCT]. Include: the angle and message fitting the date, the special offer, the posts to announce it, the urgency strategy, and how to maximize sales those days. It should make the most of the commercial date to sell more. Practical and ready to execute."}},

{ cat:"marketing", t:{es:"Mensajes para diferentes tipos de cliente", en:"Messages for different customer types"},
  p:{es:"Actúa como estratega de marketing. Mi producto [PRODUCTO] le sirve a distintos tipos de clientes. Ayúdame a crear mensajes adaptados a cada uno: identifica 3 o 4 tipos de cliente que podrían comprarlo, y para cada uno dame el mensaje que más le hablaría según lo que le importa, su dolor o su deseo. Que cada cliente sienta que el producto es perfecto para él. Específicos y persuasivos.",
     en:"Act as a marketing strategist. My product [PRODUCT] serves different types of customers. Help me create messages adapted to each: identify 3 or 4 customer types that could buy it, and for each give me the message that would speak to them most based on what they care about, their pain or desire. Each customer should feel the product is perfect for them. Specific and persuasive."}},

{ cat:"marketing", t:{es:"Cómo destacar en un mercado saturado", en:"How to stand out in a saturated market"},
  p:{es:"Eres consultor de marketing. Mi negocio [NEGOCIO] está en un mercado muy saturado con mucha competencia. Ayúdame a destacar: cómo encontrar un ángulo diferente, cómo posicionarme de forma única, qué estrategias usar para sobresalir sin competir solo por precio, y cómo llamar la atención de los clientes en medio de tanta oferta. Dame ideas concretas y aplicables para diferenciarme y ganar visibilidad. Práctico y creativo.",
     en:"You're a marketing consultant. My business [BUSINESS] is in a very saturated market with lots of competition. Help me stand out: how to find a different angle, how to position myself uniquely, what strategies to use to stand out without competing only on price, and how to grab customers' attention amid so much supply. Give me concrete, applicable ideas to differentiate myself and gain visibility. Practical and creative."}},

{ cat:"marketing", t:{es:"Promoción de boca a boca", en:"Word-of-mouth promotion"},
  p:{es:"Actúa como experto en marketing orgánico. Quiero que mis propios clientes me recomienden y hablen de [NEGOCIO/PRODUCTO]. Dame estrategias para generar boca a boca: cómo dar una experiencia que la gente quiera compartir, cómo incentivar las recomendaciones, cómo facilitar que me refieran, y cómo convertir clientes felices en promotores. Práctico y de bajo costo, para que crezca gracias a las recomendaciones. Aplicable a un negocio pequeño.",
     en:"Act as an organic marketing expert. I want my own customers to recommend me and talk about [BUSINESS/PRODUCT]. Give me strategies to generate word of mouth: how to give an experience people want to share, how to incentivize recommendations, how to make referring me easy, and how to turn happy customers into promoters. Practical and low-cost, so it grows thanks to recommendations. Applicable to a small business."}},

{ cat:"marketing", t:{es:"Embudo de contenido para vender", en:"Content funnel to sell"},
  p:{es:"Eres estratega de marketing de contenidos. Diséñame un embudo de contenido para [PRODUCTO]: qué contenido crear para atraer a desconocidos, qué contenido para generar confianza en los interesados, y qué contenido para convertir a los que están por comprar. Para cada etapa, los temas y formatos. Que lleve a la gente paso a paso desde que me conoce hasta que me compra. Práctico y estratégico, orientado a ventas.",
     en:"You're a content marketing strategist. Design me a content funnel for [PRODUCT]: what content to create to attract strangers, what content to build trust in interested people, and what content to convert those about to buy. For each stage, the topics and formats. It should lead people step by step from knowing me to buying from me. Practical and strategic, sales-oriented."}},

{ cat:"marketing", t:{es:"Conecta emocionalmente con tu cliente", en:"Connect emotionally with your customer"},
  p:{es:"Actúa como experto en marketing emocional. Quiero que mi marca [MARCA] conecte emocionalmente con [PÚBLICO], no solo que venda un producto. Dame estrategias: qué emociones y valores activar, cómo contar historias que conecten, cómo hacer que la gente sienta algo con mi marca, y cómo crear ese vínculo emocional que genera lealtad. Con ejemplos de mensajes o ideas. Que la gente se identifique y se enamore de mi marca. Auténtico y poderoso.",
     en:"Act as an emotional marketing expert. I want my brand [BRAND] to connect emotionally with [AUDIENCE], not just sell a product. Give me strategies: what emotions and values to activate, how to tell stories that connect, how to make people feel something with my brand, and how to create that emotional bond that builds loyalty. With examples of messages or ideas. People should identify with and fall in love with my brand. Authentic and powerful."}},

{ cat:"marketing", t:{es:"Plan para relanzar un producto", en:"Plan to relaunch a product"},
  p:{es:"Eres experto en lanzamientos. Tengo un producto [PRODUCTO] que ya existe pero quiero relanzarlo para darle nueva vida y vender más. Dame un plan de relanzamiento: cómo generar interés renovado, qué ángulo o novedad destacar, cómo crear expectativa, qué oferta de relanzamiento ofrecer, y cómo comunicarlo para que se sienta fresco y atractivo otra vez. Que reactive las ventas de un producto que ya tenía. Práctico y aplicable.",
     en:"You're a launch expert. I have a product [PRODUCT] that already exists but I want to relaunch it to give it new life and sell more. Give me a relaunch plan: how to generate renewed interest, what angle or novelty to highlight, how to build anticipation, what relaunch offer to give, and how to communicate it so it feels fresh and attractive again. It should reactivate sales of a product I already had. Practical and applicable."}},

// ---------- VENTAS (+10) ----------
{ cat:"sales", t:{es:"Maneja la objeción 'no lo necesito'", en:"Handle 'I don't need it'"},
  p:{es:"Actúa como cerrador experto. El cliente dice que no necesita [PRODUCTO]. Dame 5 formas de responder que: le ayuden a ver una necesidad que quizás no había notado, conecten el producto con un deseo o problema real, despierten su interés sin presionar, y mantengan la conversación abierta. Respuestas naturales y respetuosas, listas para usar por chat. Que conviertan el 'no lo necesito' en curiosidad.",
     en:"Act as an expert closer. The customer says they don't need [PRODUCT]. Give me 5 ways to respond that: help them see a need they may not have noticed, connect the product with a real desire or problem, spark their interest without pressuring, and keep the conversation open. Natural, respectful responses, ready to use via chat. To turn 'I don't need it' into curiosity."}},

{ cat:"sales", t:{es:"Genera confianza con un cliente nuevo", en:"Build trust with a new customer"},
  p:{es:"Eres experto en ventas relacionales. Un cliente nuevo que no me conoce está interesado en [PRODUCTO] pero desconfía. Dame estrategias y mensajes para generar confianza rápido: cómo demostrar que soy serio y confiable, qué mostrar para reducir su miedo, cómo dar garantías, y cómo hacer que se sienta seguro de comprarme aunque sea la primera vez. Mensajes cercanos y honestos, listos para usar. Que rompan la desconfianza inicial.",
     en:"You're a relational sales expert. A new customer who doesn't know me is interested in [PRODUCT] but is wary. Give me strategies and messages to build trust fast: how to show I'm serious and trustworthy, what to show to reduce their fear, how to give guarantees, and how to make them feel safe buying from me even if it's the first time. Warm, honest messages, ready to use. To break the initial distrust."}},

{ cat:"sales", t:{es:"Cierra la venta con una pregunta", en:"Close the sale with a question"},
  p:{es:"Actúa como cerrador experto. Enséñame a usar preguntas de cierre para llevar al cliente a comprar [PRODUCTO] sin presionar. Dame 8 preguntas de cierre que inviten al cliente a decir que sí de forma natural (por ejemplo, sobre la forma de pago, la fecha, la versión que prefiere). Explica cuándo usar cada una y cómo funciona. Que ayuden a cerrar la venta de forma suave y efectiva. Naturales y aplicables por chat o en persona.",
     en:"Act as an expert closer. Teach me to use closing questions to lead the customer to buy [PRODUCT] without pressuring. Give me 8 closing questions that invite the customer to say yes naturally (for example, about the payment method, the date, the version they prefer). Explain when to use each and how it works. They should help close the sale smoothly and effectively. Natural and applicable via chat or in person."}},

{ cat:"sales", t:{es:"Vende contando una historia", en:"Sell by telling a story"},
  p:{es:"Eres experto en venta con storytelling. Ayúdame a vender [PRODUCTO] contando una historia que conecte y persuada. Dame una historia (real o representativa) que muestre el problema que resuelve mi producto, cómo alguien lo solucionó con él, y la transformación que logró. Que genere identificación y deseo, y lleve naturalmente a querer comprar. Auténtica y persuasiva, lista para usar en ventas o contenido. Que venda sin parecer venta.",
     en:"You're a storytelling sales expert. Help me sell [PRODUCT] by telling a story that connects and persuades. Give me a story (real or representative) that shows the problem my product solves, how someone fixed it with it, and the transformation they achieved. It should generate identification and desire, and naturally lead to wanting to buy. Authentic and persuasive, ready to use in sales or content. To sell without seeming like a sale."}},

{ cat:"sales", t:{es:"Aumenta tus ventas con preguntas correctas", en:"Boost sales with the right questions"},
  p:{es:"Actúa como experto en venta consultiva. Quiero hacer mejores preguntas en mis ventas de [PRODUCTO] para entender al cliente y venderle mejor. Dame un set de preguntas estratégicas: para descubrir su necesidad real, su situación, su presupuesto, su urgencia, y qué lo motivaría a comprar. Ordénalas para que la conversación fluya. Que me ayuden a vender entendiendo en vez de presionando. Naturales y aplicables en cualquier venta.",
     en:"Act as a consultative selling expert. I want to ask better questions in my [PRODUCT] sales to understand the customer and sell better. Give me a set of strategic questions: to uncover their real need, their situation, their budget, their urgency, and what would motivate them to buy. Order them so the conversation flows. They should help me sell by understanding instead of pressuring. Natural and applicable in any sale."}},

{ cat:"sales", t:{es:"Convence con beneficios, no características", en:"Convince with benefits, not features"},
  p:{es:"Eres experto en ventas. Tiendo a vender [PRODUCTO] enumerando sus características pero no convenzo. Enséñame a vender con beneficios: ayúdame a convertir las características de mi producto en beneficios que le importen al cliente (qué gana, cómo mejora su vida, qué problema resuelve). Dame ejemplos de cómo transformar 'tiene X' en 'esto significa para ti Y'. Que mi forma de vender conecte con lo que el cliente realmente quiere.",
     en:"You're a sales expert. I tend to sell [PRODUCT] by listing its features but I'm not convincing. Teach me to sell with benefits: help me turn my product's features into benefits the customer cares about (what they gain, how it improves their life, what problem it solves). Give me examples of how to transform 'it has X' into 'this means Y for you'. So my way of selling connects with what the customer really wants."}},

{ cat:"sales", t:{es:"Reactiva clientes que no compran hace tiempo", en:"Reactivate customers who haven't bought in a while"},
  p:{es:"Actúa como experto en reactivación de clientes. Tengo clientes que me compraron [PRODUCTO/SERVICIO] antes pero hace tiempo que no vuelven. Dame una estrategia y mensajes para reactivarlos: cómo retomar el contacto de forma cercana, qué ofrecerles para que vuelvan, cómo recordarles el valor que doy, y cómo motivarlos a comprar de nuevo. Mensajes listos para WhatsApp o email. Que recuperen clientes que ya me conocen y confían en mí.",
     en:"Act as a customer reactivation expert. I have customers who bought [PRODUCT/SERVICE] before but haven't returned in a while. Give me a strategy and messages to reactivate them: how to resume contact warmly, what to offer them to come back, how to remind them of the value I give, and how to motivate them to buy again. Messages ready for WhatsApp or email. To recover customers who already know and trust me."}},

{ cat:"sales", t:{es:"Cierra ventas en comentarios y mensajes", en:"Close sales in comments and messages"},
  p:{es:"Eres experto en ventas por redes sociales. La gente me pregunta por [PRODUCTO] en los comentarios y mensajes pero no logro cerrar. Dame un sistema: cómo responder a los comentarios de 'precio' o 'info' para llevarlos al privado, cómo continuar la conversación por mensaje, cómo presentar el producto y precio, y cómo cerrar la venta. Con mensajes listos para cada momento. Que convierta esas preguntas en ventas reales. Práctico y aplicable.",
     en:"You're a social media sales expert. People ask me about [PRODUCT] in comments and messages but I can't close. Give me a system: how to respond to 'price' or 'info' comments to move them to DMs, how to continue the conversation via message, how to present the product and price, and how to close the sale. With ready messages for each moment. To turn those questions into real sales. Practical and applicable."}},

{ cat:"sales", t:{es:"Vende sin bajar el precio", en:"Sell without lowering the price"},
  p:{es:"Actúa como experto en ventas de valor. Los clientes siempre me piden descuento en [PRODUCTO] y termino bajando el precio. Enséñame a vender sin tener que rebajar: cómo defender mi precio con seguridad, cómo enfocar la conversación en el valor, cómo responder cuando piden descuento, y qué ofrecer en lugar de bajar el precio (más valor, bonos, facilidades). Que cierre ventas manteniendo mi precio y mi ganancia. Con frases y enfoques aplicables.",
     en:"Act as a value selling expert. Customers always ask me for a discount on [PRODUCT] and I end up lowering the price. Teach me to sell without having to discount: how to defend my price confidently, how to focus the conversation on value, how to respond when they ask for a discount, and what to offer instead of lowering the price (more value, bonuses, payment options). To close sales keeping my price and my profit. With applicable phrases and approaches."}},

{ cat:"sales", t:{es:"Crea un guion de ventas completo", en:"Create a complete sales script"},
  p:{es:"Eres entrenador de ventas. Créame un guion de ventas completo para vender [PRODUCTO] de principio a fin. Incluye: cómo iniciar la conversación, cómo identificar la necesidad, cómo presentar el producto según lo que necesita, cómo manejar las 4 objeciones más comunes, cómo presentar el precio, y cómo cerrar. Con frases concretas para cada etapa. Que me sirva como guía para vender con confianza en cualquier conversación. Natural y efectivo.",
     en:"You're a sales trainer. Create me a complete sales script to sell [PRODUCT] from start to finish. Include: how to start the conversation, how to identify the need, how to present the product based on what they need, how to handle the 4 most common objections, how to present the price, and how to close. With concrete phrases for each stage. So it serves as a guide to sell with confidence in any conversation. Natural and effective."}},

// ---------- REDES SOCIALES (+10) ----------
{ cat:"social", t:{es:"Estrategia para crecer en Instagram", en:"Strategy to grow on Instagram"},
  p:{es:"Actúa como experto en Instagram. Tengo una cuenta de [NICHO] y quiero crecer en seguidores e interacción. Dame una estrategia completa: qué tipo de contenido publicar, cómo usar Reels, historias y publicaciones, con qué frecuencia, cómo aumentar el alcance, cómo aprovechar tendencias, y qué hábitos seguir. Realista y aplicable para crecer de forma orgánica paso a paso. Enfocada en resultados para [PÚBLICO]. Que haga crecer mi cuenta.",
     en:"Act as an Instagram expert. I have a [NICHE] account and want to grow followers and engagement. Give me a complete strategy: what type of content to post, how to use Reels, stories and posts, how often, how to increase reach, how to leverage trends, and what habits to follow. Realistic and applicable to grow organically step by step. Focused on results for [AUDIENCE]. To grow my account."}},

{ cat:"social", t:{es:"Guion de Reel educativo", en:"Educational Reel script"},
  p:{es:"Eres creador de contenido educativo. Escribe el guion de un Reel que enseñe algo útil sobre [TEMA] para [NICHO] en menos de 60 segundos. Incluye: un gancho que enganche en los primeros segundos, el contenido educativo resumido en lo esencial y fácil de entender, el texto en pantalla, y un cierre con llamada a la acción. Que aporte valor real, sea fácil de seguir, y haga que la gente lo guarde y comparta. Listo para grabar.",
     en:"You're an educational content creator. Write the script of a Reel that teaches something useful about [TOPIC] for [NICHE] in under 60 seconds. Include: a hook that engages in the first seconds, the educational content summarized to the essentials and easy to understand, the on-screen text, and a closing with a call to action. It should provide real value, be easy to follow, and make people save and share it. Ready to film."}},

{ cat:"social", t:{es:"Calendario de contenido para 2 semanas", en:"2-week content calendar"},
  p:{es:"Actúa como community manager. Crea un calendario de contenido para 2 semanas para [NEGOCIO/NICHO] en [RED SOCIAL]. Para cada día, dame: el tipo de contenido, el tema, el formato (Reel, carrusel, historia, foto) y el objetivo. Que combine contenido educativo, de entretenimiento, de venta y de conexión, manteniendo variedad. Organízalo en tabla. Realista y listo para ejecutar, que mantenga mi cuenta activa y estratégica esas 2 semanas.",
     en:"Act as a community manager. Create a 2-week content calendar for [BUSINESS/NICHE] on [SOCIAL NETWORK]. For each day, give me: the content type, the topic, the format (Reel, carousel, story, photo) and the goal. It should combine educational, entertainment, sales and connection content, keeping variety. Organize it in a table. Realistic and ready to execute, keeping my account active and strategic those 2 weeks."}},

{ cat:"social", t:{es:"Publicación para presentarte a tu audiencia", en:"Post to introduce yourself to your audience"},
  p:{es:"Eres experto en contenido de conexión. Ayúdame a crear una publicación para presentarme a mi audiencia de [NICHO] y que me conozcan mejor. Que cuente quién soy, qué hago, por qué lo hago y cómo puedo ayudarlos, de forma cercana y auténtica. Que genere conexión y confianza, y haga que la gente quiera seguirme. Con el texto listo y la estructura sugerida. Cálida y genuina, que humanice mi cuenta y conecte con la gente.",
     en:"You're a connection content expert. Help me create a post to introduce myself to my [NICHE] audience so they know me better. It should tell who I am, what I do, why I do it and how I can help them, warmly and authentically. It should create connection and trust, and make people want to follow me. With the text ready and the suggested structure. Warm and genuine, to humanize my account and connect with people."}},

{ cat:"social", t:{es:"Ideas de carruseles que aportan valor", en:"Value-adding carousel ideas"},
  p:{es:"Actúa como creador de contenido. Dame 10 ideas de carruseles para Instagram sobre [TEMA/NICHO] que aporten mucho valor y que la gente quiera guardar y compartir. Para cada idea: el título de la portada (gancho), de qué trataría, y por qué le serviría a mi audiencia. Que sean educativos, prácticos y útiles. Ordénalos por potencial. Que posicionen mi conocimiento y hagan crecer mi cuenta. Prácticos y aplicables para [PÚBLICO].",
     en:"Act as a content creator. Give me 10 carousel ideas for Instagram about [TOPIC/NICHE] that add lots of value and that people want to save and share. For each idea: the cover title (hook), what it would be about, and why it would help my audience. They should be educational, practical and useful. Sort them by potential. They should position my knowledge and grow my account. Practical and applicable for [AUDIENCE]."}},

{ cat:"social", t:{es:"Aumenta la interacción en tus publicaciones", en:"Increase engagement on your posts"},
  p:{es:"Eres experto en engagement. Mis publicaciones de [NICHO] tienen poca interacción (pocos likes y comentarios). Dame estrategias concretas para aumentarla: qué tipo de contenido genera más interacción, cómo escribir captions que inviten a comentar, cómo usar preguntas y llamados a la acción, cómo responder para generar conversación, y qué hábitos seguir. Práctico y aplicable, para que mis publicaciones tengan más vida y alcance. Que la gente interactúe más.",
     en:"You're an engagement expert. My [NICHE] posts have low interaction (few likes and comments). Give me concrete strategies to increase it: what type of content generates more interaction, how to write captions that invite comments, how to use questions and calls to action, how to reply to generate conversation, and what habits to follow. Practical and applicable, so my posts have more life and reach. So people interact more."}},

{ cat:"social", t:{es:"Guion para video promocional en redes", en:"Promotional video script for social"},
  p:{es:"Actúa como creador de contenido. Escribe el guion de un video corto para promocionar [PRODUCTO] en [RED SOCIAL] sin que se sienta como un anuncio molesto. Que enganche al inicio, muestre el producto de forma atractiva enfocándose en cómo ayuda, genere deseo, y termine con una invitación a comprar o saber más. Indica qué mostrar y qué decir. Dinámico y persuasivo, adaptado al formato de la red. Que genere interés y ventas.",
     en:"Act as a content creator. Write the script of a short video to promote [PRODUCT] on [SOCIAL NETWORK] without it feeling like an annoying ad. It should engage at the start, show the product attractively focusing on how it helps, generate desire, and end with an invitation to buy or learn more. Indicate what to show and what to say. Dynamic and persuasive, adapted to the network's format. To generate interest and sales."}},

{ cat:"social", t:{es:"Contenido detrás de cámaras", en:"Behind-the-scenes content"},
  p:{es:"Eres experto en contenido auténtico. Ayúdame a crear contenido 'detrás de cámaras' de mi [NEGOCIO/TRABAJO] para [RED SOCIAL] que conecte con mi audiencia. Dame ideas de qué mostrar del proceso, el día a día o lo que hay detrás de mi producto, cómo presentarlo de forma interesante, y por qué este tipo de contenido genera cercanía y confianza. Que humanice mi marca y haga que la gente conecte conmigo. Práctico y aplicable.",
     en:"You're an authentic content expert. Help me create 'behind the scenes' content of my [BUSINESS/WORK] for [SOCIAL NETWORK] that connects with my audience. Give me ideas of what to show of the process, the daily life or what's behind my product, how to present it interestingly, and why this type of content creates warmth and trust. It should humanize my brand and make people connect with me. Practical and applicable."}},

{ cat:"social", t:{es:"Responde a tu comunidad para fidelizar", en:"Respond to your community to build loyalty"},
  p:{es:"Actúa como community manager experto. Quiero responder a mi comunidad de [NICHO] de forma que genere fidelidad y conexión. Dame estrategias y ejemplos de cómo responder a los comentarios, mensajes y menciones para que la gente se sienta valorada, cómo crear conversación, cómo manejar tanto los positivos como las críticas, y cómo construir una comunidad fiel. Con ejemplos para distintas situaciones. Que la gente sienta cercanía y se quede conmigo.",
     en:"Act as an expert community manager. I want to respond to my [NICHE] community in a way that builds loyalty and connection. Give me strategies and examples of how to reply to comments, messages and mentions so people feel valued, how to create conversation, how to handle both positive ones and criticism, and how to build a loyal community. With examples for different situations. So people feel warmth and stay with me."}},

{ cat:"social", t:{es:"Plan para lanzar tu cuenta de cero", en:"Plan to launch your account from scratch"},
  p:{es:"Eres estratega de redes sociales. Voy a crear una cuenta nueva de [NICHO] desde cero y quiero arrancar bien. Dame un plan: cómo configurar el perfil para que se vea profesional, qué primeras publicaciones hacer, cómo conseguir mis primeros seguidores, qué contenido priorizar al inicio, y cómo crecer en los primeros meses. Realista y aplicable para empezar de cero sin audiencia. Que me dé un camino claro para arrancar mi cuenta con buen pie.",
     en:"You're a social media strategist. I'm going to create a new [NICHE] account from scratch and want to start well. Give me a plan: how to set up the profile so it looks professional, what first posts to make, how to get my first followers, what content to prioritize at the start, and how to grow in the first months. Realistic and applicable to start from zero with no audience. To give me a clear path to launch my account on the right foot."}},

// ---------- COPYWRITING (+10) ----------
{ cat:"copywriting", t:{es:"Fórmula de las 4 P para tu texto", en:"4 P formula for your copy"},
  p:{es:"Actúa como copywriter experto. Escribe un texto de venta para [PRODUCTO] usando la fórmula de las 4 P: Promesa (un beneficio atractivo), Pintar el cuadro (que se imagine el resultado), Prueba (credibilidad o testimonio) y Push (empujón final a la acción). Que conecte y persuada. Explica brevemente cada parte mientras lo escribes. Persuasivo y enfocado en lograr la venta. Listo para usar en una página o anuncio.",
     en:"Act as an expert copywriter. Write a sales copy for [PRODUCT] using the 4 P formula: Promise (an attractive benefit), Paint the picture (so they imagine the result), Proof (credibility or testimonial) and Push (final push to action). It should connect and persuade. Briefly explain each part as you write it. Persuasive and focused on achieving the sale. Ready to use on a page or ad."}},

{ cat:"copywriting", t:{es:"Texto para tu biografía de ventas", en:"Copy for your sales bio"},
  p:{es:"Eres copywriter experto. Escríbeme una biografía persuasiva para mi perfil de [RED SOCIAL/SITIO] que además de presentarme, ayude a vender [PRODUCTO/SERVICIO]. Que deje claro a quién ayudo y cómo, genere interés y confianza, y termine con una invitación a la acción. Dame 3 versiones adaptadas al límite de caracteres. Que convierta a quien visita mi perfil en cliente potencial. Clara, atractiva y orientada a la venta. Marca la mejor.",
     en:"You're an expert copywriter. Write me a persuasive bio for my [SOCIAL NETWORK/SITE] profile that, besides introducing me, helps sell [PRODUCT/SERVICE]. It should make clear who I help and how, generate interest and trust, and end with a call to action. Give me 3 versions adapted to the character limit. To turn profile visitors into potential customers. Clear, attractive and sales-oriented. Mark the best one."}},

{ cat:"copywriting", t:{es:"Encabezados que captan la atención", en:"Headlines that grab attention"},
  p:{es:"Actúa como experto en encabezados. Para [PRODUCTO/CONTENIDO/OFERTA], dame 15 encabezados que capten la atención de inmediato y hagan que la persona quiera seguir leyendo. Varía las fórmulas: pregunta, beneficio, curiosidad, urgencia, número, advertencia. Que sean potentes y específicos. Marca los 3 más fuertes y explica por qué funcionan. Para usar en anuncios, páginas, correos o publicaciones. Que detengan y enganchen al lector.",
     en:"Act as a headline expert. For [PRODUCT/CONTENT/OFFER], give me 15 headlines that grab attention immediately and make the person want to keep reading. Vary the formulas: question, benefit, curiosity, urgency, number, warning. They should be powerful and specific. Mark the 3 strongest and explain why they work. To use in ads, pages, emails or posts. They should stop and hook the reader."}},

{ cat:"copywriting", t:{es:"Texto que vende un servicio", en:"Copy that sells a service"},
  p:{es:"Eres copywriter experto en servicios. Escribe un texto persuasivo para vender mi servicio de [SERVICIO] a [PÚBLICO]. Que explique el problema que resuelvo, presente mi servicio como la solución, destaque los beneficios y resultados que obtiene el cliente, genere confianza, responda la duda principal, y termine invitando a contactarme. Enfocado en el cliente y en resultados, no en una lista de tareas. Profesional, atractivo y orientado a conseguir clientes.",
     en:"You're an expert service copywriter. Write a persuasive copy to sell my [SERVICE] service to [AUDIENCE]. It should explain the problem I solve, present my service as the solution, highlight the benefits and results the customer gets, build trust, answer the main doubt, and end by inviting contact. Focused on the customer and results, not a task list. Professional, attractive and oriented to getting clients."}},

{ cat:"copywriting", t:{es:"Convierte características en deseo", en:"Turn features into desire"},
  p:{es:"Actúa como copywriter enfocado en beneficios. Mi producto [PRODUCTO] tiene estas características: [LISTA LAS CARACTERÍSTICAS]. Ayúdame a convertir cada característica en un beneficio que despierte deseo, mostrando qué gana el cliente y cómo mejora su vida. Dame el 'antes y después': la característica fría y su versión convertida en beneficio deseable. Que mi texto haga que el cliente quiera el producto por lo que va a lograr con él. Persuasivo y enfocado en el cliente.",
     en:"Act as a benefit-focused copywriter. My product [PRODUCT] has these features: [LIST THE FEATURES]. Help me turn each feature into a benefit that sparks desire, showing what the customer gains and how it improves their life. Give me the 'before and after': the cold feature and its version turned into a desirable benefit. So my copy makes the customer want the product for what they'll achieve with it. Persuasive and customer-focused."}},

{ cat:"copywriting", t:{es:"Texto para una oferta con descuento", en:"Copy for a discounted offer"},
  p:{es:"Eres copywriter de promociones. Escribe un texto persuasivo para promocionar [PRODUCTO] con un descuento especial. Que comunique la oferta de forma atractiva, destaque el ahorro y el valor, genere urgencia para aprovecharla, refuerce el beneficio principal, y termine con una llamada a la acción clara. Que el cliente sienta que es una oportunidad que no debe dejar pasar. Persuasivo y directo, listo para usar en redes, página o mensaje. Que impulse la compra.",
     en:"You're a promotions copywriter. Write a persuasive copy to promote [PRODUCT] with a special discount. It should communicate the offer attractively, highlight the savings and value, create urgency to take advantage of it, reinforce the main benefit, and end with a clear call to action. The customer should feel it's an opportunity not to miss. Persuasive and direct, ready to use on social media, a page or a message. To drive the purchase."}},

{ cat:"copywriting", t:{es:"Texto que genera confianza", en:"Copy that builds trust"},
  p:{es:"Actúa como copywriter experto en confianza. Para [PRODUCTO/NEGOCIO], escribe un texto que genere confianza y reduzca el miedo del cliente a comprar. Que transmita credibilidad, profesionalismo y seguridad, responda las dudas o miedos comunes, mencione garantías o respaldos, y haga que el cliente se sienta seguro de comprarme. Para usar en mi página o ventas, especialmente útil cuando el cliente no me conoce. Que derribe la desconfianza y acerque a la compra.",
     en:"Act as a trust-copy expert. For [PRODUCT/BUSINESS], write a copy that builds trust and reduces the customer's fear of buying. It should convey credibility, professionalism and security, answer common doubts or fears, mention guarantees or backing, and make the customer feel safe buying from me. To use on my page or sales, especially useful when the customer doesn't know me. To break down distrust and bring them closer to buying."}},

{ cat:"copywriting", t:{es:"Reescribe tu oferta para que sea irresistible", en:"Rewrite your offer to be irresistible"},
  p:{es:"Eres copywriter de respuesta directa. Esta es mi oferta actual de [PRODUCTO]: \"[PEGA TU OFERTA]\". Reescríbela para que sea irresistible: hazla más clara y atractiva, aumenta el valor percibido, mejora la presentación del precio y los beneficios, añade urgencia y reduce el riesgo. Muéstrame la versión mejorada y explícame qué cambiaste y por qué ahora convence más. Que pase de ser una oferta normal a una que el cliente no quiera dejar pasar.",
     en:"You're a direct-response copywriter. This is my current offer for [PRODUCT]: \"[PASTE YOUR OFFER]\". Rewrite it to be irresistible: make it clearer and more attractive, increase the perceived value, improve the presentation of the price and benefits, add urgency and reduce risk. Show me the improved version and explain what you changed and why it convinces more now. So it goes from a normal offer to one the customer doesn't want to miss."}},

{ cat:"copywriting", t:{es:"Texto para redes que vende sutilmente", en:"Social copy that sells subtly"},
  p:{es:"Actúa como copywriter de redes. Escribe 3 textos para publicaciones de [RED SOCIAL] que promocionen [PRODUCTO] de forma sutil, aportando valor en vez de solo vender. Uno que enseñe algo y conecte con el producto, uno que cuente una historia o caso, y uno que muestre un beneficio o resultado. Que generen interés y deseo, e inviten suavemente a comprar o saber más. Cercanos y persuasivos para [PÚBLICO]. Que vendan sin parecer venta directa.",
     en:"Act as a social copywriter. Write 3 copies for [SOCIAL NETWORK] posts that promote [PRODUCT] subtly, providing value instead of just selling. One that teaches something and connects with the product, one that tells a story or case, and one that shows a benefit or result. They should generate interest and desire, and gently invite buying or learning more. Warm and persuasive for [AUDIENCE]. To sell without seeming like direct selling."}},

{ cat:"copywriting", t:{es:"Crea una promesa que enganche", en:"Create a hooking promise"},
  p:{es:"Eres copywriter estratégico. Ayúdame a crear la promesa central de [PRODUCTO]: el gran beneficio o resultado que prometo, expresado de forma clara, creíble y deseable. Dame 7 versiones de una promesa potente que pueda usar como mensaje principal en mi publicidad y comunicación. Que resuma lo mejor que ofrezco y despierte el deseo de comprar. Marca la más fuerte y explícame por qué. Convincente, verdadera y memorable, que sea el corazón de mi mensaje.",
     en:"You're a strategic copywriter. Help me create the central promise of [PRODUCT]: the big benefit or result I promise, expressed clearly, believably and desirably. Give me 7 versions of a powerful promise I can use as the main message in my advertising and communication. It should sum up the best I offer and spark the desire to buy. Mark the strongest and explain why. Convincing, true and memorable, to be the heart of my message."}},

];
